### ISSUE TITLE
Allow running multiple custom config files via `--config` flag

### ISSUE THREAD

**Issue by bugbaba** [trufflesecurity/trufflehog#1001]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello Team :)

### Description

While trying out the new custom regex feature, I noticed that currently, it's only accepting one config file which restricts to only use one custom check at a time. It would be better to allow multiple config files and run them in one go.

Or the other not so great approach could be that when the custom config is passed the default checks aren't being run so that users can loop against multiple config files.

## Problem to be Addressed
Allow running multiple custom config files. 

## Description of the Preferred Solution
The `--config` flag can be passed multiple times or take a directory as input similar to [nuclei](https://github.com/projectdiscovery/nuclei).

--
Regards,
@bugbaba

**Comment by mcastorina** [comment]
Hey, thanks for trying out the new feature!

> it's only accepting one config file which restricts to only use one custom check at a time

For the time being, you should be able to put multiple configurations under `detectors:` like so:

```yaml
detectors:
- name: first detector
  keywords: ["keyword"]
  regex:
    foo: bar
- name: second detector
  keywords: ["keyword"]
  regex:
    bar: baz
```

**Comment by bugbaba** [comment]
Thanks it works. Though `Detector Type:` in the output should use the `name` defined in the yaml file instead of `CustomRegex`.

![image](https://user-images.githubusercontent.com/29960776/211718820-f4de76a8-849b-458d-a33e-0a9e061e948f.png)

**Comment by zricethezav** [comment]
<img width="927" alt="Screenshot 2024-02-16 at 3 37 17 PM" src="https://github.com/trufflesecurity/trufflehog/assets/15034943/517371db-0d3c-44d1-b002-dcfa9ee764a9">

This issue has been fixed (testing using sample custom config example in the readme)
