### ISSUE TITLE
Feature request: Only show the repo name, file name, line number and matched key

### ISSUE THREAD

**Issue by rupsray** [trufflesecurity/trufflehog#102]
Only show the repo name, file name, the line number of matched key and matched key, instead of showing everything in the committed file. This will increase the visibility.
If we send the output to a file, it is impossible to figure out the matched secret key.

**Comment by fahrishb** [comment]
you can edit the source code and comment out the line which prints the output you didnt want. @rupsray

**Comment by dxa4481** [comment]
For now, I suggest using the json output as a work around, it's a good idea to limit what's printed though, I'll probably truncate the surrounding text so it stays reasonable and doesn't get unwieldy.

**Comment by mterron** [comment]
On this same subject, can you add the repo name to the json output?

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

The default output is very close to what is requested here.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
