### ISSUE TITLE
Unable to test detection with an example secret and the --no-verification flag

### ISSUE THREAD

**Issue by mortenson** [trufflesecurity/trufflehog#1021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
```
% trufflehog --version
trufflehog 3.25.1
```

### Trace Output

https://gist.github.com/mortenson/b1bb008641ff54938de6a146815f9a79

### Expected Behavior

I should be able to use an example or dummy secret, for example an invalid AWS key, to test if trufflehog is working while using the `--no-verification` flag.

### Actual Behavior

Trufflehog does not fail when adding an example secret.

### Steps to Reproduce

```
git clone git@github.com:trufflesecurity/trufflehog.git
cd trufflehog
echo "AKIAIOSFODNN7EXAMPLE" > foo
git add foo
trufflehog git file://. --since-commit HEAD --no-update --no-verification --fail
# Notice that the above command does not fail as expected
```

## Environment
 * OS: macOS
 * Version: 13.1 (22C65)

## Additional Context

I wanted to test if the pre-commit example was working locally before adding trufflehog to my repo. Maybe I'm doing something wrong?

### References

* #0000

**Comment by dustin-decker** [comment]
AWS credentials require both the key ID (what you have) and the secret value (what you are missing) to be detected.

**Comment by mortenson** [comment]
Hi @dustin-decker - do you have a minimal replication steps for testing trufflehog in a similar way to what I was doing? i.e. Staging a file in Git that contains a secret and detecting it
