### ISSUE TITLE
Difference between GitHub scan and Filesystem scan results

### ISSUE THREAD

**Issue by brian-hamill-bv** [trufflesecurity/trufflehog#1025]
### TruffleHog Version
`trufflehog 3.25.2`

### Expected Behavior

The GitHub scan results and Filesystem results should have the same number of findings.

### Actual Behavior

There is a large difference in the number of results identified between github and filesystem scans.

### Steps to Reproduce

Scan a GitHub repository, for example OWASP/SEDATED:

```bash
trufflehog github --repo=https://github.com/OWASP/SEDATED --no-verification --json > results.json && wc -l < results.json
      50
```

Then clone the repo with `git clone git@github.com:OWASP/SEDATED.git` and scan the repo with the filesystem scan:

```bash
trufflehog filesystem --directory SEDATED --no-verification --json > results.json && wc -l < results.json
    1472
```

## Environment
 * OS: MacOS 12.6.1

**Comment by dxa4481** [comment]
Hi there,

This isn't a bug, the GitHub scan scans the entire history of the project, where as the filesystem scan will only scan the current commits.

**Comment by brian-hamill-bv** [comment]
Hi Dylan, why would this cause the GitHub scan to produce fewer results than the filesystem scan?  
Surely the GitHub scan would have more findings if it's including historical issues?

**Comment by brian-hamill-bv** [comment]
@dxa4481 what are your thoughts on the GitHub scan having less results than the filesystem scan?

**Comment by GeeksikhSecurity** [comment]
Does the filesystem scan the subfolders or just the current folder in the local filesystem scans?
