### ISSUE TITLE
Add github action output

### ISSUE THREAD

**Issue by james-callahan** [trufflesecurity/trufflehog#1027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add trufflehog structured output as a github action output

## Problem to be Addressed

Currently the trufflehog github action does not have any outputs. This makes it impossible to introspect the output of trufflehog from subsequent steps.

This would be useful for filtering out known false positives (related: https://github.com/trufflesecurity/trufflehog/issues/675); or implementing custom reporting (related: https://github.com/trufflesecurity/trufflehog/issues/1026)

## Description of the Preferred Solution

The trufflehog action should create an output of the json output

To create an output, send a key/value pair to the file in `GITHUB_OUTPUT`. [See docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)

**Comment by ahrav** [comment]
This should be resolved with release [v3.31.3](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.31.3) Thanks for the enhancement issue :)

**Comment by james-callahan** [comment]
This appears to have been reverted via https://github.com/trufflesecurity/trufflehog/pull/1219

Could this be reopened?
