### ISSUE TITLE
Scan sometimes displays wrong line number

### ISSUE THREAD

**Issue by RebeckaForsberg** [trufflesecurity/trufflehog#1031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
3.25.2

### Expected Behavior

When running the Trufflehog the output containing the line number should match the line in the actual commit.

### Actual Behavior

The lines do sometimes not match.

### Steps to Reproduce
We are running Trufflehog on internal repositories with the command:
trufflehog git <URL>  --only-verified

and the output in the terminal shows a line number. When searching for the commit in Azure DevOps the secret sometimes appears on a different line than stated in the output. 

## Environment
 * OS: macOS Monterey
 * Version 12.6

## Additional Context
When the lines do not match, the line number in the commit is around five lines below or above.

**Comment by dustin-decker** [comment]
Could you provide the secret type that you observed this issue with?

**Comment by zricethezav** [comment]
@RebeckaForsberg if this is still an issue feel free to reopen. If you do can you provide more details and a way for us to reproduce this bug? Thanks!
