### ISSUE TITLE
Github actions uses latest version of image regardless specifying the version in workflow file

### ISSUE THREAD

**Issue by Kruthika0** [trufflesecurity/trufflehog#1040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

TruffleHog Version
3.24

Expected Behavior
When running Trufflehog via Github actions, trufflehog uses latest version of docker image regardless it being specified explicitly to use previous version.

Actual Behavior
Trufflehog Github action should use the version specified in workflow file

Steps to Reproduce

![trufflehog](https://user-images.githubusercontent.com/111109922/214100144-edc20d9d-8770-49f2-9ca7-1e183de03a1c.png)
**Run trufflesecurity/trufflehog@v3.24.0**
/usr/local/bin/docker run --name ghcriotrufflesecuritytrufflehoglatest_5c2248 --label [6](https://github.com/Sentinel-One/Trufflehog-Secrets-Scanner/actions/runs/3987739979/jobs/6837959054#step:6:7)0e226 --workdir /github/workspace --rm -e "INPUT_PATH" -e "INPUT_BASE" -e "INPUT_HEAD" -e "INPUT_EXTRA_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_EVENT_PATH" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/runner/_work/":"/github/workspace" ghcr.io/trufflesecurity/trufflehog:latest  "git" "file://./" "--since-commit" "" "--branch" "master" "--fail" "--no-update" "
time="2023-01-23T15:14:30Z" level=debug msg="running version 3.25.2"
2023/01/23 15:14:30 [updater parent] run
2023/01/23 15:14:30 [updater parent] starting /usr/bin/trufflehog
time="2023-01-23T15:14:30Z" **level=debug msg="running version 3.25.2"**

**Comment by mcastorina** [comment]
I think there are two versions here, which can be confusing.

The first is the github action version which is `v3.24.0`. The second is the trufflehog version which is `latest` (in this case `v3.25.2`). (See the [github action YAML](https://github.com/trufflesecurity/trufflehog/blob/v3.24.0/action.yml#L25))

Currently, you can only specify the github action version, but not the trufflehog version. A github action input will probably need to be added to support pinning a trufflehog version.

**Comment by Kruthika0** [comment]
Hi @mcastorina do we have an ETA for this?

**Comment by mcastorina** [comment]
This isn't currently a priority but contributions are welcome!

**Comment by mcastorina** [comment]
`version` will be available in the next release as a GitHub action input.

```yaml
  with:
    version: v3.24.0
```

**Comment by mcastorina** [comment]
Update: it seems like the `image` field doesn't use the GitHub Action expression syntax. I'm not a GitHub Actions expert so any help here would be appreciated.

**Comment by zricethezav** [comment]
https://github.com/trufflesecurity/trufflehog/blob/834163acf5343c103e5d1b8bd88a952f23b85bc8/action.yml#L21-L24 @Kruthika0 you can now specify the version number
