### ISSUE TITLE
False reporting on jacoco.xml report from codescan

### ISSUE THREAD

**Issue by pax95** [trufflesecurity/trufflehog#1055]
### Community Note

Hi
I'm using jacoco code coverage maven plugin to generate code coverage reports on java projects https://github.com/jacoco/jacoco. This plugin outputs a code coverage report as cacoco.xml in the target directory. 
Truffelhog reports a violation on this file -> Generic API Key - Found in target/site/jacoco/jacoco.xml at line 1

I'm wondering what has triggered this state.

**Comment by zricethezav** [comment]
The generic api key detector is no longer included in the default detector list. Closing this issue
