### ISSUE TITLE
Tab character added to output filename

### ISSUE THREAD

**Issue by diogo-fernan** [trufflesecurity/trufflehog#1060]
## TruffleHog Version

```
$ trufflehog --version
trufflehog 3.26.0
```

## Trace Output

```
$ trufflehog git file://. --since-commit HEAD --json --no-verification --fail --trace
{"level":"debug","msg":"running version 3.26.0","time":"2023-02-01T15:00:10+01:00"}
{"level":"debug","msg":"running version 3.26.0","time":"2023-02-01T15:00:10+01:00"}
{"level":"debug","msg":"running with up to 1 workers","time":"2023-02-01T15:00:10+01:00"}
{"level":"debug","msg":"loaded 2 decoders","time":"2023-02-01T15:00:10+01:00"}
{"level":"debug","msg":"loaded 731 detectors total, 0 with verification enabled. 731 with verification disabled","time":"2023-02-01T15:00:10+01:00"}
2023-02-01T15:00:10+01:00       info-1  trufflehog      cloned repo     {"path": "."}
2023-02-01T15:00:10+01:00       info-1  trufflehog      scanning repo   {"repo": "https://github.com/<org>/<repo>.git", "base": "be9dac16b41dc3e2994a5a6e89828a1cfc12ca72", "head": ""}
2023-02-01T15:00:10+01:00       info-1  trufflehog      reached base commit     {"repo": "https://github.com/<org>/<repo>.git", "commit": "be9dac16b41dc3e2994a5a6e89828a1cfc12ca72"}
2023-02-01T15:00:10+01:00       info-1  trufflehog      scanning unstaged changes       {"path": "."}
2023-02-01T15:00:10+01:00       info-2  trufflehog      scanning unstaged changes from git      {"filename": "filename 2\t", "commit": "", "file": "filename 2\t"}
2023-02-01T15:00:10+01:00       info-1  trufflehog      scanning git repo complete      {"Repo": "https://github.com/<org>/<repo>.git", "path": ".", "time": 62379000}
{"SourceMetadata":{"Data":{"Git":{"commit":"Unstaged","file":"filename 2\t","repository":"https://github.com/<org>/<repo>.git","timestamp":"0001-01-01 00:00:00 +0000 UTC","line":2}}},"SourceID":0,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":2,"DetectorName":"AWS","DecoderName":"PLAIN","Verified":false,"Raw":"AKIA...","Redacted":"AKIA...","ExtraData":null,"StructuredData":null}
{"level":"debug","msg":"scanned 2 chunks","time":"2023-02-01T15:00:11+01:00"}
{"level":"debug","msg":"scanned 145 bytes","time":"2023-02-01T15:00:11+01:00"}
{"level":"debug","msg":"exiting with code 183 because results were found","time":"2023-02-01T15:00:11+01:00"}
```

## Expected Behavior

```
$ mv filename\ 2 "filename2"
$ git add .
$ trufflehog git file://. --since-commit HEAD --json --no-verification --fail
{"SourceMetadata":{"Data":{"Git":{"commit":"Unstaged","file":"filename2","repository":"https://github.com/<org>/<repo>","timestamp":"0001-01-01 00:00:00 +0000 UTC","line":2}}},"SourceID":0,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":2,"DetectorName":"AWS","DecoderName":"PLAIN","Verified":false,"Raw":"AKIA...","Redacted":"AKIA...","ExtraData":null,"StructuredData":null}
```

## Actual Behavior

```
$ mv filename2 "filename 2"
$ git add .
$ trufflehog git file://. --since-commit HEAD --json --no-verification --fail
{"SourceMetadata":{"Data":{"Git":{"commit":"Unstaged","file":"filename 2\t","repository":"https://github.com/<org>/<repo>","timestamp":"0001-01-01 00:00:00 +0000 UTC","line":2}}},"SourceID":0,"SourceType":16,"SourceName":"trufflehog - git","DetectorType":2,"DetectorName":"AWS","DecoderName":"PLAIN","Verified":false,"Raw":"AKIA...","Redacted":"AKIA...","ExtraData":null,"StructuredData":null}
```

## Environment

 * OS: macOS
 * Version: Monterey 12.6.3

## Additional Context

TruffleHog seems to be adding a `\t` character to the end of a file whose name contains a space in the name.

**Comment by mcastorina** [comment]
Interestingly, I think this is coming directly from `git` (`0x09` is the `\t` character).

```
» git log -p | grep '+++' | xxd
00000000: 2b2b 2b20 622f 6669 6c65 6e61 6d65 2032  +++ b/filename 2
00000010: 090a                                     ..
```

Steps to reproduce:
```bash
mkdir test
cd test
git init
echo foo > 'filename 2'
git add 'filename 2'
git commit -m 'test'
git log -p | grep '+++' | xxd
```

**Comment by diogo-fernan** [comment]
Thanks @mcastorina. I can also replicate your test.

I have just submitted a bug report to git via `git@vger.kernel.org`.

**Comment by diogo-fernan** [comment]
@mcastorina FYI this appears to be by design and not a bug. Here is what I have been conveyed:

> The code that adds this tab in the output of `git log` and friends has
changed a bit since it was originally added in 1a9eb3b9d5
("git-diff/git-apply: make diff output a bit friendlier to GNU patch
(part 2)", 2006-09-22), but in that commit you can see the original
motivation. Here's an online view: https://github.com/git/git/commit/1a9eb3b9d50367bee8fe85022684d812816fe531

> I sense there is some sort of ulterior motive here that hasn't come
across yet. Are you trying to parse the output of `git log` to find
something? Would `git diff-tree` work, e.g., if you're mostly just after
the filenames involved?  Depending on what you're trying to achieve, it
could be a bit simpler to parse `git diff-tree` and other "plumbing"
commands, rather than `git log` and other such "porcelain" commands.

Perhaps Trufflehog should parse the output of another `git` command instead of `git log`?

**Comment by mcastorina** [comment]
Wow, this is a fascinating bit of history, thanks for digging into it.

From first inspection `diff-tree` doesn't appear to have all the information we need. Trufflehog needs a history of commits and the diffs between each, which is why we are currently parsing `git log` (with `-p` flag). If you have suggestions for "plumbing" commands that would work better for our use case I'd be happy to look into it.

I was curious what would happen if a filename ended or contained a tab character, and it looks like it is quoted with the tab character escaped: `"b/filename\t2"`. In regards to this specific issue, I think it would be okay to trim any trailing tab characters from the filename.

**Comment by diogo-fernan** [comment]
Thanks for your help @mcastorina. I have added a workaround in my project to trim the trailing tabs whenever those occur.

**Comment by mcastorina** [comment]
Trufflehog should parse the filename correctly as well; we are using the `git` CLI but that is an implementation detail in my opinion.
