### ISSUE TITLE
Add structured data to custom regex detector's results

### ISSUE THREAD

**Issue by fabricat** [trufflesecurity/trufflehog#1063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Additional information could be added to enrich the results of the custom regex detectors.

## Problem to be Addressed
Regex detector is a very powerful and flexible feature (yet in alpha stage), but its output is too poor currently.

## Description of the Preferred Solution

I'd appreciate if the output results include:
* name of the **detector** (coming from the config file, not `CustomRegex` - in the JSON output this can be added in `ExtraData`)
* name and value of each **regex submatch** (in the JSON output this can be added **as an object** within `StructuredData`)
* **redacted** string (as like as [some detectors](https://github.com/trufflesecurity/trufflehog/blob/80a68b84c2db1d05bab20f85dbb6cd0830adb5af/pkg/detectors/ftp/ftp.go#L59) already do - this requires a _new key_ in the configuration file)

### References

* https://github.com/trufflesecurity/trufflehog/blob/80a68b84c2db1d05bab20f85dbb6cd0830adb5af/pkg/custom_detectors/custom_detectors.go#L96

**Comment by zricethezav** [comment]
Closing with the release of https://github.com/trufflesecurity/trufflehog/releases/tag/v3.41.0
