### ISSUE TITLE
TruffleHog github action - unable to parse inputs.version

### ISSUE THREAD

**Issue by fnxpt** [trufflesecurity/trufflehog#1067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
Main Branch

PR #1064 broke the github action. ${{ inputs.version }} is not able to be parsed as mentioned on the PR

Download action repository 'trufflesecurity/trufflehog@main' (SHA:8dedd08d895220e35cc1f39550e23047c5200cf3)
Error: trufflesecurity/trufflehog/main/action.yml (Line: 29, Col: 10):
Error: trufflesecurity/trufflehog/main/action.yml (Line: 29, Col: 10): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.version
Error: Fail to load trufflesecurity/trufflehog/main/action.yml

**Comment by ahrav** [comment]
I believe this change was reverted here: https://github.com/trufflesecurity/trufflehog/pull/1068
Going to close this, but feel free to re-open if this is still and issue.
