### ISSUE TITLE
Ability to scan a single file

### ISSUE THREAD

**Issue by JaneJeon** [trufflesecurity/trufflehog#1078]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would love for trufflehog to be able to scan a single file.

## Problem to be Addressed

Trufflehog currently "technically" supports being run in a pre-commit hook. However, instead of scanning staged files, it scans for _all files_ that have changed since the last commit, which is NOT the same.

## Description of the Preferred Solution

If Trufflehog supports a way to scan a single file, I can run a hook (using something like husky + lint-staged) to run the trufflehog scan on every staged file individually, thus freeing trufflehog from even having to know what "staged files" even are, while limiting the scans strictly to the staged files.

Alternatively, if the Trufflehog team would rather implement a `--staged` (just like gitleaks), where Trufflehog scans only the staged files, it would be an alternate way of achieving the same thing as well, though it would probably be much more work for the team.

**Comment by JaneJeon** [comment]
Before you close this issue, could you update the documentation about the _usage_ as well? The docs haven't been touched (the "file" scanning says it's still "coming soon") and there's no example or documentation about how to scan a single file.

Thank you.

**Comment by mcastorina** [comment]
Thanks for the reminder. I'll note here in case anyone finds the issue in the future:

File scanning was implemented on the `filesystem` sub-command using arguments to specify the file(s). You may also pass directories as arguments now too, which is preferred over `--directory`. At some point the `--directory` flag will be fully deprecated, but for now it still works.

Example:

```
trufflehog filesystem path/to/file1.txt path/to/file2.txt path/to/dir
```

**Comment by JaneJeon** [comment]
That's excellent, thank you very much!x
