### ISSUE TITLE
Version from downloaded binary just automatically bump up to latest

### ISSUE THREAD

**Issue by madchap** [trufflesecurity/trufflehog#1096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
3.6.x

### Trace Output
While wanting to workaround https://github.com/trufflesecurity/trufflehog/issues/1094, I downloaded the second to last binary directly, and then I got surprised.

![image](https://user-images.githubusercontent.com/5468769/218246320-dad2d94a-105a-49ce-9936-d1de07fe2f08.png)

### Expected Behavior

I am using the version/binary that I downloaded (not using a package manager, straight from github releases).

### Actual Behavior

It seems the version gets bumped automatically.

### Steps to Reproduce

See screenshot.

## Environment
 * OS: Linux amd64.

### References
* https://github.com/trufflesecurity/trufflehog/issues/1094

**Comment by JacobHayes** [comment]
It also looks like there's a `--no-update` flag if you want to keep pinned versions in CI, etc
