### ISSUE TITLE
Verified secrets - unreachable website

### ISSUE THREAD

**Issue by mateuszgrzelak** [trufflesecurity/trufflehog#1112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi guys, I'm wondering if there is a way to get additional exit code or information for responses that come from --only-verified flag that encountered status code 5xx.

## Problem to be Addressed
I noticed that sometimes verified scans for the same secrets may differ. For example for slack token we send request to some Slack endpoint to check if the secret is valid. But what when the Slack endpoit is unreachable and we have a token that is active and should be reported. Instead of getting "no secret found" because some endpoint responded 5xx and it is not our fault but this specific endpoint, it would be good to get  informatiom such us "Couldn't verfied this secret cause the website is unreachable" or seomething like that. 

## Description of the Preferred Solution
Add additional information or exit code for verfied scans that ecountered status code 5xx

### References

* #0000

**Comment by zricethezav** [comment]
Hi @mateuszgrzelak, we now set verification errors which will output more context as to why a verification attempt has failed: https://github.com/trufflesecurity/trufflehog/pull/2335.

Closing the issue. If this doesn't handle what you had in mind feel free to ping me and reopen it.
