### ISSUE TITLE
Missing .pre-commit-hooks.yaml in order to install trufflehog automatically with other pre-commit dependencies

### ISSUE THREAD

**Issue by shashial** [trufflesecurity/trufflehog#1124]
### Description
Hey, thanks for the great work, love your product!
So the problem is: if i would like a member of my team to use trufflehog as a pre-commit secrets scanner, i would need them to install trufflehog manually, but pre-commit actually can install a binary for you, so you would just do pre-commit update and everything works out of the box.
The only thing missing right now is a small yaml config for the pre-commit. Details could be found somewhere [here](https://pre-commit.com/#new-hooks).
This would really ease pre-commit usage!

### Solution
Solution is to place a yaml` .pre-commit-hooks.yaml`, something like this:

```
- id: trufflehog
  name: detects secrets
  description: detects secrets
  entry: trufflehog git file://. --since-commit HEAD --only-verified
  language: golang
  pass_filenames: false
```

### References
your colleagues have it
https://github.com/zricethezav/gitleaks/blob/master/.pre-commit-hooks.yaml
https://github.com/Yelp/detect-secrets/blob/master/.pre-commit-hooks.yaml

**Comment by ahrav** [comment]
Thanks @shashial that is a great suggestion.
