### ISSUE TITLE
Floating Version Tags for GitHub Actions

### ISSUE THREAD

**Issue by niall-byrne** [trufflesecurity/trufflehog#1128]
## Description

After reading https://github.com/trufflesecurity/trufflehog/issues/1040, I was a little confused as to what the versioning actually means for GitHub actions.

A common chore for people consuming GitHub workflow actions is to periodically update their CI to point to the latest version.

Other projects often use floating tags to make this less of a headache.

ie.  The consumer of your GitHub action would subscribe to a v3 for the newest stable 3.x.x release of the GitHub action.

I understand the version of Trufflehog to actually be floated inside the newest version of the action after reading https://github.com/trufflesecurity/trufflehog/issues/1040.

## Problem to be Addressed

This makes your work easier to consume, and CI updates are a painful time consuming chore.  It would be pretty sweet to be able to stay up to date.

## Description of the Preferred Solution

Instead of pinning to a particular patched version of the GitHub Action, we could instead subscribe to the latest v3, v4, whatever.

This would mean retagging each new released tag with a v3 tag that is understood to be "floating", and over time would point to each new patched release as it comes out.

## Additional Context

I am quite happy to take a peek to see how complicated this would be to automate, but I also wanted to get the project maintainer's thoughts.  

I'm also curious if people in general prefer to pin to specific patched versions, or float or a Minor or Major release version.

### References

Other projects using github actions frequently use this strategy:
- https://github.com/actions/setup-python
- https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by HKruthika** [comment]
Hey @niall-byrne , I would prefer to have version specified in the github actions. For instance, if I want to use 3.24 version then some parameter to define this in github action. 

This is to ensure we use n-1 or n-2 version, to observe stability. Also to ensure we have a provision to use one specific version across the organisation.

**Comment by niall-byrne** [comment]
@HKruthika Get that totally from a compliance perspective.  I'm would still be keen to see an extra v3 tag however, but this is mostly to address changes that happen to the actions API itself over the years.

**Comment by niall-byrne** [comment]
I'm going to close this, I think pinning to a sha is the safest way to handle this kind of thing.  Floating tags are convenient, but they come with a downside.
