### ISSUE TITLE
commitHash looks off by one

### ISSUE THREAD

**Issue by elliottb303** [trufflesecurity/trufflehog#113]
possibly related to this one https://github.com/dxa4481/truffleHog/issues/108

I am seeing that in the iter_commits section, the latest commit is skipped. Comments mention there is nothing to diff with. So for example commit xyz123 is latest and has secrets in files, but is just skipped via this code  

`            if not prev_commit:
                prev_commit = curr_commit
                continue
            else:
                diff = prev_commit.diff(curr_commit, create_patch=True)
`

On the next commit, my secrets from first commit are identified but with the next commit hash abc1234. looking at git log, this is the wrong hash for secrets. Am I missing something, or is that normal operation?

I can paste more info if needed, just a little confused on what is happening and wondering if this was known

**Comment by elliottb303** [comment]
I guess this makes sense if a diff is needed, so its creating a diff from second commit with latest? Then I would expect the first commit hash to be reported. Given that is the case, looking at the code i see difficulty storing and using that commit hash on second loop.

**Comment by dxa4481** [comment]
The latest commit should be captured by diffing it against the NULL_TREE https://github.com/dxa4481/truffleHog/blob/dev/truffleHog/truffleHog.py#L279

I believe I am logging the wrong commit hash... it diffs two, and logs one of the two, I think currently it's logging the less intuitive of the two. It was on my back log to investigate, I'll try to find time this weekend

**Comment by elliottb303** [comment]
thanks for the reply. Makes sense, I'll consider a PR if I find a solution!

**Comment by LewisLebentz** [comment]
@tmsteen think this may be the issue I'm experiencing too.

If I commit a fake key with commit hash: '#2' then run a scan stating to run since_commit='#1' it seems to completely miss the fact that I committed a key, until commit '#3'.

**Comment by LewisLebentz** [comment]
@dxa4481 @elliottb303 has this been fixed? Looks like the code has been updated (not by merging this PR though).

It still doesn't appear to work correctly for me. How can I make it so if I provide the second newest commit hash, it will ONLY scan changes in the newest commit?
