### ISSUE TITLE
Add OpenAI API Token detector

### ISSUE THREAD

**Issue by yilmi** [trufflesecurity/trufflehog#1140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add OpenAI API Token detectors

## Problem to be Addressed
Missing the detection and verifications for OpenAI Tokens

## Description of the Preferred Solution
Match the pattern in a precise way, verify the token, and pull extraData for the first organizaton fetched

**Comment by yilmi** [comment]
Preparing a PR

**Comment by dustin-decker** [comment]
Closed by merging #1142
