### ISSUE TITLE
Azure access key detection

### ISSUE THREAD

**Issue by naveenwebie** [trufflesecurity/trufflehog#1160]
#### Description ####

For pushing docker images using CICD into Azure container registry requires a service account(Access key). It may be wrote on the script explicitly. So we need to detect it.

#### Problem to be Addressed ####
Earlier I was using trufflehogv2 based on python, It detected the Access key as high entropy. But, After swithing to go based trufflehog, It is not detecting properly.

#### Solution ####
Adding the required detector would be great. It looks like this
Access key:
NEzS653B3k054e497CI3AIpQxajP1Jtzy4NodFtKNF+ACRCDFTDf

The above key is already rotated,

**Comment by zricethezav** [comment]
Azure detectors have been added. See https://github.com/trufflesecurity/trufflehog/tree/main/pkg/detectors
