### ISSUE TITLE
Need versioning for brew download

### ISSUE THREAD

**Issue by HKruthika** [trufflesecurity/trufflehog#1183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, we can download Trufflehog using brew, however, we cannot choose a specific version as brew mode of download does not support versioning. We should have versioning allowed which can follow @version parameter with brew download.

**Comment by zricethezav** [comment]
https://formulae.brew.sh/formula/trufflehog should be supported now
