### ISSUE TITLE
Pipeline build fail due to missing $GITHUB_OUTPUT variable

### ISSUE THREAD

**Issue by Fresh-SeanPatterson** [trufflesecurity/trufflehog#1216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
Latest Version: 3.31.0

### Expected Behavior
Pipeline executes with no errors, and I receive standard report.

### Actual Behavior
My pipeline fails with the message:

`/etc/entrypoint.sh: line 7: $GITHUB_OUTPUT: ambiguous redirect`

### Steps to Reproduce
Command line run in pipeline

`docker run --rm --platform linux/amd64 -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem --directory=/pwd --fail --only-verified`

## Additional Context
I am using Bitbucket pipelines to run my Trufflehog scans. To date, the pipelines have been running find, and I even have a successful pipeline run that occurred roughly 30 minutes before 3.31.0 was pushed and tagged as latest.

I suspect that since I'm not using Github actions, not having the environment variable listed in the actual behavior section is causing the problem. I suspect I could put this into my environment variables in Bitbucket, but this wouldn't help others using platforms such as Bitbucket, Azure DevOps, and others

### References
I think this was introduced through this issue:

https://github.com/trufflesecurity/trufflehog/issues/1026

* #0000

**Comment by dustin-decker** [comment]
My apologies, this should be fixed in v3.31.2 which was just tagged.

**Comment by Fresh-SeanPatterson** [comment]
Thank you! I'll work with that tagged version.

**Comment by Fresh-SeanPatterson** [comment]
If it helps for tracking purposes. This issue is resolved when I specifically tag 3.31.2 in my pipeline. Here is my updated command (which also avoids the deprecated directory parameter

`docker run --rm --platform linux/amd64 -v "$PWD:/pwd" trufflesecurity/trufflehog:3.31.2 filesystem /pwd --fail --only-verified`
