### ISSUE TITLE
S3 Scan Not Working Properly

### ISSUE THREAD

**Issue by SecTheBit** [trufflesecurity/trufflehog#1222]
While scanning AWS bucket with the credentials of a AWS account, through which the bucket is created, API keys were detected. But on scanning the bucket with some different AWS Account credentials, trufflehog is not providing any result or any error. (refer picture below). The particular AWS bucket is PUBLIC and have sufficient policy , so that any user can ListBucket and also can GetObject.
Also, while using the AWS CLI I was successfully list the buckets using different AWS account credentials.It's better if we can get facility of `--no-sign-request` in trufflehog as in AWS CLI.

![Screenshot from 2023-03-29 17-43-51](https://user-images.githubusercontent.com/46895441/228535129-e1dd1458-96cd-4915-bd46-1a6cb3e7b80e.png)

**Comment by nyanshak** [comment]
@SecTheBit - can you provide more info to help reproduce this?

1. Could you share a cloudformation template for making the bucket?
2. Is the problem with permissions that specific users can't see it but unauthenticated (e.g., `--no-sign-request`) requests work?
3. Can you share full commands (redacted creds) to reproduce this? The screenshots are a bit cut off, but the two commands look identical, so it's not clear what has changed between the two runs.

I'm also wondering if the following two things would be sufficient to close this out:
* Ensure there is an error/failure if we can't list the bucket
* Add some sort of `--unauthenticated` or `--no-sign-request` flag to allow you to try it unauthenticated

**Comment by SecTheBit** [comment]
@nyanshak , Yes you are right!
Specific users can not able to provide the output while using the truffle hog (2nd Output), also I have verified by ``` aws-cli``` , it is able to list down the buckets. So, might be some problem with the truffle hog.

It would be feasible if we get feature something like ```--unauthenticated``` so that it wouldn't be necessary to use aws accounts for open/public buckets.

**Comment by zricethezav** [comment]
@nyanshak we've significantly overhauled our s3 scanning and I believe this issue has been resolved. Please reopen if you are still experiencing this issue.
