### ISSUE TITLE
AWS Detector is missing validation for some key types

### ISSUE THREAD

**Issue by nyanshak** [trufflesecurity/trufflehog#1224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
`trufflehog dev` (at commit 2cf6f831d4b37bcd3c70f51f2823069f1d72894b)

### Expected Behavior

When trufflehog finds temporary secrets (e.g., `ASIA...`), it should make a request to AWS to validate the secret.

### Actual Behavior

Some types of AWS credentials are not 

### Steps to Reproduce

1. Set up AWS account with two IAM principals: `user` and `role`. `user` should be able to assume `role`.
3. Using `user` account, run `aws sts assume-role --role-arn role --role-session-name trufflehog-debug | tee -a leaked_secrets.txt`
4. `mkdir debug && mv leaked_secrets.txt debug/`
5. `trufflehog filesystem --directory=./debug --only-verified`

As there is an AWS detector that has verification, we expect to see the temporary session token output. But we actually see no results because this isn't properly verified.

Note that if you run *without the `--only-verified` flag*, you can see these are found but not verified:

```
Found unverified result 🐷🔑❓
Detector Type: AWS
Decoder Type: PLAIN
Raw result: ASIA...redacted...
File: debug/leaked_secrets.txt

Found unverified result 🐷🔑❓
Detector Type: AWS
Decoder Type: BASE64
Raw result: ASIA...redacted...
File: debug/leaked_secrets.txt
```

## Additional Context

```go
idPat     = regexp.MustCompile(`\b((?:AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16})\b`)
```

A quick read through the detector and docs seems to indicate that these detectors all support verification, but it's misleading that it only partially supports these types of secrets.

I have not tested against [https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_bearer.html](bearer tokens) (ABIA) or context-specific credentials (ACCA).

**Comment by dustin-decker** [comment]
Thanks for raising this. It looks like we'll need to detect the session token as well to properly validate the ASIA prefixed temporary tokens.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

**Comment by nyanshak** [comment]
I haven't yet found a defined format for this key.

As best as I can tell, it's a base64-encoded blob that is more or less opaque to anyone outside of AWS.

For size, I've seen anywhere from 389 to almost 800 characters.

So something like `[a-zA-Z0-9+\/=]{300,800}` (essentially, base64-encoded string between 300 and 800 characters), might work. But I'm not really sure what the lower / upper bounds are for the session token format, and this seems like a potentially expensive regex. Happy to submit a PR for this if you think that regex would work.

**Comment by nyanshak** [comment]
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html

> The size of the session token that AWS STS API operations return is not fixed. We strongly recommend that you make no assumptions about the maximum size. The typical token size is less than 4096 bytes, but that can vary.

So we could do from 300-4096 characters, which presumably would find _most_ session tokens. What do you think about that?

**Comment by Kruthika0** [comment]
Hi, do we have an update on this?

**Comment by dylanTruffle** [comment]
I just pulled short lived keys into their own detector, because they call STS differently too, it's not just a regex change
