### ISSUE TITLE
Customizable object Size for S3 Bucket Scanning

### ISSUE THREAD

**Issue by DivyanshuDiwakar** [trufflesecurity/trufflehog#1237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Problem to be Addressed

Right now the maximum object size for a S3 bucket which we can scan is 250 MB. Now suppose, what if someone wants to scan objects having size lesser than 50 MB (not greater than that), so it would be better if we would be able to customize that size using flags like ``` --max-object-size```.

**Comment by nyanshak** [comment]
@dustin-decker I think this issue can be closed since the PR has been merged.
