### ISSUE TITLE
Bug: Detectors supporting custom verifiers not working as expected (fix proposed)

### ISSUE THREAD

**Issue by issue-submission** [trufflesecurity/trufflehog#1238]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
3.31.3

### Expected Behavior
When no custom verifiers are used (`-verifier` option), the detectors should use the default endpoint to verify if a secret is valid or not.

### Actual Behavior
Secrets are not verified anymore in version 3.31.3 when no custom endpoints are provided. This issue is linked to [pull request 1070](https://github.com/trufflesecurity/trufflehog/pull/1070).

### Steps to Reproduce
- Create a valid GitHub token
- Store the token in a file
- Run TruffleHog (3.31.3)

The secret is detected but is not marked as verified.

### Fix Proposed
**Approach 1**
For the GitHub detector, in the [_FromData_ function (/pkg/detectors/github/github.go)](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/github/github.go#L80), add the following logic before iterating over the matches:
```
if len(s.verifierURLs) == 0 {
	s.verifierURLs = append(s.verifierURLs, defaultURL)
}

```
Same should be done for other detectors supporting custom endpoints. This approach may be less optimal than approaches 2 and 3.

**Approach 2**
It is also possible to handle the case directly in [_CustomDetectors_ function (pkg/engine/defaults.go)](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/engine/defaults.go#L747). In this approach, the first condition should be ignored:
```
if len(urls) == 0 {
	return defaultDetectors
}
```
However, this approach may be less optimal than approach 3.

**Approach 3**
Last approach would consist in calling the [_New_ function (/pkg/detectors/github/github.go)](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/github/github.go#L23) when building the default detectors ([_DefaultDetectors_ function (/pkg/engine/defaults.go)](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/engine/defaults.go#L804)) for all detectors supporting custom endpoints and change the function to add the default endpoint to the _verifierURLs_ array by default.

**Comment by ahrav** [comment]
Thank you for finding this and also providing multiple solutions. Really appreciate it. :)
