### ISSUE TITLE
Should Exit 0 When AWS Credentials Are Invalid

### ISSUE THREAD

**Issue by iamjpotts** [trufflesecurity/trufflehog#1252]
Currently, if the scanner is run against a protected S3 bucket, and given any combination of invalid AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, or AWS_SESSION_TOKEN, the AWS error will be correctly reported in the log output, but Truffle Hog will exit with a zero status code.

It should exit with a non-zero status code to indicate failure.

For example, if it was configured to scan a bucket, and that bucket had reportable secrets, but the secret access key was invalid or expired, some systems would interpret the zero access code to mean the bucket does not have any reportable secrets, when in fact it does.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

```
ghcr.io/trufflesecurity/trufflehog:3.31.4
```
and prior, such as
```
ghcr.io/trufflesecurity/trufflehog:3.30.0
```

### Trace Output

This output is from the default log level, and the last line is from the example shell script.

```
2023-04-11T12:55:57Z    info-2  trufflehog      trufflehog 3.31.4
2023-04-11T12:55:57Z    info-2  trufflehog      engine started  {"workers": 16}
2023-04-11T12:55:57Z    info-2  trufflehog      loaded decoders {"count": 2}
2023-04-11T12:55:57Z    info-2  trufflehog      loaded detectors        {"total": 1472, "verification_enabled": 1472, "verification_disabled": 0}
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2023-04-11T12:55:57Z    info-0  trufflehog      Scanning bucket {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "foo"}
2023-04-11T12:55:57Z    error   trufflehog      could not list objects in s3 bucket     {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "foo", "error": "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: xxx, host id: xxx"}
2023-04-11T12:55:57Z    info-0  trufflehog      Scanning bucket {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "bar"}
2023-04-11T12:55:58Z    error   trufflehog      could not list objects in s3 bucket     {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "bar", "error": "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: xxx, host id: xxx"}
2023-04-11T12:55:59Z    info-2  trufflehog      finished scanning       {"chunks": 0, "bytes": 0}
Exit code was 0
```

### Expected Behavior

Process should exit with a non-zero exit code.

### Actual Behavior

Exits with a zero exit code.

### Steps to Reproduce

Example with _3.30.0_

```shell
#!/bin/bash

set -e

aws_access_key_id=foo
aws_secret_access_key=bar

docker run \
    --rm \
    -e AWS_ACCESS_KEY_ID=$aws_access_key_id \
    -e AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
    -u 10000:10000 \
    ghcr.io/trufflesecurity/trufflehog:3.30.0 \
    s3 --bucket=foo --bucket=bar --no-update --trace

echo "Exit code was $?"
```

Example with _3.31.4_

```shell
#!/bin/bash

set -e

aws_access_key_id=foo
aws_secret_access_key=bar

docker run \
    --rm \
    -e AWS_ACCESS_KEY_ID=$aws_access_key_id \
    -e AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
    -u 10000:10000 \
    ghcr.io/trufflesecurity/trufflehog:3.31.4 \
    s3 --bucket=foo --bucket=bar --no-update --trace

echo "Exit code was $?"
```

## Environment
 * OS: Ubuntu
 * Version 22.04
 * Docker 20.10.21

## Additional Context

n/a

### References

n/a

**Comment by nyanshak** [comment]
From a quick review of the engines, this appears to be a common problem with the engines.

Here's the pattern:

```go
func (e *Engine) Scan${ENGINE}(ctx context.Context, c source.${ENGINE}Config) error {
    ...
    e.sourcesWg.Add(1)
    go func() {
        defer common.RecoverWithExit(ctx)
        defer e.sourcesWg.Done()
        err := ${ENGINE}Source.Chunks(ctx, e.ChunksChan())
        if err != nil {
            ctx.Logger().Error(err, "error scanning ${ENGINE}")
        }
    }()
    return nil
}
```

In this scenario, the error gets logged, but it's not returned to the caller (e.g., `ScanFileSystem(...)`). So although returned errors result in fatal logs and a non-zero exit code, the errors will get logged but not returned.

There are several ways, for example:
1. pass error through channel, and then select channel / close before returning
2. use errgroup:

```
import (
    ...
    "golang.org/x/sync/errgroup"
)

func (e *Engine) Scan${ENGINE}(ctx context.Context, c source.${ENGINE}Config) error {
    ...
    e.sourcesWg.Add(1)

    var g errgroup.Group

    g.Go(func() error {
        defer common.RecoverWithExit(ctx)
        err := ${ENGINE}Source.Chunks(ctx, e.ChunksChan())
        if err != nil {
             return fmt.Errorf("error scanning ${ENGINE}: %w", err)
        }
        return nil
    })

    return g.Wait()
}
```

2a. errgroup variation:

I think there are several variations on this that could work, depending on how the trufflehog maintainers prefer this to work. Another example would be switching `sourcesWg` and `workersWg`  to be `errgroup.Group`.

 `pkg/engine/engine.go`:

```go
func (e *Engine) Finish(ctx.Context, logFunc (error, string, ...any)) {
    ...
    sourceErr := e.sourcesWg.Wait()
    if sourceErr != nil {
        logFunc(sourceErr)
    }
    ...

    workerErr := e.workersWg.Wait()
    if workerErr != nil {
        logFunc(workerErr)
    }
    ...    
}

`main.go`:

```go
    go e.Finish(ctx, logFatalFunc)
```

In each engine:

```go
    e.sourcesWg.Go(func() error {
        defer common.RecoverWithExit(ctx)
        err := ${ENGINE}Source.Chunks(ctx, e.ChunksChan())
        if err != nil {
             return fmt.Errorf("error scanning ${ENGINE}: %w", err)
        }
        return nil
    })
    return nil
```

I'd be happy to work on a PR for this. Any preferences from maintainers on this?

**Comment by dustin-decker** [comment]
The Scan${ENGINE} functions need to be non-blocking for the rest of the pipeline to continue, so 2a seems like a good way to go. 

A PR would be gladly accepted. Thank you, @nyanshak!
