### ISSUE TITLE
Feature Request: Filesystem scanning should support line numbers

### ISSUE THREAD

**Issue by mimaslanka** [trufflesecurity/trufflehog#1272]
### Description

Using git scanning it will show the line number on a given file. This feature should also be present in filesystem as well so the user has more context to find an issue quickly.

**Comment by nyanshak** [comment]
I would like to add support for line numbers in *all* sources, but I'm less familiar with this aspect of trufflehog, so I stuck to implementing just the filesystem source line numbers in my PR. :100:
