### ISSUE TITLE
New buildkite token format

### ISSUE THREAD

**Issue by CameronLonsdale** [trufflesecurity/trufflehog#1300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Buildkite has updated their token format to use a common prefix of `bkua_`. The rest of the token format is the same as described with 40 hex characters https://github.com/trufflesecurity/trufflehog/blob/58e8c1e4ac9e4663006d01ed62859bd927e53f5f/pkg/detectors/buildkite/buildkite.go#L24.

Likely with how npm tokens changed, we should create a new detector for this format & can re-use the same validation endpoint.

## Problem to be Addressed
New Buildkite tokens can be detected

## Description of the Preferred Solution

A new detector using the updated Buildkite token format.

**Comment by dustin-decker** [comment]
Thank you for the information! We will update this soon.
