### ISSUE TITLE
Json Output is not Json

### ISSUE THREAD

**Issue by bp4151** [trufflesecurity/trufflehog#1302]
### TruffleHog Version
3.33.0

### Expected Behavior
Json output should be an array of comma separated dictionary objects

### Actual Behavior
Json output is actually individually output lines of dictionary objects with no comma and no start or end square brackets to indicate the output is an array.

### Gist
https://gist.github.com/bp4151/354a3601e86266f6a2698dd5c43f4ba8

### Steps to Reproduce
docker run --rm -it -v "${PWD}:/pwd" trufflesecurity/trufflehog:latest github --org=[Github Org] --token=$env:GITHUB_TOKEN --json > trufflehog.json

## Environment
 * OS: Windows 10 running Docker

### References
The following issue from March 2019 mentions the issue and the issue was closed
https://github.com/trufflesecurity/trufflehog/issues/705

* #0000

**Comment by dustin-decker** [comment]
The output is NDJSON, or new line delimited JSON. Each line is parsable JSON. This is the only way to output JSON in a stream, otherwise you would have to wait for the completion of the program to parse it.
