### ISSUE TITLE
Can't scan the whole org. Only works for a single project.

### ISSUE THREAD

**Issue by shoaibali123** [trufflesecurity/trufflehog#131]
Hi:

I tried to use the scripts for scanning the whole org instead of a single project repo, but it didn't work. Any help on this will be appreciated.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

You can scan entire gitlab and github orgs now!

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
