### ISSUE TITLE
Unify timestamps

### ISSUE THREAD

**Issue by XSchelin** [trufflesecurity/trufflehog#1312]
### Description

Currently, results return with the timezone offset of the user who made the commit, like so:

```
Timestamp: 2022-04-05 14:45:07 +0530
...
Timestamp: 2020-06-25 09:48:11 -0700
```

It'd be nice to have an adjusted timestamp field that goes along with this that puts all of them in UTC:

```
Timestamp:     2022-04-05 14:45:07 +0530
UTC Timestamp: 2022-04-05 09:15:07
...
Timestamp:     2020-06-25 09:48:11 -0700
UTC Timestamp: 2020-06-25 16:48:11
```

**Comment by nyanshak** [comment]
I took a stab at fixing this by uniformly returning UTC timestamps.

Another approach might be to have some sort of flag to specify timezone (`--timezone`):

* original: Use original commit author timestamp
* local: Use timezone of the computer running trufflehog
* UTC: Use UTC time in output

I went for the minimal approach, but could update if it makes sense :woman_shrugging:
