### ISSUE TITLE
Brew - Possible duplicate detectors ('Square')

### ISSUE THREAD

**Issue by SumoSumir** [trufflesecurity/trufflehog#1313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

trufflehog 3.33.0

### Trace Output
https://gist.github.com/SumoSumir/d8559f5b0ca8b0858354909a1ebcf7f7

### Expected Behavior
There shouldn't have been a duplicate detector error message. 

### Actual Behavior
No duplicate detector error message appears

### Steps to Reproduce

 1. Install latest version of trufflehog using homebrew
 2. Run 'trufflehog --version' to confirm that you're on the latest i.e 3.33.0
 3. Run 'trufflehog filesystem . ' to view the error
 
## Environment
 * OS: Ventura
 * Version 13.3

## Additional Context

This issue was fixed in pull request #1266. Which was merged into 3.32.0 on April 20th. I installed trufflehog version 3.33.0 via homebrew on 1st of May. Possible cause of this issue is:
1. homebrew image isn't updated (unlikely as assured by https://github.com/trufflesecurity/trufflehog/pull/1266#issuecomment-1529822712)
2. Or there has been a code regression (based on my cursory investigation - not the case)
3. Or the fix implement has not been able to patch the issue

Will try to investigate and solve the issue myself if possible

### References

* #1266

**Comment by dustin-decker** [comment]
Confirmed. It is because there are multiple square-related detectors that are using the same enum from the proto.

**Comment by SumoSumir** [comment]
Would be fixed by #1322 
Please update the brew image with the same.

**Comment by ahrav** [comment]
Closing this as the fix should be deployed in version v3.34.0 (https://github.com/trufflesecurity/trufflehog/releases/tag/v3.34.0)
