### ISSUE TITLE
Github Action swallows file paths in warnings

### ISSUE THREAD

**Issue by 64kramsystem** [trufflesecurity/trufflehog#1326]
The GitHub Action, at least in some cases, is swallowing the file paths in the warnings.

This is confusing and time consuming, since the origin of the warnings is not reported, and one has to manually inspect the series of commits, which may be time consuming for large PRs.

This is an edited example of the CLI output:

```
::warning file=path/to/file,line=1,endLine=1::Found unverified PrivateKey result 🐷🔑
```

This is what the Action prints:

```
Warning: Found unverified PrivateKey result 🐷🔑
```

Both invocations use the same parameters.

**Comment by avx-rvandegrift** [comment]
I'm hitting this issue with v3.50.0 on false positives from the SQLServer scanner.

**Comment by zricethezav** [comment]
<img width="388" alt="Screenshot 2024-02-16 at 12 57 57 PM" src="https://github.com/trufflesecurity/trufflehog/assets/15034943/ee0dc2e7-4487-43b4-b66d-927b93a1d3de">

The line number is part of the output title. It's also a clickable link which will take you to the correct line and commit
