### ISSUE TITLE
old-style classes error

### ISSUE THREAD

**Issue by jaikishantulswani** [trufflesecurity/trufflehog#133]
**Getting this issue while running like** 
trufflehog --rules=regexes.json --entropy=True https://github.com/example/example.git

`
Traceback (most recent call last):
  File "/usr/local/bin/trufflehog", line 11, in <module>
    load_entry_point('truffleHog==2.0.92', 'console_scripts', 'trufflehog')()
  File "build/bdist.linux-i686/egg/truffleHog/truffleHog.py", line 47, in main
TypeError: exceptions must be old-style classes or derived from BaseException, not str
root@Kali:~/truffleHog# trufflehog  --entropy=True https://github.com/example/example.git
`

**work fine when running it without** `--rules=regexes.json`

**Comment by iammarco** [comment]
I got the same error. I added the following regex to the list: (\s|'|\")((?=.*[0-9])(?=.*[a-z]))([a-z0-9]{8})(\s|'|\")
It is supposed to find strings of length 8 having at least one digit and one small character. all needs to be enclosed by space, ' or ".
Anybody got an idea on how to overcome?

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
