### ISSUE TITLE
Print which detector is used when a secret is found with custom detectors

### ISSUE THREAD

**Issue by Nouman404** [trufflesecurity/trufflehog#1330]
### Description

I think that it would be great if it was possible to see the name of the custom detector used when we create our own regex. For now, we only have "Custom Regex" printed out and it would be better to have the name of the custom regex used.

![image](https://user-images.githubusercontent.com/73934639/236404324-76e4905c-0c4b-4c6a-9c08-2e0b0d3016cf.png)

**Comment by zricethezav** [comment]
@Nouman404 Thanks for opening this issue. I'll take a crack at it.

**Comment by zricethezav** [comment]
Just opened https://github.com/trufflesecurity/trufflehog/compare/main...custom-detector-name where you can track progress. Right now it's just a hacky solution to get the `name` in the output. For example:
```
Found unverified result 🐷🔑❓
Detector Type: CustomRegex
Decoder Type: PLAIN
Raw result: hogs are cool
Name: hog detector
Commit: 6a761551b86e55fd84163f378c12190ce91ea210
Email: Zachary Rice <email>
File: test1.md
Line: 2
Timestamp: 2023-06-09 15:13:12 +0000
```

using this custom config:
```
# config.yaml
detectors:
- name: hog detector
  keywords:
  - hog
  regex:
    adjective: hogs are (\S+)
```

**Comment by zricethezav** [comment]
related issue: https://github.com/trufflesecurity/trufflehog/issues/1063#issue-1567803192
