### ISSUE TITLE
Active secrets found in Trufflehog repository

### ISSUE THREAD

**Issue by Kruthika0** [trufflesecurity/trufflehog#1360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

There are 52 active secrets existing as part of Trufflehog source code. This could be potentially dangerous for all the consumers using Trufflehog. Could someone look into it and get these secrets invalidated?

**Comment by dustin-decker** [comment]
These are test credentials that are intentionally included and are not revocable. Rest assured, we do monitor this repository for credential leaks.
