### ISSUE TITLE
Git version validate broken

### ISSUE THREAD

**Issue by Gabryel8818** [trufflesecurity/trufflehog#1374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

latest: 3.8

### Trace Output
https://gist.github.com/Gabryel8818/20e30b1a54f638ed1445157ab0ae6942

### Expected Behavior
![image](https://github.com/trufflesecurity/trufflehog/assets/50804183/6b0e1b33-2a49-4a58-8743-67faf29e5f4f)

### Actual Behavior

![image](https://github.com/trufflesecurity/trufflehog/assets/50804183/88625bcf-584c-42c7-af1e-91f9592a51d0)

### Steps to Reproduce

 1. Run: docker run --rm -it -v "$PWD:/pwd" docker.io/trufflesecurity/trufflehog:latest github --org=trufflesecurity 

## Environment
 * OS: [ Linux ]
 * Version [ ubuntu-22.04 ]

## Additional Context
I believe the problem is here:  https://github.com/trufflesecurity/trufflehog/commit/183037ab34ab0a81e6d041febfa2aec2f590628d

**Comment by dustin-decker** [comment]
Hey @Gabryel8818 I will do more research on the minimum version that we can support

**Comment by dustin-decker** [comment]
This will be fixed in v3.39.0 which is building now. It will support git versions down to v2.20.0 (released 5 years ago)

**Comment by Gabryel8818** [comment]
thansk @dustin-decker its ok now
