### ISSUE TITLE
Feature Request: Support Matthew Barnett's regex module

### ISSUE THREAD

**Issue by clay584** [trufflesecurity/trufflehog#139]
It would be best if this would support PCRE (or the closest thing in python) which is [Matthew Barnett's regex library](https://pypi.org/project/regex/). It is backward's compatible with python re.

You cannot perform advanced regex matches with truffleHog because of this. Here is an example that would work with this better regex module...

`\$\d+\$\S+\$\S+$`

should match...

`$1$MfuJ$VyYAg2gxOfJpAflbbea5M.`

**Comment by lufte** [comment]
Your example seems to work with the built-in `re` module.

```
lufte@lufte-thinkpad:~$ cat /tmp/test_regex.py 
import re
s = '$1$MfuJ$VyYAg2gxOfJpAflbbea5M.'
p = '\$\d+\$\S+\$\S+$'
print(re.match(p, s))

lufte@lufte-thinkpad:~$ python2 /tmp/test_regex.py 
<_sre.SRE_Match object at 0x7f701d9e95e0>
lufte@lufte-thinkpad:~$ python3 /tmp/test_regex.py 
<re.Match object; span=(0, 29), match='$1$MfuJ$VyYAg2gxOfJpAflbbea5M'>
lufte@lufte-thinkpad:~$ 
```

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
