### ISSUE TITLE
Trufflehog creates an invalid json report

### ISSUE THREAD

**Issue by MukulG27** [trufflesecurity/trufflehog#1398]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

trufflehog 3.40.0

### Trace Output

https://gist.github.com/MukulG27/9037a113fc6ea068676c24f6a5c6ce55

### Expected Behavior

It should have provided a valid json output

### Actual Behavior

The json output is invalid

### Steps to Reproduce

 1. Install and set up docker
 2. Run command `docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest git https://github.com/vsco/keys.git --json > rep.json`
 3. Open the file rep.json
 4. The file contents are not valid json

## Environment
 * OS: Ubuntu
 * Version 22.0.4

## Additional Context

The repository I used in the command is a random public repository to test the output of the scanner

Also, if I try to install the trufflehog using go install. The install is unsuccessful

### References

* #0000

**Comment by dustin-decker** [comment]
That is new line delimited JSON. Each line is a JSON blob. It is the only way to output parsable JSON in a stream, otherwise there would be no output until the end of the scan.
