### ISSUE TITLE
Traceback Error - No such file or directory in /tmp/

### ISSUE THREAD

**Issue by matchstickboy** [trufflesecurity/trufflehog#141]
Hello,

Odd error encountered on a fresh Kali install.  Git, Python3, and Pip are all installed, and a pip install of trufflehog conmpleted without errors.  But the test provided on the trufflehog Readme return the following output:

root@kali:~/truffleHog/truffleHog# python3 truffleHog.py --regex --entropy=False https://github.com/dxa4481/truffleHog.git
~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 475, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6lmiivfm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "truffleHog.py", line 311, in <module>
    main()
  File "truffleHog.py", line 59, in main
    shutil.rmtree(project_path, onerror=del_rw)
  File "/usr/lib/python3.6/shutil.py", line 477, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "truffleHog.py", line 82, in del_rw
    os.chmod(name, stat.S_IWRITE)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6lmiivfm'

Wondering if this is just a permissions issue to tmp directory or something more.  The specific folder in temp is different every time (as I would expect).  Running as SUDO return the same output.

Any suggestions would be appreciated.  Let me know if additional information is requested.

Thank you in advance,

Chris

**Comment by travis-infosec** [comment]
I had this problem too.  Looking into the problem it seems that it's just attempting to remove the directory a second time.  If during the first rmtree, there's an exception of any kind, it attempts to remove the mktemp() dir extra hard.  If that first rmtree actually worked then the directory won't exist and you get this error.  If you see no other output I think it didn't find any secrets.

**Comment by pkq2019** [comment]
Have you already resolved this question?
How to achieve that

**Comment by travis-infosec** [comment]
It's an error from the second attempt to remove the directory which is triggered if the first attempt returns some kind of error/exception.  Often the directory is already gone by the second attempt, especially in my experience on latest Mac OS X, so is safe to ignore.

**Comment by willem-tee** [comment]
I do also have this issue on a similar specs to the OP and unsolved. Any updates?

**Comment by travis-infosec** [comment]
Is the directory actually still there?  Or is it just a spurious error message.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
