### ISSUE TITLE
How to use github + `--exclude-paths`?

### ISSUE THREAD

**Issue by jacek-jablonski** [trufflesecurity/trufflehog#1414]
Hi,

I'm trying to use `--exclude-paths` parameter for `github` subcommand, unfortunately without success.

I'm trying:
```
docker run --platform linux/arm64 -it -v "$PWD:/pwd" ghcr.io/trufflesecurity/trufflehog:latest github --org myorg --fail  --exclude-paths=yarn.lock --token mytoken
```

What I'm trying to do is omit lock files from the scan.
Thanks :)

**Comment by zricethezav** [comment]
Hi @jacek-jablonski,

If you want to exclude `yarn.lock` you'll need to provide a file that contains `yarn.lock`.  Just a lil bit of indirection ;) 

So something like:
**ignorefiles.txt**
```
yarn.lock
go.mod
etc...
```

From the --help output:
```
  -x, --exclude-paths=EXCLUDE-PATHS  Path to file with newline separated regexes for files to exclude in scan.
```

**Comment by jacek-jablonski** [comment]
Thank you @zricethezav

**Comment by karanb192** [comment]
@jacek-jablonski, how would this work when running it in docker using below command?

`docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --repo https://github.com/trufflesecurity/test_keys`

**Comment by jacek-jablonski** [comment]
@karanb192 no change for me.
