### ISSUE TITLE
Git requirement

### ISSUE THREAD

**Issue by LewisLebentz** [trufflesecurity/trufflehog#142]
Is there a way to run truffleHog without having git installed?

I am trying to get this working in AWS Lambda but it's failing due to git not being on the OS that Lambda runs in. I've tried using lambda-git, but that doesn't work either.

Is there a way to get it working without relying on an OS version of git so I can run it serverlessly?

`
10:35:02
File "/var/task/truffleHog/truffleHog.py", line 247, in find_strings

10:35:02
project_path = clone_git_repo(git_url)

10:35:02
File "/var/task/truffleHog/truffleHog.py", line 122, in clone_git_repo

10:35:02
Repo.clone_from(git_url, project_path)

10:35:02
File "/var/task/git/repo/base.py", line 925, in clone_from

10:35:02
return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)

10:35:02
File "/var/task/git/repo/base.py", line 874, in _clone

10:35:02
v=True, **add_progress(kwargs, git, progress))

10:35:02
File "/var/task/git/cmd.py", line 424, in <lambda>

10:35:02
return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)

10:35:02
File "/var/task/git/cmd.py", line 873, in _call_process

10:35:02
return self.execute(call, **_kwargs)

10:35:02
File "/var/task/git/cmd.py", line 601, in execute

10:35:02
raise GitCommandNotFound(command, err)

10:35:02
git.exc.GitCommandNotFound: Cmd('git') not found due to: FileNotFoundError('[Errno 2] No such file or directory: 'git': 'git'')`

**Comment by kaido89** [comment]
For Lambda you could use a layer such as the installation of git and adding it to the lambda function's configuration.

**Comment by trash-anger** [comment]
Hi @LewisLebentz ,

I'm currently starting a project to do the same !
What have you done in the end ?

**Comment by mohitk09** [comment]
Is there any conclusion of the same I am still facing trouble in configuring it

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
