### ISSUE TITLE
Latest v3.41.0 release is missing pre-compiled assets 

### ISSUE THREAD

**Issue by nicoSWD** [trufflesecurity/trufflehog#1421]
All releases execpt the latest one include pre-compiled binary assets. Not sure if this is intentional, but I couldn't find any references to this in the changelog or anywhere else.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
v3.41.0

### Trace Output

None

### Expected Behavior

I expected the latest realease to include compiled assets, like all the other ones do.

### Actual Behavior

404 not found

### Steps to Reproduce

 1. Go to 'https://github.com/trufflesecurity/trufflehog/releases/tag/v3.41.0'
 2. Scroll down to 'Assets'
 3. Nothing there

**Comment by dustin-decker** [comment]
Thanks for surfacing this. It looks like the github action never ran. I'm not sure how to trigger it for an old tag so I've tagged v3.41.1.

**Comment by zricethezav** [comment]
closing this as [v3.41.1](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.41.1) has been cut and assets attached
