### ISSUE TITLE
Updates fail with "too many redirects"

### ISSUE THREAD

**Issue by dinvlad** [trufflesecurity/trufflehog#1437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

`3.40.0`

### Trace Output

https://gist.github.com/dinvlad/b460083b8a0ce1c51d83ec39727ba253

### Expected Behavior
Auto-updates should succeed

### Actual Behavior
Updates fail

### Steps to Reproduce

 1. `cd $(mktemp -d)`
 2. `trufflehog filesystem . --debug --trace`
 3. Observe the following message in the log:
 ```
[updater parent] failed to get latest version: Post "https://oss.trufflehog.org/updates": stopped after 10 redirects
```

## Environment
 * OS: macOS Ventura
 * Version 13.3

## Additional Context

The same happens with `curl -L https://oss.trufflehog.org/updates`, which reports `curl: (47) Maximum (50) redirects followed`, and in the verbose output it just redirects back to the same URL, resulting in this error.

**Comment by dustin-decker** [comment]
Thanks for reporting, we're taking a look.

**Comment by dustin-decker** [comment]
This is resolved now.
