### ISSUE TITLE
Twilio scanner verification uses API call with side effects

### ISSUE THREAD

**Issue by brandonjyan** [trufflesecurity/trufflehog#1493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
v3.44.0

### Expected Behavior

Running Trufflehog scanner should not cause any side effects to Twilio user account.

### Actual Behavior

New Twilio service is created when using scanner on valid Twilio credentials.

### Steps to Reproduce

Run Trufflehog scanner on code with valid Twilio credentials. After the scan, there will be a new service created called "MyServiceName".

**Comment by ahrav** [comment]
Thanks @brandonjyan I agree with you. Thanks for taking the time to put in the fix. Really appreciate it 😄
