### ISSUE TITLE
docker --image : scan by digest

### ISSUE THREAD

**Issue by chr-b** [trufflesecurity/trufflehog#1505]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The container image scan functionality currently only works by specifying an image by tag. E.g.:
`trufflehog docker --image trufflesecurity/secrets:latest --only-verified`

Please also support scanning an image specified by digest. E.g.:
`trufflehog docker --image trufflesecurity/secrets@sha256:864f6d41209462d8e37fc302ba1532656e265f7c361f11e29fed6ca1f4208e11
 --only-verified`

## Problem to be Addressed
Scanning an image referenced by digest is currently not possible.
Error message:
```
2023-07-17T14:07:23Z	error	trufflehog	error occurred while collecting chunks	{"error": "error scanning docker image: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: trufflesecurity/secrets@sha256"}
```

Scanning by digest instead of tag would be an improvement because it is more precise.  Tags are mutable, whereas digests are not.

## Description of the Preferred Solution
Support specifying an image by digest.

## Additional Context
trufflehog 3.43.0

### References
none

**Comment by zricethezav** [comment]
Thanks for raising this issue @chr-b, we're not actively working on this feature but will happily review a community PR if anyone is up for it
