### ISSUE TITLE
Support scanning GitHub Orgs with GitHub App Token

### ISSUE THREAD

**Issue by TaxBusby** [trufflesecurity/trufflehog#1513]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[GitHub Apps](https://docs.github.com/en/apps/overview) are the recommended way to interact with GitHub's API from code. Using Github app tokens confers [higher rate limits](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/rate-limits-for-github-apps#installation-access-tokens-on-githubcom) than user tokens.

## Problem to be Addressed
Currently, if a GitHub app token is passed to trufflehog, such as with
```bash
trufflehog github --org my-org --token $GITHUB_APP_TOKEN
```
It errors out quickly with 

```
{"level":"info-0","ts":"2023-07-19T15:07:01Z","logger":"trufflehog","msg":"loaded decoders","count":3}
{"level":"info-0","ts":"2023-07-19T15:07:01Z","logger":"trufflehog","msg":"loaded detectors","total":745,"verification_enabled":745,"verification_disabled":0}
{"level":"error","ts":"2023-07-19T15:07:01Z","logger":"trufflehog","msg":"error occurred while collecting chunks","error":"could not scan github: GET https://api.github.com/user: 403 Resource not accessible by integration []"}
```
It is accessing a REST endpoint that is not valid for github apps, the `/user` endpoint. 

## Description of the Preferred Solution
Support a github app token being passed as the `--token` arg for doing org-level secret scanning with `trufflehog github`

## Additional Context
[Listing repositories](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories) and [accessing their content](https://stackoverflow.com/questions/54873777/cloning-a-private-github-repo-authenticated-as-a-github-app) should both be possible with github app tokens.

### References

* #671
  - Another user hit this issue and reported it as a bug, but was happy to use a Personal Access Token as a workaround

**Comment by TaxBusby** [comment]
Looking at the source code, it appears that some code has been written to support Github app tokens, though I can't find any documentation on how to specify them

https://github.com/trufflesecurity/trufflehog/blob/main/pkg/sources/github/github.go#L368C13-L368C13

**Comment by zricethezav** [comment]
Hi @TaxBusby, we don't plan on supporting this in TruffleHog OSS. since authenticating via GitHub app only benefits organizations with more than 20 users. Consider using [TruffleHog Enterprise](https://trufflesecurity.com/trufflehog/) for higher rate limits on organizations
