### ISSUE TITLE
Presence of RSA keys in a file results in unexpected trufflehog behavior

### ISSUE THREAD

**Issue by anuraagbaishya** [trufflesecurity/trufflehog#1536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
trufflehog 3.44.0

### Expected Behavior

When testfile1.txt is scanned trufflehog should find 1 RSA key, 1 Npm token and 2 slack webhooks
When testfile2.txt is scanned trufflehog should find 2 RSA keys, 1 Npm token and 2 slack webhooks 

### Actual Behavior

When testfile1.txt is scanned trufflehog finds 1 RSA key, 1 Npm token and 2 slack webhooks, but it reports the slack webhooks twice. Once with decoder:plain and once with decoder:base64
When testfile2.txt is scanned trufflehog finds 1 RSA key, and 1 slack webhook (reported twice, once with decoder:plain and once with decoder:base64). It misses the other slack webhook and the npm token

### Steps to Reproduce

1. Scan testfile1.txt and observe results similar to https://gist.github.com/anuraagbaishya/4e39b16a71ed35de799633320e18b413#file-testfile1-trace-txt (trufflehog finds 1 RSA key, 1 Npm token and 2 slack webhooks, but it reports the slack webhooks twice. Once with decoder:plain and once with decoder:base64)
2. Scan testfile2.txt and observe results similar to https://gist.github.com/anuraagbaishya/4e39b16a71ed35de799633320e18b413#file-testfile2-trace-txt (trufflehog finds 1 RSA key, and 1 slack webhook (reported twice, once with decoder:plain and once with decoder:base64). It misses the other slack webhook and the npm token)

## Environment
 * OS: MacOS
 * Version 13.3

## Additional Context
Changing the location of the RSA keys in the file results in the output of the scan to change. 

### References

* #0000

**Comment by zricethezav** [comment]
Thanks for opening this issue. I took some time looking at this and figured out it has something to do with the chunker. If you look at https://github.com/trufflesecurity/trufflehog/blob/91cbca941af9c72f45d29220d5ae82dd9ee770dc/pkg/engine/engine.go#L273 `string(chunk.Data)` you can see that we aren't scanning the full file (testfile1.txt). Pretty odd bug 🤔. I can spend some more time looking at it this week but any help from the community/other teams members would be appreciated

**Comment by ahrav** [comment]
I think [v3.48.0](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.48.0) should resolve the issue here.

**Comment by ahrav** [comment]
@anuraagbaishya going to close this specific issue as I believe the filesystem scan should be picking up secrets in files that aren't archived. Feel free to re-open if for any reason you are still seeing secrets not get detected in regular files. I'll open a separate Issue for the missed secrets in archived files.
