### ISSUE TITLE
Trufflehog reports no secrets when input file is of certain sizes/line lengths

### ISSUE THREAD

**Issue by TylerJang27** [trufflesecurity/trufflehog#1537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

3.44.0
### Trace Output

https://gist.github.com/TylerJang27/9220e2a706929cf47c633b29eca00918

### Expected Behavior

Expect to get the following issue output on line 231 (0-indexed) or 232, as I would if I delete the last test scope.
```json
{"level":"info-0","ts":"2023-07-24T12:07:39-07:00","logger":"trufflehog","msg":"loaded decoders","count":3}
{"level":"info-0","ts":"2023-07-24T12:07:39-07:00","logger":"trufflehog","msg":"loaded detectors","total":745,"verification_enabled":0,"verification_disabled":745}
{"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_test.cc","line":231}}},"SourceID":15,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password2@gitlab.com","RawV2":"https://gitlab-ci-token:password2@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
```

### Actual Behavior

No secret found.
```json
{"level":"info-0","ts":"2023-07-24T12:08:53-07:00","logger":"trufflehog","msg":"loaded decoders","count":3}
{"level":"info-0","ts":"2023-07-24T12:08:53-07:00","logger":"trufflehog","msg":"loaded detectors","total":745,"verification_enabled":0,"verification_disabled":745}
```

### Steps to Reproduce

 1. Create an empty directory and create [trufflehog_test.cc](https://gist.github.com/TylerJang27/614e837e8b6470aa836e2c8a3ecc2e93)
 2. Run `trufflehog filesystem --json --fail --no-verification --no-update trufflehog_test.cc`
 3. No results/issues are reported.
 4. Delete the three lines before the secret 
 ```
TEST_F(BasicTest, BasicBasicBasicBasicTest) {
  // empty
}
 ```
 5. An issue is reported, even though the secret itself remains unchanged and wellformed.

## Environment
 * OS: Ubuntu 20.04.6 LTS
 * Version: 20.04.6 LTS

## Additional Context

I have also anecdotally seen a bit of weird behavior which prompted me to investigate this a bit more and produce the included repro:
- On large files (>700 lines), I was seeing incorrect line numbers being reported. A secret string on line 607 of a .cc file was being reported as a duplicate, on both lines 332 and 337 (which had unrelated code)
  - I am unable to include the file where I was originally seeing this unfortunately, but if need be I can keep pursuing a minimal repro.
- As I was building a repro file, I was sometimes seeing duplicate issues reported on the same line. That particular problem appears to have been resolved since upgrading from 3.40.0 to 3.44.0.
- I did not see the same behavior as reported in this issue when I replaced the empty test scopes with empty lines.

I would suspect the underlying problem for all of these issues is related, potentially buffer size or how regex parsing is handled. Unfortunately, I am not familiar enough with trufflehog's internals to speculate more than that.

**Comment by zricethezav** [comment]
@TylerJang27 Thanks for raising this issue. 

If we take a look at https://github.com/trufflesecurity/trufflehog/blob/f39303495a46a6d096e96c050a31b8315bbc7585/pkg/engine/engine.go#L269 with the three lines delete and without the three lines deleted you will see the issue. Trufflehog will chunk up the incoming data to scan for performance reasons. You can see that code here https://github.com/trufflesecurity/trufflehog/blob/f39303495a46a6d096e96c050a31b8315bbc7585/pkg/sources/chunker.go#L19. Because of this, if a secret is located on the edge of a chunk, i.e. a partial secret is present in two separate chunks, then that secret won't be considered. 

A potential option to alleviate this case would be to expose a `chunkSize` option, or use a true sliding window approach, which would come at a performance cost, but maybe some users would prefer that?

**Comment by TylerJang27** [comment]
Thanks! The chunking definitely makes sense for performance, although personally I consider fidelity of output to be of largest importance. On some much larger files I was also seeing some line numbers be off by a factor of 2, which was very misleading, and I suspect this same chunking is the root cause.

A chunkSize option would certainly be nice in the absence of a pure "fix".

**Comment by rgmz** [comment]
> ...I consider fidelity of output to be of largest importance

I agree. Performance shouldn't be ignored, but I'd rather a scan take an extra few seconds/minutes than miss valid secrets.

**Comment by TylerJang27** [comment]
At the very least, I think the chunker should make sure not to omit any lines and that the eventual line numbers are correct 🙏

**Comment by react-native-mapbox-gl** [comment]
I am facing the same issue. False negatives for file size. Detection of secrets changes with file size. Very frustrating. I have the older version that works correctly somehow so I assume this bug was introduced later.
[trufflehog.tar.gz](https://github.com/trufflesecurity/trufflehog/files/12298392/trufflehog.tar.gz)

**Comment by ahrav** [comment]
It seems that the problem originates from the filesystem source managing the chunking process independently, rather than utilizing the sliding window with overlap chunker. [This PR](https://github.com/trufflesecurity/trufflehog/pull/1619) is aimed at resolving the issue.

**Comment by react-native-mapbox-gl** [comment]
still seeing the same issue even with the fix.

**Comment by ahrav** [comment]
> still seeing the same issue even with the fix.

Yea, I believe the issue is still persistent in the archive handler. If you un-archive the file and scan it with the filesystem scanner you should have the secrets get picked up. I'll work on getting the archive handler to also use the sliding window with overlap chunker.

**Comment by TylerJang27** [comment]
It definitely feels like an improvement, but I think there are still some problems. Might be worth a new issue ticket, but when running on the original file I posted, I get 2 issues outputted when there should be one:
```json
{"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_test_again.cc","line":199}}},"SourceID":1,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password@gitlab.com","RawV2":"https://gitlab-ci-token:password@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
{"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_test_again.cc","line":231}}},"SourceID":1,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password@gitlab.com","RawV2":"https://gitlab-ci-token:password@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
```

**Comment by ahrav** [comment]
> It definitely feels like an improvement, but I think there are still some problems. Might be worth a new issue ticket, but when running on the original file I posted, I get 2 issues outputted when there should be one:
> 
> ```json
> {"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_test_again.cc","line":199}}},"SourceID":1,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password@gitlab.com","RawV2":"https://gitlab-ci-token:password@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
> {"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_test_again.cc","line":231}}},"SourceID":1,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password@gitlab.com","RawV2":"https://gitlab-ci-token:password@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
> ```

hmmm interesting, looks like the only difference is the line number. @zricethezav I think we might've done some work around this issue if i'm not mistaken. Although I think that issue was centralized around the same secret being detected by multiple decoders, so maybe this is a new issue.

**Comment by TylerJang27** [comment]
Anecdotally, I was also seeing this "duplicate issue" problem back on `3.44.0` with some different file/buffer sizes. I don't know if maybe the default chunk size changed, but my initial impression is that this isn't a "new" issue. If I can I'll try and find one of my old repro files sometime today.

**Comment by TylerJang27** [comment]
I can't post the original file where I saw the duplicate issue in 3.44.0, but I did find this potentially useful debugging line number issue showing up in both 3.44.0 and 3.49.0

Input file: [trufflehog_long_test.cc](https://gist.github.com/TylerJang27/48e0859df30ad16200b6ce93abe4ee3f)
3.44.0 output:
```json
{"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_long_test.cc","line":28}}},"SourceID":15,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password@gitlab.com","RawV2":"https://gitlab-ci-token:password@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
```

3.49.0 output:
```json
{"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_long_test.cc","line":28}}},"SourceID":1,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password@gitlab.com","RawV2":"https://gitlab-ci-token:password@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
{"SourceMetadata":{"Data":{"Filesystem":{"file":"trufflehog_long_test.cc","line":708}}},"SourceID":1,"SourceType":15,"SourceName":"trufflehog - filesystem","DetectorType":17,"DetectorName":"URI","DecoderName":"PLAIN","Verified":false,"Raw":"https://gitlab-ci-token:password@gitlab.com","RawV2":"https://gitlab-ci-token:password@gitlab.com/org/repo.git","Redacted":"https://gitlab-ci-token:********@gitlab.com","ExtraData":null,"StructuredData":null}
```

(There's no issue on line 29)
