### ISSUE TITLE
Email Regex failing

### ISSUE THREAD

**Issue by nickwinn** [trufflesecurity/trufflehog#156]
I'm trying to write a rule that will match email addresses and every version of regex I throw at it fails. I can check my regex in other ways and it works fine. Can anyone point me towards what I am doing wrong? 

These are the two patterns I have tried. 

[\w\.\+\-]+\@[\w]+\.[a-z]{2,3}
[a-zA-Z0-9]+@[a-zA-Z0-9]{1,22}+\.[a-zA-Z]{2,4}

They both die with similar errors to this

```Traceback (most recent call last):
  File "/truffleHog/truffleHog/truffleHog.py", line 58, in main
    rules = json.loads(ruleFile.read())
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 21 column 24 (char 1431)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/trufflehog", line 11, in <module>
    load_entry_point('truffleHog', 'console_scripts', 'trufflehog')()
  File "/truffleHog/truffleHog/truffleHog.py", line 62, in main
    raise("Error reading rules file")```

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
