### ISSUE TITLE
Error during Git scan using pre-commit

### ISSUE THREAD

**Issue by ahrav** [trufflesecurity/trufflehog#1560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
v3.45.1

### Trace Output
![TH](https://github.com/trufflesecurity/trufflehog/assets/21311841/d1d6f0d2-4587-448e-a769-a3ae262baeed)

### Expected Behavior
There should not be errors when scanning.

### Actual Behavior
An error is reported during the scan stemming from gitParse.

### Steps to Reproduce

 1. Install pre-commit framework
 2. Setup pre-commit config in repo
 3. Make changes to local repo and commit

## Environment
 * OS: macOS
 * Version Ventura v13.4.1

## Additional Context
This could be related to the recent changes introduced to gitparse.

### References
https://github.com/trufflesecurity/trufflehog/pull/1486

**Comment by rgmz** [comment]
Ah, my bad. I had originally included a case to handle merge lines but ended up removing it because the default diff filter excludes merge commits.

I don't have time to make this change right now, but here you go:
https://github.com/trufflesecurity/trufflehog/commit/e55a5fe1

**Comment by ahrav** [comment]
> Ah, my bad. I had originally included a case to handle merge lines but ended up removing it because the default diff filter excludes merge commits.
> 
> I don't have time to make this change right now, but here you go: [e55a5fe1](https://github.com/trufflesecurity/trufflehog/commit/e55a5fe1)

No worries at all, thanks for hoping in here so quickly and providing a solution. Greatly appreciated!
