### ISSUE TITLE
Feature Request: configurable maximum length of match in regex

### ISSUE THREAD

**Issue by tecknicaltom** [trufflesecurity/trufflehog#159]
Several of the regex patterns include a `.*` pattern. This pattern will match any length string, even enough that the portion of the match before and after the wildcard are not reasonably related. For instance, the GitHub regex:

```[g|G][i|I][t|T][h|H][u|U][b|B].*['|\"][0-9a-zA-Z]{35,40}['|\"]```

will match the text `github` followed by any amount of unrelated text, followed by what looks like a token. This has a problem with e.g. minified javascript files, where the match could easily be a line of text many thousands of characters long.

These regex should limit the number of characters the wildcard could match (e.g. `.{,100}`) potentially making the limit configurable.

**Comment by dxa4481** [comment]
Yup this is a good point. The regexes are actually managed in a separate repo, so if you wanna close this ticket out and open up another one over at https://github.com/dxa4481/truffleHogRegexes/issues

I'll see if I can get to it this weekend

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
