### ISSUE TITLE
repo_path not working on windows

### ISSUE THREAD

**Issue by yu0307** [trufflesecurity/trufflehog#160]
I tired to use repo_path to locate the git, but seemed like it kept asking me for git_url. I thought git_url is omitted if repo_path is supplied. 
this is what I ran: 
`truffleHog --repo_path file:///C:/somepath/PassRemove/`

**Comment by tul-urte** [comment]
Try adding a dummy git_url:

`truffleHog --repo_path file:///C:/somepath/PassRemove/ dummy_git_url`

The argument parser demands there be one, although it's then ignored.

**Comment by dtd379** [comment]
Trufflehog is prompting me for github credentials no matter what I do here for a locally cloned repo. What is the secret command line to ignore remote repositories?

**Comment by flickerfly** [comment]
I'm experiencing the same thing. I'm running it like this so the actual thing happens inside a git container. When run with the command below, I am prompted for git credentials.

`docker run --rm -it -v ${PWD}:/proj:Z registry1.dso.mil/ironbank/opensource/trufflehog/trufflehog:2.2.1
 https://my-git-server/git-repo.git --repo_path /proj`
 
The Dockerfile for the container I'm using is here: https://repo1.dso.mil/dsop/opensource/trufflehog/trufflehog/-/blob/development/Dockerfile

**Comment by flickerfly** [comment]
Workaround: I found that instead using the repo location as file:///proj/ and leaving out --repo_path worked.

**Comment by dxa4481** [comment]
Cool thanks for the update. I don't have immediate access to a windows machine so sorry this has stayed open for a bit. Feel free to update the readme with the workaround

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
