### ISSUE TITLE
[Feature] Ability to scan files ignored by Git

### ISSUE THREAD

**Issue by MVrachev** [trufflesecurity/trufflehog#161]
Hi, I read your documentation carefully and I don't find a way to scan files ignored by `gitignore`.

I want to use this tool for local repositories which doesn't currently use Git.

Is there a way to do this currently?

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It includes filesystem scanning now.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
