### ISSUE TITLE
Trufflehog returning inconsistent results with multiple secrets in a single file

### ISSUE THREAD

**Issue by sboni-sc** [trufflesecurity/trufflehog#1618]
### TruffleHog Version
trufflehog 3.46.3

### Expected Behavior
In a given file if there are multiple secrets then trufflehog should be able to detect all of those secrets.

### Actual Behavior

Trufflehog detects the number of secrets very inconsistently depending on how many secrets are there, type of secrets and their order.
eg, if a file has GCP_SECRET_A, GCP_SECRET_B, AWS_SECRET_A, AWS_SECRET_B in respective order it will only return GCP_SECRET_A and AWS_SECRET_A
but if we add slack personal token in between, eg,  GCP_SECRET_A, SLACK_SECRET, GCP_SECRET_B, AWS_SECRET_A, AWS_SECRET_B then the result is only GCP_SECRET_A, SLACK_SECRET

### Steps to Reproduce
trufflehog filesystem <file_name> --only-verified
trufflehog git file://<repo> --only-verified

results from git scanning are slightly different but it still misses some secrets.

## Environment
 * OS: MacOS Ventura
 * Version 13.5

## Additional Context
I have tried it with multiple combinations and it turns out to be different.

**Comment by rgmz** [comment]
This might be related to #1537.
