### ISSUE TITLE
Whitelist everything before commit?

### ISSUE THREAD

**Issue by mdeeks** [trufflesecurity/truffleHog#163]
When I scan our repo I get dozens of false positives. I would like a way to whitelist every previous commit so that I can ignore them in the output.
I tried:
```
git rev-parse HEAD > .trufflehog_last_commit
...a few commits later...
trufflehog --regex --entropy=False --since_commit=$(cat .trufflehog_last_commit) .
```

But that doesn't seem to work. It still returns results of old commits that are full of false positives.

I just want a way for people to review commits, mark them as "okay", and then only scan future commits. Is there a way to do that that I am not seeing?

**Comment by alishasinghania** [comment]
@mdeeks Have you found any way to do that? as I am also trying same to implement TH in my org and wants to behave in same way?
