### ISSUE TITLE
Usage of regex

### ISSUE THREAD

**Issue by fatlazycat** [trufflesecurity/trufflehog#164]
Should I expect the regex to only match against a file changed within a commit and the actual changed lines of a file ?

I'm currently finding too many matches for the same file and trying to understand it's usage.

Thanks

**Comment by dxa4481** [comment]
If the line gets modified it will rescan it because git counts that as a new patch

**Comment by fatlazycat** [comment]
Is there some difference is supplying the regex, trying to work out what i'm doing wrong but appears to get less unqiue hits with trufflehog than a 

```
git grep --name-only -E 'password\s?[:=]' | sort | uniq
```

I would have assume TH would get more results given the git grep is just looking at tracked files at the latest version

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
