### ISSUE TITLE
Databricks Token detector does not detect secrets

### ISSUE THREAD

**Issue by mimaslanka** [trufflesecurity/trufflehog#1656]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

$ trufflehog --version
trufflehog 3.52.1

### Expected Behavior

By default, the databrickstoken detector needs to be able to detect a secret.

### Actual Behavior

This does not happen. I had to make a custom detector just copying the regex from the detector to make it show up:
    keywords:
      - databricks
    regex:
      adjective: dapi[a-z0-9]{32}

### Steps to Reproduce

Run trufflehog on any file that has the dapi.... sample in there. Use the default detectors and then add the custom to see it being picked up.

## Environment
 * OS: iOS
 * Version 12.5

### References

* #0000

**Comment by ankushgoel27** [comment]
The detector not just detects the dapi secret but also detects a domain. you need to provide both to detect the valid credentials.

**Comment by zricethezav** [comment]
ankush is correct, you need both the domain and token to verify a secret. The work around for just detecting `dapi` secrets and not verifying them would be to use a custom detector like you mentioned.
