### ISSUE TITLE
[query] Are you abandoning entropy checking?

### ISSUE THREAD

**Issue by electrofelix** [trufflesecurity/trufflehog#167]
According to a blog https://blog.acolyer.org/2019/04/08/how-bad-can-it-git-characterizing-secret-leakage-in-public-github-repositories/ and https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_04B-3_Meli_paper.pdf both suggest that trufflehog only detected 25-29% of the secrets, but left out the important qualifier that this was intended to highlight that even the best tools currently don't catch everything. Unfortunately the blog appears to suggest this means you should look at using other tools instead, which I don't think was the intention of the paper.

However there is still a point that disabling entropy checks results in a lower catch rate of secrets.

The paper contains the text

> Our results show that TruffleHog is largely ineffective atdetecting secrets, as its algorithm only detected 25.236% ofthe secrets in our Search dataset and 29.39% in the BigQuerydataset. Every one of these secrets were detected by entropy,while only a fraction of them were double detected by regularexpressions. This discrepancy is worrying as the TruffleHogdevelopers are deprecating entropy detection in favor of regularexpressions detection

Presumably this is a reference to the text in the readme that the entropy checks can be disabled and previously trufflehog didn't have regex based checking:
https://github.com/dxa4481/truffleHog/blame/dev/README.md#L5-L9

Also maybe compounted by #150 which disables entropy by default requiring users to enable it explicitly. However the PR is by a new submitter, and it's unclear if trufflehog is really planning to deprecate entropy based checks or require them to be explicitly enabled rather than disabled.

The blog mimics the bad results with entropy checks disabled without any qualification:

> The pre-commit hook approach is taken by TruffleHog, though as of the time this paper was written, TruffleHog’s secret detection mechanisms were notably inferior (detecting only 25-29%) to those developed in this work (§ VII.D). You might also want to look at git-secrets which does this for AWS keys, and is extensible with additional patterns.

This does seem a little unfair, particularly as it goes on to suggest awslabs/git-secrets which only matches on AWS keys, has no support for entropy scanning at all, and misses all of the *other* secrets that trufflehog would catch unless you took all of the regexes used by trufflehog and added them to be used by awslabs/git-secrets as well.

As anyone searching for tools to scan for secrets is likely to stumble upon the blog, perhaps it would be good to have a statement here that indicates what the plan is towards entropy checking and assuming the idea is to make it more configurable and easier to handle false positives rather than remove it, to also request the blog consider updating.

[edited based on altered understanding as to what I think the paper authors were trying to suggest]

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
