### ISSUE TITLE
Feature request: Search only a single branch 

### ISSUE THREAD

**Issue by hollowsunsets** [trufflesecurity/trufflehog#170]
Not sure if there is a way to do this already, but it would be great if there was a way to search a single branch instead of all local and remote branches.

**Comment by Rajshr** [comment]
It would be great if we have this feature to scan a specific branch ?
Is this option available ?

**Comment by dxa4481** [comment]
Hey great question. I don't think this feature exists right now, but as is it won't rescan commit hashes if it's already seen them, so there's not a lot of repeat work from the other branches. That said, do you have a use case that still could make use of this feature?

**Comment by Rajshr** [comment]
Yes , in our organization we follow the branching strategy.Few projects have huge close base with more than 1k branches.Scanning such repository just hangs the process.it would be great if we can in-corporate this feature

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

I believe this feature is supported with the `git` subcommand!

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
