### ISSUE TITLE
Add IP2Location.io As New IP Detector Package

### ISSUE THREAD

**Issue by ip2location** [trufflesecurity/trufflehog#1726]
I would like to introduce the IP2Location.io IP geolocation API. It has the following advantages compare to other API providers.

- **Fast** - one of the fastest API in the market using multi-location servers and anycast technology
- **Accurate** - based on IP2Location and IP2Proxy database which is available since 2002
- **Free** - free tier with 30,000 queries monthly available to all users who sign-up online

Please consider [IP2Location.io](https://www.ip2location.io) as one of the IP detector package in TruffleHog. Feel free to ping me if you have any questions.

Thank you.

**Comment by zricethezav** [comment]
Closing since this has been added into the default detectors
