### ISSUE TITLE
Error with newlines in RSA keys

### ISSUE THREAD

**Issue by stacifractals** [trufflesecurity/trufflehog#179]
Dear all,
When I attempt to run trufflehog on an AWS codebuild formation (triggered by a push to a github repo), and the RSA key that's been committed ends with a newline, this results in trufflehog exiting with error 1 and the build fails. This error goes away when I manually remove the newline from the RSA key. 

This error does not occur locally on mac.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
