### ISSUE TITLE
Install via Homebrew

### ISSUE THREAD

**Issue by cloudlena** [trufflesecurity/trufflehog#186]
It would be great to get a [Homebrew](https://brew.sh/) formula for this project to make it easier to keep the installed version up to date on macOS.

**Comment by drewstinnett** [comment]
I'd be happy to help with this if you all like. Goreleaser can build the homebrew package with a little extra config...we would just need somewhere to push it. Maybe a new repo for all the trufflesecurity formulas, like `homebrew-trufflehog`? Users could then do a `brew tap trufflesecurity/trufflehog` and `brew install trufflehog`.

**Comment by dustin-decker** [comment]
This is now available! Thank you @drewstinnett!
