### ISSUE TITLE
Context Line Control

### ISSUE THREAD

**Issue by cloudlena** [trufflesecurity/trufflehog#188]
The output of whole files is usually hard to read if I have more than just one or two results. It would be great if there were flags to delimit the number of lines above and below the line where a secret was found. I imagine this to work similar to `grep`'s context line control flags (https://www.gnu.org/software/grep/manual/grep.html in chapter "2.1.5 Context Line Control"). `grep` has three flags: `--context/-C`, `--after-context/-A` and `--before-context/-B` but I guess the `--context` one would be sufficient.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
