### ISSUE TITLE
Programmatic use of trufflehog shows e.ResultsChan() is empty after e.Finish()

### ISSUE THREAD

**Issue by Integralist** [trufflesecurity/trufflehog#1881]
### TruffleHog Version
`3.59.0`

### Expected Behavior

I expected a call to `e.Finish()` to wait for the internal workers to complete, and after that there would be a bunch of results in a channel (i.e. the channel returned by `e.ResultsChan()`) for me to process.

### Actual Behavior

The channel returned by `e.ResultsChan()` is empty, even though I see output to suggest that two secrets (one verified and one unverified) were sent into the internal `e.results` channel.

### Steps to Reproduce

```go
ctx := context.Background()
e, err := engine.Start(
  ctx,
  engine.WithConcurrency(uint8(runtime.NumCPU())),
)
if err != nil {
  return err
}
cfg := sources.FilesystemConfig{
  Paths: []string{"./my_file.toml"},
}
if err = e.ScanFileSystem(ctx, cfg); err != nil {
  return err
}
err = e.Finish(ctx)
if err != nil {
  return err
}

// ⬇️ PRINTS 1 verified, 1 unverified
metrics := e.GetMetrics()
fmt.Printf("metrics.VerifiedSecretsFound: %d\n", metrics.VerifiedSecretsFound)
fmt.Printf("metrics.UnverifiedSecretsFound: %d\n", metrics.UnverifiedSecretsFound)

ch := e.ResultsChan() // ⬅️ EMPTY 
for result := range ch { 
  fmt.Printf("result: %#v\n", result)
}
```

## Environment
 * OS: macOS
 * Version: Ventura 13.3.1

**Comment by Integralist** [comment]
In the mean time I've implemented the folllowing workaround, which passes a custom `Printer`...

```go
// SecretPrinter tracks the results returned by trufflehog.
type SecretPrinter struct {
	mu      sync.Mutex
	Results []Result
}

// Print implements the trufflehog Printer interface.
func (p *SecretPrinter) Print(_ context.Context, r *detectors.ResultWithMetadata) error {
	p.mu.Lock()
	p.Results = append(p.Results, Result{
		Secret:   string(r.Raw),
		Verified: r.Verified,
	})
	p.mu.Unlock()
	return nil
}
```

**Comment by zricethezav** [comment]
@Integralist `e.ResultsChan()` is already being received in `notifyResults`: https://github.com/trufflesecurity/trufflehog/blob/88c1bb3289c5de44ebf4e9f484a6ebc02a2f6178/pkg/engine/engine.go#L520

https://github.com/trufflesecurity/trufflehog/blob/88c1bb3289c5de44ebf4e9f484a6ebc02a2f6178/pkg/engine/engine.go#L856

Perhaps we need to make `ResultsChan` private. Gonna close this issue as it's not an issue with the CLI tool but rather a programmatic one.
