### ISSUE TITLE
where is the default config file

### ISSUE THREAD

**Issue by marcelo321** [trufflesecurity/trufflehog#1887]
I am sorry for creating this issue, but been looking for the config file and can't find it.

There isn't any .yaml or .yml files inside the repo that work as a intended config file, so where is this file? is there any default config file that we can edit/work on it?

Sorry I just can't find it, and I would love to know which file is using the program when you don't specify one

**Comment by rgmz** [comment]
The rules are embedded into the TruffleHog binary as [they are code](https://github.com/trufflesecurity/trufflehog/tree/main/pkg/detectors).

You can customize the code and build the binary yourself, or you can write a custom regex detector as an external config:
https://github.com/trufflesecurity/trufflehog#regex-detector-alpha

**Comment by zricethezav** [comment]
@marcelo321, what @rgmz is right on the money. Let me know if you have any other questions. Closing this issue
