### ISSUE TITLE
Do not print ANSI Characters when pipelining

### ISSUE THREAD

**Issue by sdandois** [trufflesecurity/trufflehog#189]
An option to disable ANSI characters (used to display colors in terminals) would be a nice.
This is useful when saving results to a file, yet using text mode.

**Comment by AyoubUmoru** [comment]
really missing this

**Comment by danquinn2121** [comment]
This basically makes usage of this tool on large codebases impossible.

**Comment by dxa4481** [comment]
Can yall use the json output option?

**Comment by danquinn2121** [comment]
You're right, using json output and then writing a script to transform that
into a csv or whatever is the current best option. I wrote a script like
that yesterday so maybe I'll adapt it for a csv output mode PR.



*Dan Quinn *

Security Engineer | opploans <https://www.opploans.com/>

773,780.6849 mobile| dquinn@opploans.com <skranz@opploans.com>

130 East Randolph Street, Suite 3400, Chicago, IL 60601

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL!


*Confidentiality Statement & Notice: *This email is covered by the
Electronic Communications Privacy Act, 18 U.S.C. 2510-2521 and intended
only for the use of the individual or entity to whom it is addressed as it
may contain confidential and legally privileged information subject to the
attorney/client privilege. E-mail transmission is not intended to waive the
attorney-client privilege or any other privilege. Any review,
retransmission, dissemination to unauthorized persons or other use of the
original message and any attachments is strictly prohibited. If you
received this electronic transmission in error, please reply to the
above-referenced sender about the error and permanently delete this
message. Thank you for your cooperation.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

We detect a tty now to control whether color is added.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
