### ISSUE TITLE
Hardcoded thresholds of 20 in get_strings_of_set()

### ISSUE THREAD

**Issue by bandrel** [trufflesecurity/trufflehog#19]
threshold keyword variable is declared and used on the last if statement [Line 39](https://github.com/dxa4481/truffleHog/blob/master/truffleHog.py#L39), but not in the first else statement [Line 35](https://github.com/dxa4481/truffleHog/blob/master/truffleHog.py#L35)

```python
def get_strings_of_set(word, char_set, threshold=20):
    count = 0
    letters = ""
    strings = []
    for char in word:
        if char in char_set:
            letters += char
            count += 1
        else:
            if count > 20:
                strings.append(letters)
            letters = ""
            count = 0
    if count > threshold:
        strings.append(letters)
```

**Comment by bandrel** [comment]
@dxa4481 What is the purpose of the threshold value?  

it appears that you are trying to find substrings of "words" that only contain letters from the char_set AND the len(substring) > the threshold.  Is that correct?

**Comment by dxa4481** [comment]
The first comparison is a mistake, it should be if count > threshold

Currently truffleHog has a hardcoded secret minimum length of 20 chars, but I wanted to leave it somewhat open so later it could be configured via command line flag, to reduce the min secret length to search for.

**Comment by ryanohoro** [comment]
The entropy algorithm likes to pick up variable names and paths like PatternMatchingExpressionTemp and /root/Desktop/myevilstuff/. The character limit cuts down on variable names being identified as candidates.

The final entropy numbers may need to be adjusted to improve the false positive rate if the length filter comes down.

**Comment by dxa4481** [comment]
The problem with smaller secrets is it's easy to evenly distribute b64 chars accidentally, in english words. A word that never repeats letters will be identified as "high entropy"

**Comment by bandrel** [comment]
The function/variable names are a bit confusing as well.  You return a list that will only ever be one element because the input of the function is always a single word.  The function could also probably be simplified by [this](https://gist.github.com/bandrel/6263597d3653c32528b0a7e5f593c0e5)

**Comment by bbriggs** [comment]
Can we at least make this configurable without having to tinker with source? I'd like to set the threshold lower and sort through false positives rather than miss something that I know is there and is 16 chars.

**Comment by bbriggs** [comment]
I did fork and patch it, but if you're actively merging fixes then I'll send my patches your way instead.

**Comment by jcmcken** [comment]
Even if it increases false positives, this would be a useful configuration knob to have. Let the user make this trade-off instead of hard-coding the value.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
