### ISSUE TITLE
Discrepancy in 0/1/2-indexing for trufflehog filesystem and trufflehog git

### ISSUE THREAD

**Issue by TylerJang27** [trufflesecurity/trufflehog#1928]
### TruffleHog Version

`3.60.1`

### Trace Output

[input file](https://gist.github.com/TylerJang27/df68b68d596fe0a31fd927f6096a3195)
[trufflehog filesystem](https://gist.github.com/TylerJang27/bd2056fdc1c8ba749f791fe842d6a669)
[trufflehog git](https://gist.github.com/TylerJang27/ec20456d876c7c729675624cd4d9df3f)

### Expected Behavior

For filesystem and for git:
In version `3.60.1`, should get result with line number 8, and 8 respectively.
In version `<=3.60.0`, should get result with line number 7, and 7 respectively.

### Actual Behavior

For filesystem and for git:
In version `3.60.1`, get result with line number 8, and 9 respectively.
In version `<=3.60.0`, get result with line number 7, and 8 respectively.

### Steps to Reproduce
1. Create the file with the secret
2. Commit the file with the secret
3. Remove the file with the secret
4. Commit this deletion
5. Run `trufflehog filesystem --fail --only-verified --no-update secrets2.in.py`
6. Run `trufflehog git --fail --only-verified --no-update file://. --since-commit c68790ea84fc1daf20ac4da4f45986f00f499383` (use original commit sha from before starting)

## Environment
 * OS: Ubuntu
 * Version 20.04.6 LTS (Focal Fossa)

## Additional Context
It appears that after https://github.com/trufflesecurity/trufflehog/pull/1891, `trufflehog git` results are effectively 2-indexed, whereas `trufflehog filesystem` results are effectively 1-indexed. This discrepancy should not exist.

**Comment by bill-rich** [comment]
Root cause is #1876. Made more obvious by #1891 (which is being rolled back)

**Comment by bill-rich** [comment]
The reason for this is that `filesystem` doesn't do any special chunking. Git-based sources maintain line numbers through chunking in the `git` source which does its own line-aware chunking. We should add that logic to the general chunker. Or maybe to `util` so any source can utilize it.
