### ISSUE TITLE
How to run truffleHog for private repositories?

### ISSUE THREAD

**Issue by aadarshr1** [trufflesecurity/trufflehog#195]
I tried to run TruffleHog for public repositories and it is working for them. How do I run it for a private Bitbucket repository? 
It is giving me an error- 'fatal: could not read Password for '<bitbucker url>': No such device or address.

**Comment by fakeNetflix** [comment]
`No such device or address` to me suggests your host is wrong. That said, you'd auth to it the same way you would any repo, you can use SSH and it'll use your configured RSA key, or you can use HTTP with password based auth with the password in the URL.

**Comment by aadarshr1** [comment]
Hi,
Thanks for your reply. Would you please share the syntax for running the
TruffleHog command for a private repository, for a private Bitbucket repo?
I am not able to find it.

**Comment by aadarshr1** [comment]
I am trying to run this process as part of a script in a Jenkins pipeline.

**Comment by th3coop** [comment]
@aadarshr1 configure your CI machine to use SSH: https://help.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

You can use the `git` subcommand with SSH or use the `gitlab` and `github` subcommands with a token provided.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
