### ISSUE TITLE
FileNotFoundError in subprocess.py > startupinfo (windows 10)

### ISSUE THREAD

**Issue by brianmcaudill** [trufflesecurity/trufflehog#196]
When running the example "truffleHog --regex --entropy=False https://github.com/dxa4481/truffleHog.git" in windows powerShell the following error occurs:

  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

From what I understand this has to do with using the shell command in windows so I check the environment variable COMPSEC and it was set to "%SystemRoot%\system32\cmd.exe" and I also added " git.USE_SHELL = True" in def clone_git_repo() but that did not help.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
