### ISSUE TITLE
Update GitPython

### ISSUE THREAD

**Issue by JonZeolla** [trufflesecurity/trufflehog#198]
`requirements.txt` has not been updated in over a year.  In particular, `GitPython` is version pinned to 2.1.1 but 3.0.5 is available.  This is causing some `pip` error messages in upstream projects which use `truffleHug` but also use newer version of `GitPython`.

**Comment by JonZeolla** [comment]
This problem is going to get worse with some coming [`pip` changes](https://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html), any update?

**Comment by JonZeolla** [comment]
This is now causing the build to break.

**Comment by dxa4481** [comment]
Will take a look later today

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
