### ISSUE TITLE
Trufflehog running through Megalinter throws a non-blocking error for .git/config

### ISSUE THREAD

**Issue by wesley-dean-flexion** [trufflesecurity/trufflehog#2007]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

v3.60.4

### Trace Output

Please see oxsecurity/megalinter/issues/3046 for the logs and such.  

### Expected Behavior

Trufflehog should not match on `.git/config` (which isn't in the repository -- it's created earlier in the workflow)

### Actual Behavior

Trufflehog throws a non-blocking error when matching on `.git/config` .  This is actually correct -- it's finding something -- but it's neither helpful nor useful in this context.

### Steps to Reproduce

1. Run Megalinter (current version is v7.4.0) as a GitHub Action
2. Include in the workflow a step that results in the creation of that `.git/config` file (I believe actions/checkout@v4 does this)
3. observe the finding

## Environment

* GitHub Action running Megalinter v7.4.0 on ubuntu-latest

## Additional Context

I recognize this is not a Trufflehog bug.  It's not a Megalinter bug.  Both tools are doing exactly what they should.  I'm including this so that others who stumble upon this may spend less time trying to resolve the issue than I did.

### Workaround

This behavior can be worked around by creating a file (e.g., I used `.trufflehogignore`) that includes `.git/` ) and including the flag `--exclude-paths=.trufflehogignore` (or whatever filename was chosen).

#### Workaround with .gitignore

Our particular project's `.gitignore` used the `[ ]` character range fileglob notation (e.g., `[Rr]*]`) and Trufflehog wasn't able to parse it correctly.  As a result, we weren't able to use `--exclude-paths=.gitignore` ; when we did, this is the result:

```
 2023-10-27T15:17:55Z	error	trufflehog	could not create filter	{"error": "could not create exclude rules: can not compile regular expression: *.py[cod]"}
```

I suppose one could extend #865 to include that syntax, but that's beyond the scope of this "issue."

### References

* oxsecurity/megalinter/issues/3046

## Final comment

There's no request here.  I'm including this issue so that when others stumble across what I did and search the list of issues for a clue, hopefully this will send them off in a direction that could be helpful.

**Comment by zricethezav** [comment]
Thanks for the workaround @wesley-dean-flexion! Gonna close this issue since like you said, it's not really a bug and TruffleHog is working as intended on its own. This issue will still be searchable and available to the community.
