### ISSUE TITLE
Maintain an official Docker image?

### ISSUE THREAD

**Issue by stone-z** [trufflesecurity/trufflehog#201]
Hey @dxa4481, this is a cool project.

The pip installation is super easy, but I was wondering if you would be willing to publish releases to Docker hub as well? If this is something you'd be open to, I'd be happy to submit a GitHub action to do it automatically when you tag a GitHub release.

What do you think?

**Comment by dxa4481** [comment]
There is one here https://hub.docker.com/r/dxa4481/trufflehog

I just didn't advertise it too well

**Comment by stone-z** [comment]
I can't see anything listed there, and `docker pull dxa4481/trufflehog` doesn't find anything. Is it private maybe?

**Comment by dxa4481** [comment]
Hmmm odd, I'm not sure why autobuilds weren't working, but I just manually triggered the build and that should enable you to pull now

**Comment by stone-z** [comment]
Great, much appreciated :+1:  

Would it be possible to also have specific versions tagged (maybe starting with the next release, not necessarily retroactively)?

e.g. so I can do `docker pull dxa4481/trufflehog:2.0.98`

This would be ideal for automation so the behavior doesn't change unexpectedly

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

We publish docker images for it.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
