### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by kirtiso** [trufflesecurity/trufflehog#202]
Hey,

Please help me , when i'm installing truffleHog tool it's give error so please how to resolve it for installing.
irti@kali:~/truffleHog$ truffleHog --regex --entropy=False https://github.com/dxa4481/truffleHog.git
bash: truffleHog: command not found
skk@kali:~/truffleHog$ pip install truffleHog
Collecting truffleHog
  Using cached https://files.pythonhosted.org/packages/c1/53/e91b67438bae15348d4a6afe03da4e86c4416317a919f7fa83991e3b8fda/truffleHog-2.1.11-py2.py3-none-any.whl
Collecting truffleHogRegexes==0.0.7 (from truffleHog)
  Using cached https://files.pythonhosted.org/packages/7d/e3/5f800360d7f0b68f935fcd06ec18ec28802b931aa4bf6caef20de00b6546/truffleHogRegexes-0.0.7-py2.py3-none-any.whl
Collecting GitPython==3.0.6 (from truffleHog)
  Could not find a version that satisfies the requirement GitPython==3.0.6 (from truffleHog) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.13, 2.1.14, 2.1.15)
No matching distribution found for GitPython==3.0.6 (from truffleHog)
skk@kali:~/truffleHog$

**Comment by kirtiso** [comment]
Hey,

This issue is solve but now new issue create , please help me ,when trufflehog -h then command not found ????

skk@kali:~/truffleHog$ pip install truffleHog
Requirement already satisfied: truffleHog in /home/kirti/.local/lib/python2.7/site-packages (2.0.99)
Requirement already satisfied: truffleHogRegexes==0.0.7 in /home/kirti/.local/lib/python2.7/site-packages (from truffleHog) (0.0.7)
Requirement already satisfied: GitPython==2.1.1 in /home/kirti/.local/lib/python2.7/site-packages (from truffleHog) (2.1.1)
Requirement already satisfied: gitdb2>=2.0.0 in /home/kirti/.local/lib/python2.7/site-packages (from GitPython==2.1.1->truffleHog) (2.0.6)
Requirement already satisfied: smmap2>=2.0.0 in /home/kirti/.local/lib/python2.7/site-packages (from gitdb2>=2.0.0->GitPython==2.1.1->truffleHog) (2.0.5)
skk@kali:~/truffleHog$ truffleHog -h
bash: truffleHog: command not found
skk@kali:~/truffleHog$

**Comment by dxa4481** [comment]
Hi kirtiso,

I'll be at bsidessf today and tomorrow and may not have a chance to take a look until later in the week. At a high level though, you're using python2 which is no longer supported by pypi. I would recommend upgrading to python3.

-Dylan

**Comment by vijayjb** [comment]
Is this resolved? I am still getting the same error 
"No matching distribution found for GitPython==3.0.6 (from -r requirements.txt (line 1))"

**Comment by kongwenbin** [comment]
I had the same error during installation, as shown below:
```
# pip install truffleHog
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support                                                                                                                                    
Collecting truffleHog
  Using cached truffleHog-2.1.11-py2.py3-none-any.whl (13 kB)
ERROR: Could not find a version that satisfies the requirement GitPython==3.0.6 (from truffleHog) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.13, 2.1.14, 2.1.15)                              
ERROR: No matching distribution found for GitPython==3.0.6 (from truffleHog)
```

Hence I installed using the following command:
```
# python3 -m pip install --upgrade pip
Collecting pip
  Using cached pip-20.2.2-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-20.2.2
```

And it works:
```
# trufflehog 
usage: trufflehog [-h] [--json] [--regex] [--rules RULES] [--entropy DO_ENTROPY] [--since_commit SINCE_COMMIT] [--max_depth MAX_DEPTH] [--branch BRANCH]
                  [-i INCLUDE_PATHS_FILE] [-x EXCLUDE_PATHS_FILE] [--repo_path REPO_PATH] [--cleanup]
                  git_url
trufflehog: error: the following arguments are required: git_url
```

Hope it helps.

**Comment by MoatazFarid** [comment]
@kongwenbin Thanks!! your solution worked for me, just needed to upgrade pip 👍

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.

**Comment by ludbaziza** [comment]
Please help me i got this error when i run "cd trufflehog; go install"

main.go:14:2: cannot find package "github.com/go-logr/logr" in any of:
        /usr/lib/go-1.20/src/github.com/go-logr/logr (from $GOROOT)
        /root/go/src/github.com/go-logr/logr (from $GOPATH)
main.go:15:2: cannot find package "github.com/jpillora/overseer" in any of:
        /usr/lib/go-1.20/src/github.com/jpillora/overseer (from $GOROOT)
        /root/go/src/github.com/jpillora/overseer (from $GOPATH)
main.go:16:2: cannot find package "github.com/mattn/go-isatty" in any of:
        /usr/lib/go-1.20/src/github.com/mattn/go-isatty (from $GOROOT)
        /root/go/src/github.com/mattn/go-isatty (from $GOPATH)
main.go:20:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/common" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/common (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/common (from $GOPATH)
main.go:21:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/config" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/config (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/config (from $GOPATH)
main.go:22:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/context" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/context (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/context (from $GOPATH)
main.go:23:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/decoders" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/decoders (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/decoders (from $GOPATH)
main.go:24:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/detectors" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/detectors (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/detectors (from $GOPATH)
main.go:25:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/engine" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/engine (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/engine (from $GOPATH)
main.go:26:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/handlers" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/handlers (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/handlers (from $GOPATH)
main.go:27:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/log" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/log (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/log (from $GOPATH)
main.go:28:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/output" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/output (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/output (from $GOPATH)
main.go:29:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/pb/sourcespb" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/pb/sourcespb (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/pb/sourcespb (from $GOPATH)
main.go:30:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/sources" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/sources (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/sources (from $GOPATH)
main.go:31:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/sources/git" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/sources/git (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/sources/git (from $GOPATH)
main.go:32:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/tui" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/tui (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/tui (from $GOPATH)
main.go:33:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/updater" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/updater (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/updater (from $GOPATH)
main.go:34:2: cannot find package "github.com/trufflesecurity/trufflehog/v3/pkg/version" in any of:
        /usr/lib/go-1.20/src/github.com/trufflesecurity/trufflehog/v3/pkg/version (from $GOROOT)
        /root/go/src/github.com/trufflesecurity/trufflehog/v3/pkg/version (from $GOPATH)
main.go:17:2: cannot find package "google.golang.org/protobuf/types/known/anypb" in any of:
        /usr/lib/go-1.20/src/google.golang.org/protobuf/types/known/anypb (from $GOROOT)
        /root/go/src/google.golang.org/protobuf/types/known/anypb (from $GOPATH)
main.go:18:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        /usr/lib/go-1.20/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
        /root/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
