### ISSUE TITLE
Diffs are backwards

### ISSUE THREAD

**Issue by mattalexander-pantheon** [trufflesecurity/trufflehog#206]
Diffs are in the wrong direction. If I append a line with entropy to a file, then run truffleHog, the diff makes it look like I subtracted the line.

This problem does not occur if the repo only has a single commit and an issue is found in that commit. This is because you are running the diff against the root in that case.

Obviously, since this changes the diff, it may not be backwards compatible.

**Comment by mattalexander-pantheon** [comment]
I have submitted a PR to fix this: https://github.com/dxa4481/truffleHog/pull/205

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
