### ISSUE TITLE
Add an flag that disables writing to the filesystem

### ISSUE THREAD

**Issue by mattalexander-pantheon** [trufflesecurity/trufflehog#207]
If you just want the output of the command in a variable, it's not necessary to also write to the filesystem. If that is disabled, the command would run slightly faster it would not require cleanup.

Use case:

```
json_lines = $(truffleHog --skip_fs --json "URL")
# Parse json_lines in memory
```

**Comment by mattalexander-pantheon** [comment]
Fixed by https://github.com/dxa4481/truffleHog/pull/208.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
