### ISSUE TITLE
[Bug] Missing check for directories in extractRpmContent function is causing `unable to determine MIME type of nested filename` error

### ISSUE THREAD

**Issue by bugbaba** [trufflesecurity/trufflehog#2071]
Hi Team,

[extractRpmContent](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/handlers/archive.go#L354) function is not validating if the contents of the archive is a directory or a file and when a directory is passed to [handleNestedFileMIME](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/handlers/archive.go#L377)  function it fails as its expecting a file and not a directory.

TruffleHog error:
![Screenshot from 2023-10-31 16-01-58](https://github.com/trufflesecurity/trufflehog/assets/29960776/b0142677-ffc7-4df3-87de-2d4a79db225c)

`.rpm` file contents:
![image](https://github.com/trufflesecurity/trufflehog/assets/29960776/77fef8ca-6762-4cc6-9052-cb8b3a6ea020)

### Expected Behavior
Determine that the `etc` is a directory and not a file and hence its contents need to be enumerated rather than being passed to [determineMimeType](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/handlers/archive.go#L416) function to avoid the error.

### Actual Behavior

The [extractRpmContent](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/handlers/archive.go#L354) function is not checking if the contents of the archive is a directory and passed to [handleNestedFileMIME](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/handlers/archive.go#L377) to determine file type which gets failed since its, not a file.

### Steps to Reproduce

 1. Download the latest truffflehog binary.
 2. Create a `.rpm` archive with folders inside it.
 3. Scan the file using the trufflehog.
 4. We get an error like below.

```
2023-10-31T11:00:10Z    error   trufflehog      error handling file     {"job_id": 1, "source_manager_worker_id": "M0HG5", "source_type": "SOURCE_TYPE_FILESYSTEM", "source_name": "trufflehog - filesystem", "error": "unable to extract file with MIME type application/x-rpm: unable to determine MIME type of nested filename: /tmp/tmp_archive1956321577/etc, unable to read file for MIME type detection: read /tmp/tmp_archive1956321577/etc: is a directory"}
```

**Comment by ahrav** [comment]
I believe [this PR](https://github.com/trufflesecurity/trufflehog/pull/2178) should've addressed the issue. Please let me know if that's not the case and I can reopen.
