### ISSUE TITLE
Regex for Password in URL too broad

### ISSUE THREAD

**Issue by hawkeyej** [trufflesecurity/trufflehog#209]
The regex for Password for URL is currently too broad and therefore produces some false positives.

Example:
```
https://${username}:${password}/etc/etc/etc
```

This URL gets flagged even though it is not exposing any secrets.

**Comment by AdamVB** [comment]
Try it with this one:

`"Password in URL": "[a-zA-Z]{3,10}://(?!user|\\{)[^/\\s:@]{3,20}:(?!pass|secret|\\$|\\{)[^/\\s:@]{3,20}@.{1,100}[\"'\\s]",`

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
