### ISSUE TITLE
Automatic destroy of found secrets

### ISSUE THREAD

**Issue by jameslao** [trufflesecurity/trufflehog#2112]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

## Description
As the project is named "TruffleHog", I think it would make sense for it to behave like a real one. 

### Additional Context
_Pigs naturally forage and rout (dig for food) in the ground with their snouts and are keen lovers of truffles themselves and will happily gobble them up if not trained to eat something else as a reward._ (source: https://truffledogcompany.com/about-truffles/)

### Preferred Solution

1. The default behavior would be to automatically and permanently delete the found secrets without warning.
2. The user shall be obliged to train the software / add switches so that it signals the identified secrets. 
3. Some secrets shall be reserved as a reward.

#### References
https://truffledogcompany.com/about-truffles/

**Comment by zricethezav** [comment]
wat

**Comment by 0x1** [comment]
Deletion of secrets does not actually solve the core issue, as any exposed secrets are still valid and can be used by attackers. What we recommend is for users to rotate (deactivate) any exposed secrets. You can learn more on how to rotate any secrets you find with TruffleHog at your dedicated site: https://howtorotate.com/docs/introduction/getting-started/

Hope this helps.
