### ISSUE TITLE
AWS Session Key detector error

### ISSUE THREAD

**Issue by gabrielssant0s** [trufflesecurity/trufflehog#2125]
Hey!

I got the below error.

I'm running truffehog in 2 different scenarios, in the first scenario no secrets were found and I don't have any errors. 
In the second scenario, secrets are found and the error below occurs, I don't know if it's related, but can you review it, please?

23-Nov-2023 17:18:20	2023-11-23T20:18:20Z	info-0	trufflehog	finished scanning	{"chunks": 277, "bytes": 3485953, "verified_secrets": 1, "unverified_secrets": 2, "scan_duration": "724.51421ms"}
23-Nov-2023 17:18:22	🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷
23-Nov-2023 17:18:22	
23-Nov-2023 17:18:24	2023-11-23T20:18:24Z	error trufflehog	goroutine 193 [running]:
23-Nov-2023 17:18:24	runtime/debug.Stack()
23-Nov-2023 17:18:24		/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x5e
23-Nov-2023 17:18:24	github.com/trufflesecurity/trufflehog/v3/pkg/common.Recover({0x3ac6bc0, 0xc001f78540})
23-Nov-2023 17:18:24		/home/runner/work/trufflehog/trufflehog/pkg/common/recover.go:17 +0x58
23-Nov-2023 17:18:24	panic({0x2d4d660?, 0x3a87ff0?})
23-Nov-2023 17:18:24		/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
23-Nov-2023 17:18:24	github.com/trufflesecurity/trufflehog/v3/pkg/detectors/awssessionkeys.scanner.FromData({0x0?, 0xc00217c1b0?}, {0x7f67998ea2d0, 0xc001f78540}, 0x1, {0xc003526a00?, 0x306ed20?, 0x0?})
23-Nov-2023 17:18:24		/home/runner/work/trufflehog/trufflehog/pkg/detectors/awssessionkeys/awssessionkey.go:158 +0xad5
23-Nov-2023 17:18:24	github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).detectChunk(0xc0000d3ce0, {0x3ac6bc0?, 0xc00131b6e0?}, {{0x3ab08a0, 0xc001d049f0}, {{0x326ef05, 0xf}, 0x1, 0x1, 0xd, ...}, ...})
23-Nov-2023 17:18:24		/home/runner/work/trufflehog/trufflehog/pkg/engine/engine.go:508 +0x172
23-Nov-2023 17:18:24	github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).detectChunks(...)
23-Nov-2023 17:18:24		/home/runner/work/trufflehog/trufflehog/pkg/engine/engine.go:495
23-Nov-2023 17:18:24	github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).startWorkers.func2()
23-Nov-2023 17:18:24		/home/runner/work/trufflehog/trufflehog/pkg/engine/engine.go:390 +0x1f5
23-Nov-2023 17:18:24	created by github.com/trufflesecurity/trufflehog/v3/pkg/engine.(*Engine).startWorkers in goroutine 1
23-Nov-2023 17:18:24		/home/runner/work/trufflehog/trufflehog/pkg/engine/engine.go:386 +0x276
23-Nov-2023 17:18:24		{"detector_worker_id": "HFDc7", "timeout": 10, "recover": "assignment to entry in nil map", "error": "panic"}
23-Nov-2023 17:18:24	2023-11-23T20:18:24Z	info-0	trufflehog	sentry flush failed	{"detector_worker_id": "HFDc7", "timeout": 10}
23-Nov-2023 17:18:24	2023-11-23T20:18:24Z	error trufflehog	goroutine 201 [running]:
23-Nov-2023 17:18:24	runtime/debug.Stack()
23-Nov-2023 17:18:24		/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/debug/stack.go:24 +0x5e
23-Nov-2023 17:18:24	github.com/trufflesecurity/trufflehog/v3/pkg/common.Recover({0x3ac6bc0, 0xc0013112c0})
23-Nov-2023 17:18:24		/home/runner/work/trufflehog/trufflehog/pkg/common/recover.go:17 +0x58
23-Nov-2023 17:18:24	panic({0x2d4d660?, 0x3a87ff0?})

**Comment by dxa4481** [comment]
Hey there, thanks for submitting. This is due to a buggy detector I wrote recently (the AWS session key detector). We'll take a look at it early next week (it's an American holiday this weekend).

**Comment by gabrielssant0s** [comment]
No problem, let me know if I can help you.

**Comment by rgmz** [comment]
@gabrielssant0s what version of TruffleHog are you using? This seems the same as #2116, which should be fixed in the latest version.

**Comment by gabrielssant0s** [comment]
@rgmz, I'm using docker in the latest version - truffesecurity/trufflehog:latest

**Comment by zricethezav** [comment]
@gabrielssant0s thanks for raising this issue. Hopefully this will handle the error https://github.com/trufflesecurity/trufflehog/compare/check-extra-data?expand=1

**Comment by gabrielssant0s** [comment]
Hi guys!

Thanks for the quick fix.

Do you have a timeline for publishing a docker image with this fix?
