### ISSUE TITLE
Github Actions with config properties

### ISSUE THREAD

**Issue by khannar-osttra** [trufflesecurity/trufflehog#2131]
Hi Team,

I am using trufflehog in github actions and I want to pass config.yaml in github actions.
Could you please guide us how to do this and simultaneously want to ignore docs folder in the repo.

- name: TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --config=./.github/trufflehog-config.yaml --exclude-paths=./.github/exclude_patterns.txt
          args: --config=./.github/trufflehog-config.yaml
          
config.yaml 
detectors:
- name: generic-api-key
  keywords:
  - token
  - secret
  - client
  - passwd
  - password
  - auth
  regex:
    # borrowing the gitleaks generic-api-key regex
    generic-api-key: "(?i)(?:token|secret|client|passwd|password|auth)(?:[0-9a-z\\-_\\t .]{0,20})(?:[\\s|']|[\\s|\"]){0,3}(?:=|>|:{1,3}=|\\|\\|:|<=|=>|:|\\?=)(?:'|\"|\\s|=|\\x60){0,5}([0-9a-z\\-_.=]{10,150})(?:['|\"|\\n|\\r|\\s|\\x60|;]|$)"

**Comment by zricethezav** [comment]
@khannar-osttra 

Here's an example on how you would do that:

https://github.com/zricethezav/thghaconfig

https://github.com/zricethezav/thghaconfig/actions/runs/7878935604
