### ISSUE TITLE
Is it possible to scan the whole repository filebased?

### ISSUE THREAD

**Issue by deknos** [trufflesecurity/trufflehog#216]
Hi,
before being able to install the pipeline i have to check the repository if there are already files with credentials in there. is there a possibility for a certain branch to check the FILES in there and not the commits leading up to the Files? Or should i use another tool for that?

**Comment by mykter** [comment]
Duplicate of #92 
https://github.com/feeltheajf/truffleHog3 implemented this feature.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It supports filesystem scanning!

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
