### ISSUE TITLE
The Slack Webhook verifier returns False even for active secrets.

### ISSUE THREAD

**Issue by shreyas-acharya-amagi** [trufflesecurity/trufflehog#2177]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
trufflehog 3.63.1

## Description
The Slack Webhook verifier's condition seems to be outdated. The link to the conditions : https://github.com/trufflesecurity/trufflehog/blob/11394ea318a12a5bf99c1b0cb7ba5e44b3c7a79c/pkg/detectors/slackwebhook/slackwebhook.go#L79

The condition seem to match the request's result with the statement `missing_text` when the exit code is 400. But the actual response from the request seem to be `missing_text_or_fallback_or_attachments`. 

Attached below are some screenshots for reference : 
<img width="1029" alt="Screenshot 2023-12-05 at 8 21 13 PM" src="https://github.com/trufflesecurity/trufflehog/assets/130966494/fabc794f-6186-453c-8c58-e02de5a7cc8b">

**Comment by ahrav** [comment]
hey @shreyas-acharya-amagi I believe this issues should be resolved with [this PR](https://github.com/trufflesecurity/trufflehog/pull/2193). Please let me know if you are still encountering the issue and we can re-open this.
