### ISSUE TITLE
Orgs People

### ISSUE THREAD

**Issue by domwhewell-sage** [trufflesecurity/trufflehog#2189]
## Description
GitHub organizations can have public members (https://github.com/orgs/<org>/people)
I have come across instances where members of an organization have an old fork of the organizations public repository containing valid secrets (removed in the org repo but not from members forks)

### Preferred Solution
When a Github Org is supplied users can supply the optional flag `--include-members` so trufflehog will obtain a list of members publicly linked with the organization and scan their repository's for secrets

### Additional Context
N/A

#### References

N/A

**Comment by rgmz** [comment]
Doesn't this already exist? Or am I misreading the issue? (it has been a long day)

https://github.com/trufflesecurity/trufflehog/blob/ee6923a24116e38bc6606bb6b8a222ce1a312041/main.go#L83

**Comment by domwhewell-sage** [comment]
Aha it has been a long day, that's awesome thanks for the quick reply!
