### ISSUE TITLE
Whitelist False positive in the next scan

### ISSUE THREAD

**Issue by alishasinghania** [trufflesecurity/trufflehog#220]
When I scan our repo I get dozens of false positives. I would like a way to whitelist every previous commit so that I can ignore them in the output.
For implementation in my org, I just want a way for people to review commits, mark them as "okay", and then only scan the future commits. The issues which are marked as false positive should not raise again. Is there a way to do that that I am not seeing?

**Comment by AdamVB** [comment]
you could add the paths to the exclusion patterns

**Comment by alishasinghania** [comment]
that will exclude the complete file from scanning. If in some commit, anything new is added it will exclude that also.

**Comment by AdamVB** [comment]
thats true.

one workaround I'm currently using is adding a keyword exclusion to the regex.


looks like this for example:

`"Generic Password": "[p|P][a|A][s|S][s|S][w|W][o|O][r|R][d|D][=:]{1,2}['|\"|\\s]{0,2}(?!pass|PASS|Pass|debug|ssh|dummy|XXX|xxx|test|secret|\\$|\\{)[0-9a-zA-Z]{7,45}['|\"]{0,1}",`

not an ideal solution but better than nothing

**Comment by alishasinghania** [comment]
thanks

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

#22 should address this when implemented.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
