### ISSUE TITLE
scan private repositories with trufflehog

### ISSUE THREAD

**Issue by pappsec20** [trufflesecurity/trufflehog#221]
Is it possible t scan private repository using trufflehog?

**Comment by inverse** [comment]
yes  you just point it at a private repo URL ensuring the user running it as the proper credentials to auth.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
