### ISSUE TITLE
Checking for only master branch

### ISSUE THREAD

**Issue by viky28** [trufflesecurity/trufflehog#222]
Can i check secrets for only master branch .I tried using --branch=master but its not working for me.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

See the `--branch` flag of the `git` subcommand.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
