### ISSUE TITLE
Update feature

### ISSUE THREAD

**Issue by fabaff** [trufflesecurity/trufflehog#2239]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

## Description
If not running with `--no-update` then `trufflehog` wants to do an update. For installations which were done with the packages out of a distribution's repository this can cause issues for future updates of `trufflehog`.

If the filesystem is read-only or the permission not sufficient then the update fails for those users.

```bash
2023-12-17T10:21:29+01:00       error   trufflehog      error occurred with trufflehog updater 🐷       {"error": "cannot move binary (exit status 1)"}
``` 

### Preferred Solution
From a packager point of view:
It would be great to be able to disable the update feature during build time. 

This approach would require quite a bit of works, I assume. 

Another way:
Having the update feature being opt-in.

This  would work for all users. But would require from the users who did the installation manually that they use something like `--update` explicitly. If I would work with a manual installation then I wouldn't want it that way :wink: 

### Additional Context
Currently it seems that most distribution packages (at least some of them which are listed on repology) ignore the issue or depend on that their users execute `trufflehog` with `--no-update`. 

#### References

None

**Comment by marcelo321** [comment]
happening all the time, pretty annoying

**Comment by zricethezav** [comment]
Duplicate, closing in favor of https://github.com/trufflesecurity/trufflehog/issues/1239
