### ISSUE TITLE
[bug] Relative filepaths in GHA no longer work

### ISSUE THREAD

**Issue by skeweredlogic** [trufflesecurity/trufflehog#2248]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
This PR introduced the change: [#2138](https://github.com/trufflesecurity/trufflehog/pull/2138)

### Trace Output

[gist](https://gist.github.com/skeweredlogic/cfdce407a0b40fe47479d820f969df35)

### Expected Behavior

When using the `-x` flag with an ignore file argument, the file path specified should not break when relative to the repo/local filesystem root.

### Actual Behavior

Because the referenced file was copied into `/tmp`, but the entrypoint runs from `/`, `trufflehog` cannot find it.

### Steps to Reproduce

 1. Create a `.truffleignore` file used with the `-x` flag to ignore specific paths/files.
 2. Run `trufflehog` similarly to how it would be done in GHA: `docker run --rm -v .:/tmp ghcr.io/trufflesecurity/trufflehog:latest 
filesystem /tmp --fail --no-update --github-actions -x .truffleignore --trace`.
 3. Observe that `trufflehog` cannot find the file specified.

## Environment
 * OS: any (docker container)
 * Version: any (#2138 introduced the relevant change in `action.yml`)

### References

* #0000

**Comment by joeleonjr** [comment]
Since we can't mount to "/", I think an easy fix for this is to define a working directory in the docker command within the `action.yml` file. 

Ex:

```
docker run --rm -v "$REPO_PATH":/tmp  -w /tmp ....
```

@zricethezav @codevbus any thoughts on this idea?

**Comment by zricethezav** [comment]
> docker run --rm -v "$REPO_PATH":/tmp  -w /tmp ....

I've seen this in lots of GHAs, I'd say it's a good solution.

**Comment by zricethezav** [comment]
@skeweredlogic https://github.com/trufflesecurity/trufflehog/pull/2393 should fix it. Please reopen this issue if the problem persists.

**Comment by skeweredlogic** [comment]
Thank you! will be able to test when #2396 is closed.
