### ISSUE TITLE
Is it possible to invoke trufflehog natively within python and not using the cli?

### ISSUE THREAD

**Issue by sillyfatcat** [trufflesecurity/trufflehog#225]
I'm trying to avoid doing this:

```subprocess.Popen(['trufflehog', full_path], stdout=subprocess.PIPE)```

Would it be possible to invoke it natively by doing something like...

    from trufflehog import trufflehog
    trufflehog.run(full_path)

**Comment by kslo-resideo** [comment]
I am also interested in this functionality. Subscribing to this ticket.

**Comment by specters312** [comment]
Probably from just scanning over trufflehog really quick I see find_strings starts the initial scanning and stuff.

```
def find_strings(git_url, since_commit=None, max_depth=1000000, printJson=False, do_regex=False, do_entropy=True, surpress_output=True, custom_regexes={}, branch=None, repo_path=None, path_inclusions=None, path_exclusions=None):
```
Looks like find_stings copies the repo locally with
```
if repo_path:
        project_path = repo_path
    else:
        project_path = clone_git_repo(git_url))
```
then continues on to analyze 
branches and commits and that is store in `output`

After that `output` looks like it is passed into `handle_results(output, output_dir, foundIssues):` 

It looks like it write to `result_path`  so probably multiple files to multiple paths. 

Last you need to make sure to run `def clean_up(output)` or else the temp file will remain in the directory.

I didn't read super far into this so like entropy and stuff was not analyzed but you get the idea that you need to save this returned variables and then just pass them along properly everything is there it looks like.

**Comment by dtd379** [comment]
Trufflehog is available as a python package and will work as you suggested.
https://pypi.org/project/truffleHog/
As well as trufflehog3
https://pypi.org/project/truffleHog3/

Trufflehog methods can be executed as such:

```
from truffleHog import truffleHog as th

th.find_strings(repo, args.since_commit,
                                           args.max_depth, printJson=True,
                                           do_regex=args.do_regex,
                                           do_entropy=do_entropy,
                                           surpress_output=True,
                                           custom_regexes=rules,
                                           branch=args.branch)
```

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.

**Comment by dinvlad** [comment]
Is there a way to trigger a scan via Go code, as with Python in the previous version?
