### ISSUE TITLE
Azure Devops Repo + Pipeline --> fatal: could not read Username for 'https://<myorganization>.visualstudio.com': terminal prompts disabled

### ISSUE THREAD

**Issue by ivialex** [trufflesecurity/trufflehog#226]
Hi guys,

I'm trying to use truffleHog to scan Azure Repos and return this error as below. 

I'm try to run:

1. pip install truffleHog
2. trufflehog scan

## Is there any example to scan using azure devops pipelines?

> 2020-07-16T15:02:42.2474534Z ##[section]Starting: TruffleHog Scan for searches through git repositories for secrets
>
>2020-07-16T15:02:42.2482130Z >==============================================================================
>
>2020-07-16T15:02:42.2482498Z Task : Bash2020-07-16T15:02:42.2482793Z Description : Run a Bash script on macOS, Linux, or >Windows2020-07-16T15:02:42.2483075Z Version : 3.171.12020-07-16T15:02:42.2483321Z Author : Microsoft Corporation2020->07-16T15:02:42.2483678Z Help : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash2020-07->16T15:02:42.2484054Z >==============================================================================
>
>2020-07-16T15:02:42.3716717Z Generating script.2020-07-16T15:02:42.3725061Z Script contents:2020-07->16T15:02:42.3726395Z trufflehog --json --regex --entropy True --rules trufflehog-rules.json -i include-patterns.txt -x exclude->patterns.txt https://<myorganization>.visualstudio.com/<myproject>/_git/<myrepo>
>
>2020-07-16T15:02:42.3737357Z ========================== Starting Command Output >===========================
>2020-07-16T15:02:42.3751785Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/c36f6e3e-139f-4586-86fe->2e84c5a2a362.sh
>2020-07-16T15:02:42.7285203Z Traceback (most recent call last):
>2020-07-16T15:02:42.7286464Z   File "/usr/local/bin/trufflehog", line 11, in <module>
>2020-07-16T15:02:42.7287241Z     sys.exit(main())
>2020-07-16T15:02:42.7289097Z   File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 82, in main
>2020-07-16T15:02:42.7290699Z     surpress_output=False, branch=args.branch, repo_path=args.repo_path, >path_inclusions=path_inclusions, path_exclusions=path_exclusions)
>2020-07-16T15:02:42.7296053Z   File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 309, in find_strings
>2020-07-16T15:02:42.7303007Z     project_path = clone_git_repo(git_url)
>2020-07-16T15:02:42.7304899Z   File "/usr/local/lib/python3.6/dist-packages/truffleHog/truffleHog.py", line 152, in >clone_git_repo
>2020-07-16T15:02:42.7305868Z     Repo.clone_from(git_url, project_path)
>2020-07-16T15:02:42.7307197Z   File "/usr/local/lib/python3.6/dist-packages/git/repo/base.py", line 1017, in clone_from
>2020-07-16T15:02:42.7308221Z     return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
>2020-07-16T15:02:42.7309623Z   File "/usr/local/lib/python3.6/dist-packages/git/repo/base.py", line 958, in _clone
>2020-07-16T15:02:42.7310877Z     finalize_process(proc, stderr=stderr)
>2020-07-16T15:02:42.7312191Z   File "/usr/local/lib/python3.6/dist-packages/git/util.py", line 328, in finalize_process
>2020-07-16T15:02:42.7313029Z     proc.wait(**kwargs)
>2020-07-16T15:02:42.7314202Z   File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 408, in wait
>2020-07-16T15:02:42.7315089Z     raise GitCommandError(self.args, status, errstr)
>2020-07-16T15:02:42.7316332Z git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
>2020-07-16T15:02:42.7317935Z   cmdline: git clone -v >https://<myorganization>.visualstudio.com/<myproject>/_git/<myrepo> /tmp/tmpu4f2etsz
>2020-07-16T15:02:42.7319350Z   stderr: 'Cloning into '/tmp/tmpu4f2etsz'...
>2020-07-16T15:02:42.7320773Z fatal: could not read Username for 'https://<myorganization>.visualstudio.com': terminal >prompts disabled
>2020-07-16T15:02:42.7321850Z '
>2020-07-16T15:02:42.7486379Z 
>2020-07-16T15:02:42.7544540Z ##[error]Bash exited with code '1'.
>2020-07-16T15:02:42.7559133Z ##[section]Finishing: TruffleHog Scan for searches through git repositories for secrets

**Comment by ivialex** [comment]
Hi guys,

I put my personal access token before (PAT) azure repo url like this https://PAT@<AZURE REPO URI> and it's works. 

But it is returned this error now: "##[error]Bash exited with code '1". This error don't help. Then, I running in my local computer and return this error below:

>Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ifrancos\AppData\Roaming\Python\Python37\Scripts\trufflehog.exe\__main__.py", line 7, in <module>
  File "C:\Users\ifrancos\AppData\Roaming\Python\Python37\site-packages\truffleHog\truffleHog.py", line 82, in main
    surpress_output=False, branch=args.branch, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions)
  File "C:\Users\<MY USER>\AppData\Roaming\Python\Python37\site-packages\truffleHog\truffleHog.py", line 355, in find_strings
    shutil.rmtree(project_path, onerror=del_rw)
  File "c:\program files\python37\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\program files\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\program files\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\program files\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\program files\python37\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\<MY USER>\AppData\Roaming\Python\Python37\site-packages\truffleHog\truffleHog.py", line 107, in del_rw
    os.remove(name)
PermissionError: [WinError 5] Acesso negado: 'C:\\Users\\<MY USER>\\AppData\\Local\\Temp\\tmpfxlqrt01\\.git\\objects\\pack\\pack-a6e6d90b56e5b84436e0d1cd5190c02010c9955e.idx'

I tried run this command in command prompt in Windows 10 how Administrator and return the same error.

I runned too in other computer with linux mint and it's work fine. 

My vmimage in my job that is running this command is ubuntu-latest. I put the condition continueOnError how true but this bash task return the error "##[error]Bash exited with code '1"

any idea what it might be?

**Comment by jveldhuijzen** [comment]
It's the same issue as posted here in this pr: #203 
What I did locally was pipe the output of the command into a a file (this error only pops up at he end of the process)
`trufflehog --json <path or online git repo you want to scan>  > output.json`

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
