### ISSUE TITLE
GHA workflows failing with "jq missing"

### ISSUE THREAD

**Issue by johnseekins-pathccm** [trufflesecurity/trufflehog#2269]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

GHA@main

### Trace Output

https://github.com/trufflesecurity/trufflehog/actions/runs/7312576719/job/19923290176

### Expected Behavior

The action can run

### Actual Behavior

The action fails because `jq` is missing.

### Steps to Reproduce

Run the Github action workflow, even in this repo.

## Environment
 * OS: ubuntu
 * Version latest

**Comment by johnseekins-pathccm** [comment]
@0x2b3bfa0 You worked on a similar bug in https://github.com/trufflesecurity/trufflehog/pull/2259. Any thoughts on a fix?

**Comment by 0x2b3bfa0** [comment]
My bad, @johnseekins-pathccm; sorry! 😳

**Comment by 0x2b3bfa0** [comment]
Could we run [`secrets.yml`](https://github.com/trufflesecurity/trufflehog/blob/a98a4de2fb5c74eeecf8438ff1b7e42b2d3021df/.github/workflows/secrets.yml) on every pull request so this doesn't ever happen again?
