### ISSUE TITLE
Stop reporting the fixed commits.

### ISSUE THREAD

**Issue by vijayjb** [trufflesecurity/trufflehog#227]
Hello..
I am new to trufflehog
How to make the trufflehog not to list the older commits with the sensitive data, which is fixed with newer commit?

This causes lot of noise and false positives.  Appreciate any help!!

Thanks
Vijay

**Comment by jefQuery** [comment]
Actually clean your git history of the secrets with [BFG](https://rtyley.github.io/bfg-repo-cleaner/).
Or stop looking so far back such that you stop scanning the older commit with the`--max_depth MAX_DEPTH` flag

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
