### ISSUE TITLE
RedHat throwing git.exc.GitCommandError:

### ISSUE THREAD

**Issue by vijayjb** [trufflesecurity/trufflehog#230]
We are having TruffleHog in one of Redhat server and getting this error TruffleHog while connecting to remote repo 

git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https:URL..
  stderr: 'POST git-upload-pack (gzip 4404 to 2221 bytes)
error: RPC failed; result=35, HTTP code = 0
fatal: The remote end hung up unexpectedly

Any clues? We are able to connect to git from Redhat out of TruffleHog

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
