### ISSUE TITLE
Exception thrown on run in NixOS

### ISSUE THREAD

**Issue by brizzbuzz** [trufflesecurity/trufflehog#2300]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

trufflehog 3.63.0

### Trace Output

```
 trufflehog git https://github.com/unredundant/bigbang --only-verified --trace
2024-01-12T12:36:30-05:00       error   trufflehog      error occurred with trufflehog updater 🐷       {"error": "cannot move binary (exit status 1)"}
```

### Expected Behavior

shouldn't fail

### Actual Behavior

fails

### Steps to Reproduce

1. Install nixos (23.11)
2. Install trufflehog
3. Try to run trufflehog

## Environment
 * OS: NixOS
 * Version 23.11

## Additional Context
N/A

### References

n/a

**Comment by dustin-decker** [comment]
This is a permission issue with the updater. The user that ran trufflehog does not have permission to write in the directory that it resides in.

**Comment by cpcloud** [comment]
Would it be okay if trufflehog didn't try to update the binary by default? In the meantime, you can work around this issue by passing `--no-update`.

**Comment by zricethezav** [comment]
@cpcloud described the solution, run with `--no-update`

**Comment by cpcloud** [comment]
Darn, I was hoping that running a program by default didn't try to update itself.
