### ISSUE TITLE
not sure how to execute the docker container

### ISSUE THREAD

**Issue by ronykris** [trufflesecurity/trufflehog#231]
I am not sure how to execute the docker container. Below is the output of the docker run command. I know i have to pass the git repo as a parameter, but it should still execute without it and give a different error.

docker run dxa4481/trufflehog
standard_init_linux.go:211: exec user process caused "exec format error"

How do i run it?

**Comment by JPMartinezz** [comment]
checkout issue "Add usage of Docker image to docs #211".

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
