### ISSUE TITLE
Trufflehog Python package needs to be updated

### ISSUE THREAD

**Issue by za** [trufflesecurity/trufflehog#2328]
## Description
Hi there,

I think we need to update the trufflehog Python package, as installing using pip, is installing version 2.x (which was released > 5 years ago).

```
(.env) ➜ git:(main) ✗ pip3 install trufflehog
Collecting trufflehog
  Downloading truffleHog-2.2.1-py2.py3-none-any.whl (13 kB)
```

**Comment by zricethezav** [comment]
TruffleHog v3 is not a python package and can't be installed with `pip`. 

If you want to use the old v2 TruffleHog then `truffleHog-2.2.1` is the version you get

**Comment by za** [comment]
Hi @zricethezav Thanks for the explanation.
