### ISSUE TITLE
Unable to scan the local git repo

### ISSUE THREAD

**Issue by venkatn087** [trufflesecurity/trufflehog#2331]
Hi Team, 
this is reference to Issue number- 2327, still my issue is not resolved.
i have tried with the suggested solution, but not worked. could you please help me on the same.

![image](https://github.com/trufflesecurity/trufflehog/assets/52975559/59fe5fca-9424-4ad3-bfe6-9fbded3f6c0f)

**Comment by rgmz** [comment]
TruffleHog automatically updates when you run it. It appears that the user has insufficient permissions, causing the update to fail.

You can disable automatic updates by running TruffleHog with the `--no-update` flag.

**Comment by zricethezav** [comment]
@rgmz is right, run with `--no-update`
