### ISSUE TITLE
truffleHog error while using --help

### ISSUE THREAD

**Issue by sankhacse18** [trufflesecurity/trufflehog#234]
C:\Users\Sankhadeep>truffleHog --help
Traceback (most recent call last):
  File "c:\users\sankhadeep\appdata\local\programs\python\python38-32\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "c:\users\sankhadeep\appdata\local\programs\python\python38-32\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "c:\users\sankhadeep\appdata\local\programs\python\python38-32\lib\site-packages\git\cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

**Comment by RepositoryOfCode** [comment]
Hey, did you fix that issue? I just have same one )

**Comment by dxa4481** [comment]
This issue looks like Git just needs to be installed on the system and included in the PATH. Trufflehog currently requires Git to be installed

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
