### ISSUE TITLE
Refrencing $PWD in GitHub Action Behavior Change

### ISSUE THREAD

**Issue by LINDET04** [trufflesecurity/trufflehog#2365]
Hello

There was some kind of change with the GitHub Action that broke our check. I was able to find that v3.63.5 was working properly, but versions since then appear to work different. I am unsure if this is a bug, or expected change that I wasn't aware of. The only change between these two action runs was the version. Please let me know if I need to be passing the path in a different method now. Thanks

### Works with v3.63.5
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.63.5
        with:
          path: ./
          head: ${{ github.head_ref }}
          base: ${{ github.base_ref }}
          extra_args: --debug --no-verification --json --config=$PWD/.github/workflows/truffle-config.txt

### Fails with latest version
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          head: ${{ github.head_ref }}
          base: ${{ github.base_ref }}
          extra_args: --debug --no-verification --json --config=$PWD/.github/workflows/truffle-config.txt

### Error message
Status: Downloaded newer image for ghcr.io/trufflesecurity/trufflehog:latest
trufflehog: error: path '/usr/bin/.github/workflows/truffle-config.txt' does not exist, try --help

### Runner Details
  Image: ubuntu-22.04
  Version: 20240201.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240201.1/images/ubuntu/Ubuntu2204-Readme.md

**Comment by zricethezav** [comment]
@LINDET04 https://github.com/trufflesecurity/trufflehog/pull/2393 should fix it. Please reopen this issue if the problem persists.
