### ISSUE TITLE
Trufflehog issues to scan the git repo with the current commit

### ISSUE THREAD

**Issue by toshith** [trufflesecurity/trufflehog#237]
Inspite of using --since_commit parameter along with the hash value of git commit. It is not being able to detect secrets.

trufflehog <git_url> --since_commit="<git_hash_value>". Kindly fix this...or help me to scan my git repo updated with last commit...I dont want to scan the whole git repo commited from scratch. I just want to scan the repo which is last committed.

Any help will be highly appreciated.Thanks

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
