### ISSUE TITLE
No assets for OS in release 3.67.1

### ISSUE THREAD

**Issue by eptw4by** [trufflesecurity/trufflehog#2370]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
Latest 3.67.1

### Trace Output

Run curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  shell: /usr/bin/bash -e {0}
trufflesecurity/trufflehog info checking GitHub for latest tag
trufflesecurity/trufflehog info found version: 3.67.1/linux/amd6[4]
trufflesecurity/trufflehog err http_download_curl received HTTP status 404

### Expected Behavior

Release 3.67.1 release have assets added for all OSes 

### Actual Behavior

Assets not present, so https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh fails 

### Steps to Reproduce

Run `https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh` and observe error with release 3.67.1

**Comment by dustin-decker** [comment]
Thank you for reporting. Looks like it was improperly tagged. It should be available soon now.

**Comment by dustin-decker** [comment]
The artifacts are available now.
