### ISSUE TITLE
exclude secret values

### ISSUE THREAD

**Issue by jsimoni** [trufflesecurity/trufflehog#2392]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

## Description
We would like to be able to exclude specific secret values rather than entire files/folders.

### Preferred Solution
add a --exclude-secrets parameter that reads a list of secrets from a file to ignore during scanning

### Additional Context
We have scenarios where the secrets are verified, but they do not grant access to our assets.

**Comment by OlesYudin** [comment]
We are facing a similar situation. I believe a feature that allows the exclusion of secret values would help avoid false positives.

For example, having a very old repository that contained many secrets in the past can be problematic. Even if you have removed all secrets from the repository and rotated them, the git history still contains these secrets. When you enable the `--exclude-paths` key, it will exclude all files with secrets. While this works well, it poses a risk if someone creates a new file with a name that has already been excluded. This would prevent new findings from being detected.

For CI/CD processes, you can run a `filesystem` Trufflehog scan before building the application. However, if someone mistakenly pushes a secret into the repository and deletes it in the next commit, it becomes challenging. In such cases, integrating Trufflehog scans for every new commit is necessary, but this can be costly in an active development environment.

**Comment by dxa4481** [comment]
I would recommend using the `--only-verified` flag, because that actually checks which secrets are still active, and only reports the ones that are still active.

**Comment by jsimoni** [comment]
@dxa4481 we are using the `--only-verified` flag and still need to exclude specific secrets.
