### ISSUE TITLE
Version pinning for GHA

### ISSUE THREAD

**Issue by skeweredlogic** [trufflesecurity/trufflehog#2397]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

## Description
There have been a few changes in the past few months that break CI workflows (either changes to the GHA or changes to the `trufflehog` published image). Currently, we have the ability to pin the version of the GHA via branch refs or tags, but there is no ability to pin the version of the container image being used to execute secrets scanning via GHA. If there is an issue that arises from the latest built container image, there is no recourse for callers of this GHA to fall back to a known-safe version.

### Preferred Solution
There should be an input to the GHA that allows the caller to specify the version of the `trufflehog` container to use. The default value should be `latest`.

**Comment by zricethezav** [comment]
Hey @skeweredlogic gonna close this issue since your PR has been merged. Thanks a ton for the contribution. This is a great change.
