### ISSUE TITLE
Help Wanted: Unexpected issue, potential bug with workflow

### ISSUE THREAD

**Issue by brndnwd** [trufflesecurity/trufflehog#2451]
Summary:
Please help me understand why Trufflehog is throwing warnings here. It is causing CI pipelines to fail and I need to remediate.

Background: 
One line of code in three files in our repo was flagged in an org level trufflehog scan. It was a false positive - example URI. We addressed according to internal guidelines - essentially removing the lines in a new commit to main branch but not modifying the history of the files. That was months ago and we have also incorporated trufflehog scans into our CI pipelines for this repo. That scan has been running fine for months as well.

Issue at hand:
Now, out of the blue, trufflehog is throwing warnings in reference to the lines that were removed. The console output is generic (side quest: please let me know if there is any way to have trufflehog reference the lines in question in the action output) - this is what we see:
'''
Warning: Found unverified URI result with BASE64 encoding 🐷🔑
Warning: Found unverified URI result with BASE64 encoding 🐷🔑
Warning: Found unverified URI result 🐷🔑
'''

The workflow runs  on pull requests and is failing with every new pr last few days - despite the fact that all the pr feature branches are based on fresh pulls from the main branch and none of them are editing the files in question. I mentioned the generic warnings... it took me a sec to realize it was the three files I mentioned that were triggering trufflehog. In the files changed tab of the pr, I can see those three files listed at the bottom in the 'Unchanged files with check annotations' section along with the lines numbers where the false positive secret used to exit....even here it shows the latest versions of these files without the URI, as you can see here where there is no code on line 6:
![image](https://github.com/trufflesecurity/trufflehog/assets/40863255/633bc538-e5d6-4343-8276-954c8dbe2bbd)

Further details:
I use a shared action in my company's org to run the trufflehog workflow . It is defined as:

name: TruffleHog OSS
uses: trufflesecurity/trufflehog@v3.56.1
with:
path: ./
base: ${{ github.event.repository.default_branch }}
head: HEAD
extra_args: --debug --no-verification

Note I have also tested on latest version v3.67.5 and get the same behavior.

My understanding is trufflehog should only be scanning the incoming commits on the feature branch to be merged. In console output I see something like:
024-02-13T01:01:01Z	info-1	trufflehog	scanning repo	{"source_manager_worker_id": "abc123", "unit": "./", "repo": "https://github.com/my-org/my-repo", "base": "my-base-sha", "head": "my-head-sha"}

Now the base sha here in the action output looks right.... meaning it is the latest commit from main branch and the base for all the incoming feature commits. But the head sha in the output is a mystery to me. Searching the repo reveals this sha is not tied to any commit on any branch.

That's all I've got. Let me know if you have any ideas. Thanks!

**Comment by zricethezav** [comment]
@brndnwd take a look at how base and head are constructed for push events: https://github.com/trufflesecurity/trufflehog/blob/main/action.yml

try removing 
```
base: ${{ github.event.repository.default_branch }}
head: HEAD
```

and see if that fixes your problem

**Comment by brndnwd** [comment]
thank you @zricethezav, when going with the default base and head, trufflhog was seemingly scanning the entire history of the repo on pull_request whenever there were new commits on the base branch that didn't exist the feature branch. I have a working solution which is to explicitly set the base like:
`git fetch origin prod:prod
 BASE_COMMIT=$(git merge-base HEAD prod)
 echo "Base commit is $BASE_COMMIT"
 echo "base_commit=$BASE_COMMIT" >> "$GITHUB_OUTPUT"`
 then when I call trufflehog:
 `with:
 path: './'
 base: ${{ needs.get_base_commit.outputs.base_commit }}
 head: ${{ github.sha }}`
 
 This satisfies my need of only scanning incoming commits on pull requests. As such, I am closing the issue. Appreciate your time.
