### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by ashwin31** [trufflesecurity/trufflehog#250]
does this project have web UI?

**Comment by dxa4481** [comment]
There's a fork of Trufflehog that has an HTML output I plan to merge soon

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
