### ISSUE TITLE
Custom_regexes not catching secrets

### ISSUE THREAD

**Issue by HighWatersDev** [trufflesecurity/trufflehog#251]
I'm running custom regex with truffleHog. I tested the regex on couple of regex online sites and it is valid. When I run 

`trufflehog --regex --entropy=False --rules /path/to/the/regex.json git_url`

I get no matches.

Here's the regex I'm trying to use:

`{
    "Teams Webhook": "^https:\\/\\/gtvault\\.webhook\\.office\\.com\\/[a-zA-Z]+.*[a-zA-Z]+\\/.*$"
  }`

I ran it against git repo that has Teams webhook as a sanity check.

I'd expect TH to catch the webhook but I get no issues found.

**Comment by dxa4481** [comment]
Hey @HighWatersDev thanks for reporting. It would be helpful if you could provide a repo with the test case as well, or a snippet of data you expect to match (not any real sensitive secrets of course)

Additionally, separate from this issue, let's get the Teams Webhook secret added here https://github.com/dxa4481/truffleHogRegexes/blob/master/truffleHogRegexes/regexes.json#L33

**Comment by HighWatersDev** [comment]
Here's a snippet of Teams webhook that we use (the characters are replaced):

`https://gtvault.webhook.office.com/webhookb2/90jvoif-8856-6532-8896-ntbrth644t4efq@4gebrtheb5-5y6g-88gg-t5t5g-4r4fe34f3f337/IncomingWebhook/39j39jd93j3p9djqp9dkqp0/cdfbn-flkwen-dlkdlk-wdmqw
`

 I tried to run it against this repo I just created: https://github.com/HighWatersDev/secret-test.git

I also tried that regex against the Teams webhook in regex101.com and I get a match. But as usual, I must be doing something wrong here.

**Comment by nelenkov** [comment]
this seems to fix it, not sure if the best way, but it without this custom regexes don't get passed down to `find_string()`

```
diff --git a/truffleHog/truffleHog.py b/truffleHog/truffleHog.py
index 591c098..a6be3ee 100644
--- a/truffleHog/truffleHog.py
+++ b/truffleHog/truffleHog.py
@@ -90,7 +90,7 @@ def main():
                 path_exclusions.append(re.compile(pattern))
 
     output = find_strings(args.git_url, args.since_commit, args.max_depth, args.output_json, args.do_regex, do_entropy,
-            surpress_output=False, branch=args.branch, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions, allow=allow)
+            surpress_output=False, branch=args.branch, custom_regexes=regexes, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions, allow=allow)
     project_path = output["project_path"]
     if args.cleanup:
         clean_up(output)
```

**Comment by dxa4481** [comment]
Thanks, I just merged that change in. I'll do some testing and if that works, I'll cut a new release

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
