### ISSUE TITLE
Detect Slack workflows webhook

### ISSUE THREAD

**Issue by juliendoutre** [trufflesecurity/trufflehog#2571]
## Description
Slack allows users to trigger workflows from webhooks, as described in https://slack.com/intl/en-gb/help/articles/360041352714-Build-a-workflow--Create-a-workflow-that-starts-outside-of-Slack.

This works pretty much like for classic webhooks, Slack generates a secret URL that can be used to trigger the workflow. However the format is slightly different from the one detected by the current [Slack WebHook detector](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/slackwebhook/slackwebhook.go):
```shell
// Services webhook URL format
(https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]{23,25})
// Workflow webhook URL format
(https://hooks\.slack\.com/workflows/T[A-Z0-9]+/A[A-Z0-9]+/[0-9]{17,19}/[A-Za-z0-9]{23,25})
```

### Preferred Solution
Since [Slack WebHook detector](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/slackwebhook/slackwebhook.go) already covers a pretty similar secret pattern, I propose like it's the case for the [Slack Tokens detector](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/slack/slack.go), to extend its logic to support this new format.

#### References
* I drafted https://github.com/trufflesecurity/trufflehog/pull/2569 to implement the proposed solution.

**Comment by zricethezav** [comment]
closing as https://github.com/trufflesecurity/trufflehog/pull/2569 has been merged
