### ISSUE TITLE
Base64 decoder causing double findings

### ISSUE THREAD

**Issue by Opolor** [trufflesecurity/trufflehog#2574]
### TruffleHog Version

- trufflehog 3.67.4

### Trace Output

See trace output here: https://gist.github.com/Opolor/27be187bc6a8b8f13c4f5adb770ca026
### Expected Behavior

I would expect that only the PLAIN decoder detects the URI

### Actual Behavior

Both the BASE64 and PLAIN decoder detect this result.
Additionally, the decoders output different "Line" values for the same finding.

### Steps to Reproduce

 1. Create file containing (I called it reproducer.txt)
 ```
# specifying-the-class-of-an-ingress
http://admin:admin@127.0.0.1
 ```
 3. Run ` trufflehog --no-update filesystem reproducer.txt`
 5. See that both decoders appear and cause a finding to be outputted twice.

## Environment
 * OS: Windows WSL Ubuntu 22.04.3 LTS

**Comment by ahrav** [comment]
@Opolor Could you please run the scan again without --no-update to ensure you're using the most recent version? This [PR](https://github.com/trufflesecurity/trufflehog/pull/2671) should have fixed the issue. If you still encounter the problem, please let us know.
