### ISSUE TITLE
Process still running but no more output on large repository

### ISSUE THREAD

**Issue by stabla** [trufflesecurity/truffleHog#258]
**Describe the bug**
I have a project of a notable size (25 MB) and wanted to scan it with trufflehog. It seems that after a moment of scanning, Trufflehog is unable to continue and is stopping but the process still runs. Is there any reason for that? I have tried to reduce the scope by adding a patterns path but it doesn't solve the issue

Scanning continue, but no more output, no more data on terminal. Yet, process is still running. Any idea?

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6

**Comment by dxa4481** [comment]
It's probably just working its way through. For larger repos it can take some time to make it all the way through.
