### ISSUE TITLE
Exclusions by line number 

### ISSUE THREAD

**Issue by ejayt** [trufflesecurity/trufflehog#261]
**Is your feature request related to a problem? Please describe.**
Files may contain multiple issues and sometimes only (a) particular line(s) in a file should be excluded instead of the entire file. 

Here are the problems with exclusions at the file level: 
1. When an entire file is excluded, the file is no longer evaluated and secrets can be added after the fact.
2. Given a file, we may want to exclude one finding but not the other.

**Describe the solution you'd like**
To have the option to add a line number or line number range in addition to the file path in the exclude option. `--exclude path/to/file:17 path/to/other/file:45-60`. I understand that if changes occur to that file, those exclusions may no longer be valid, but that's fine– we would want to revisit the file to evaluate changes to see if it should still be excluded.

**Describe alternatives you've considered**
1. Manage and track changes to files that were given exclusions. If a file changes, then we would remove it from exclusions. Doesn't cover the case where we have multiple findings in one file and we want to exclude one but not the other.

2. Run trufflehog on excluded paths, save the list of findings into a file. If a previous list of findings exists, compare to see if there are differences or new findings. If there are no differences, we are clear to run it against the list of exclusions. This is not ideal in a CI/CD setting.

Note, this is in the context of using this within a CI/CD pipeline where exclusions are listed out as an environment variable.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

#22 should give equivalent functionality if it gets added.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
