### ISSUE TITLE
n00bidiot can't figure out how to make a list of test tokens for supported regexChecks.

### ISSUE THREAD

**Issue by adamplater** [trufflesecurity/trufflehog#263]
I am trying to make a bunch of fake tokens to run truffleHog over.

embarrassingly i am stuck at not being able to get it to detect a slack access token with entropy off

anyone able to give me a rundown or point me in the right direction?

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
