### ISSUE TITLE
Show Line Number

### ISSUE THREAD

**Issue by Jab2870** [trufflesecurity/trufflehog#264]
It would be super if, as well as the file path, the line number was shown for matches. The equivalent of the grep flag `--line-number`

**Describe the solution you'd like**
Include a line number with matches

**Describe alternatives you've considered**
Not sure what possible alternatives there are

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It supports line numbers!

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
