### ISSUE TITLE
False positives being reported in every run. What is the recommended approach to handle this?

### ISSUE THREAD

**Issue by impks27** [trufflesecurity/trufflehog#265]
False positives being reported in every run. What is the recommended approach to handle this?

I understand this may be out of scope but just reporting everything everytime does make the scan result lengthy. There are scan tools like fortify checkmarx which provide a portal for false positive review and whitelisting them. I do not see such a thing with trufflehog.

**Comment by dxa4481** [comment]
Hey @impks27 , we have a lot of features we're about to open source in the coming months that should address this.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
