### ISSUE TITLE
Go install not working - Must match format (WSL)

### ISSUE THREAD

**Issue by Dyst0rti0n** [trufflesecurity/trufflehog#2661]
### TruffleHog Version
`3.72.0`

### Expected Behavior

When `go install` is ran - for it to install all go packages and modules necessary. 

### Actual Behavior
```
go: errors parsing go.mod:
...trufflehog/go.mod:3: invalid go version '1.23.0': must match format 1.23
```

## Environment
 OS: Windows Subsystem for Linux (WSL)
 Version: WSL version: 2.1.5.0

### Fix
Alter *go.mod:3* from `go 1.22.0` -> `go 1.22`

**Comment by rgmz** [comment]
This seems like the exact opposite of #2639, unless I'm missing something. 🤔

**Comment by Dyst0rti0n** [comment]
Oh it does indeed, interesting... I wonder if there's a work around

**Comment by rgmz** [comment]
Unfortunately, the Go team seems to lock resolved issues, otherwise I would seek clarification about that suggestion.

Is this a known issue? Is there an obvious solution? Idk.

**Comment by Dyst0rti0n** [comment]
> Unfortunately, the Go team seems to lock resolved issues, otherwise I would seek clarification about that suggestion.
> 
> Is this a known issue? Is there an obvious solution? Idk.

The only solution I found was altering the version from 1.22.0 -> 1.22 so I'm not too sure

**Comment by h0bbl3s** [comment]
> Unfortunately, the Go team seems to lock resolved issues, otherwise I would seek clarification about that suggestion.

> Is this a known issue? Is there an obvious solution? Idk.

I believe the solution to this ticket and the other ticket referred to is to set go 1.22 and toolchain go1.22.0 in go.mod
I was having the same issue as @Dyst0rti0n but I think this will fix the go install and go build for this.

**Comment by rgmz** [comment]
For posterity, this seems to be a frustrating compatibility issue between versions of Go mod. Newer versions want x.x.x, older versions want x.x.

https://github.com/golang/go/issues/63370
