### ISSUE TITLE
Non-Zero exit code when secrets where found is not documented

### ISSUE THREAD

**Issue by nilsmahlstaedt** [trufflesecurity/trufflehog#267]
**Describe the bug**
When trufflehog finds a secret it will exit with an exit code of 1.
This feature was requested in #87 and implemented (see https://github.com/trufflesecurity/truffleHog/blob/dev/truffleHog/truffleHog.py#L98). But neither the Readme nor `--help` Output mention this behaviour.
It stumbled over it while trying to integrate trufflehog as part small tool to scan multiple Repo's in a git organisation.

**To Reproduce**
1. Run trufflehog over a repo with at least one secret found
2. observe exit code (e.g. `echo $?`)

**Expected behavior**
The documentation and preferably also the help page should mention that an exit code of 1 indicates that secrets were found.

**Desktop (please complete the following information):**
 - OS: Linux/WSL2
 - Related Code can be found in Main Branch (Readme and Exit Code line)

**Comment by retornam** [comment]
@nilsmahlstaedt  see #271

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
