### ISSUE TITLE
Feature: unified git diff context control

### ISSUE THREAD

**Issue by will-schneble** [trufflesecurity/trufflehog#269]
**Is your feature request related to a problem? Please describe.**
When using git-diff scanning with trufflehog, false positives can occur when a non-secret containing modification is within the git-diff context (3 lines before and after the modifications by default). For example:
```txt
text1
secret
text2
+text3
```  
Will trigger a finding by trufflehog even though the commit did not contain the addition/deletion of the secret. 

**Describe the solution you'd like**
GitPython `git.diff` supports all the command line options for `git-diff`. Thus add the `unified` kwarg to `git.diff` and `truffleHog.find_strings` methods. 

**Describe alternatives you've considered**
An alternative would be to check the diff or printDiff of each finding and eliminate findings where the stringsFound elements were not in an addition/deletion.

**Additional context**
[git-diff](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---unifiedltngt)
[GitPython git.diff](https://gitpython.readthedocs.io/en/stable/reference.html#git.diff.Diffable.diff)

Edit: mistakenly said `git.diff_worker` instead of `git.diff`.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
