### ISSUE TITLE
Any background on entropy detection sensitivity?

### ISSUE THREAD

**Issue by rbailey-godaddy** [trufflesecurity/trufflehog#275]
This question came up while working on [tartufo](https://github.com/godaddy/tartufo) entropy scanning.

Is there any background on how/why the default thresholds (4.5 for base64 and 3.0 for hex) were chosen? I'm especially interested in whether or not there are theoretical drivers for this choice, or if this was an empirical "seems to work" kind of thing.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
