### ISSUE TITLE
Postman not working?

### ISSUE THREAD

**Issue by marcelo321** [trufflesecurity/trufflehog#2753]
I  am not sure if it isn't working or I am doing something wrong.

```
trufflehog postman --workspace "linode" --token mytoken

2024-04-26T05:44:22Z    error   trufflehog      engine failed to finish execution       {"error": "fatal: error getting workspace linode: could not get workspace: linode"}
```

It says error getting workspace for any term I use, including paypal or any

**Comment by marcelo321** [comment]
I just created the key here:

![image](https://github.com/trufflesecurity/trufflehog/assets/29487296/9c20a953-a0e6-4bc3-a42e-f1b42671055c)

**Comment by dustin-decker** [comment]
I think you need to use the workspace ID instead. The flag could have been named more clearly.

**Comment by marcelo321** [comment]
@dustin-decker giving a exact workspace id also fails to me, can you give me an example of a workspace and what id would it use so I can try it?? would be appreciated

**Comment by marcelo321** [comment]
Ooh I see. Do you have any info on how the team was able to scrap ids when searching on the public workspaces..? I read the blog post which is great, but I am finding pretty difficult to understand the postman api. Not sure if you were part of that research or not

**Comment by dustin-decker** [comment]
I do not know the details of that part.

**Comment by zricethezav** [comment]
> Do you have any info on how the team was able to scrap ids when searching on the public workspaces

That's something we did internally and don't plan on releasing. Closing this issue as I believe the original issue has been answered.
