### ISSUE TITLE
AWS Session Key not being matched

### ISSUE THREAD

**Issue by domwhewell-sage** [trufflesecurity/trufflehog#2771]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
3.74.0

### Trace Output

https://gist.github.com/domwhewell-sage/66c6ce77f372d958dbbae7fdde4e6a0f

### Expected Behavior

Session Key is detected

### Actual Behavior

No secrets are detected

### Steps to Reproduce

 1. Paste a AWS session token into a .txt file
 2. Run `trufflehog filesystem <path_to_file>.txt` against it

## Environment
 * OS: Kali
 * Version 2023.3

## Additional Context
Looking at the regex in `awssessionkey.go`, the `sessionPAT` seems to not match the `==` from the session token

### References

N/A

**Comment by domwhewell-sage** [comment]
As suggested on slack I have run the commands mentioned here and cannot see any errors https://github.com/trufflesecurity/trufflehog/issues/2620#issuecomment-2032727625

I have added the result as a comment to my gist

**Comment by rgmz** [comment]
> As suggested on slack I have run the commands mentioned here and cannot see any errors https://github.com/trufflesecurity/trufflehog/issues/2620#issuecomment-2032727625

The lack of those print statements mean that it's not being picked up by the detector at all. This indicates that there's an error with the keywords, pattern, or perhaps the verification overlap change (#2356, https://github.com/trufflesecurity/trufflehog/issues/2515#issuecomment-1967449011).

**Comment by domwhewell-sage** [comment]
If it helps the regex [here](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/awssessionkeys/awssessionkey.go#L59) works for session tokens obtained via `aws sts get-session-token` but does not work for session tokens obtained from `aws sts assume-role`

**Comment by rgmz** [comment]
Hopefully this was fixed by https://github.com/trufflesecurity/trufflehog/pull/3583.

**Comment by domwhewell-sage** [comment]
Thanks @rgmz that has worked now!
