### ISSUE TITLE
Requesting manual verification instructions

### ISSUE THREAD

**Issue by Dark-Aura** [trufflesecurity/trufflehog#2806]
Hi Team,

I have been using Trufflehog for the past year. However, I'm facing a few obstacles, and I believe taking certain actions would be helpful for us.

Currently, when I run Trufflehog with the "--verified" flag, it provides some verified results. However, if it detects a few issues, I would like to rerun specific detectors, such as "Postgres" or "Infura", with debug mode or through a proxy to double-check.

I suggest you add the following features in the new update:

Once I have used "--verified" I need to report to someone, I require steps to reproduce. for that, I would request you to add these Feature Requests:

1. Debug, verbose, or proxy mode: I want to capture and check in Burp Suite how Trufflehog requests that specific detector or through CLI (verbose).
2. Specific detector double-check

Adding these features would be very helpful for us.

**Comment by Dark-Aura** [comment]
this image for Infura, I can check this code and re-execute it and report to the appropriate team, ![image](https://github.com/trufflesecurity/trufflehog/assets/65353593/ee7ba58e-ee31-43d0-9993-b872f78cd0a5)

![image](https://github.com/trufflesecurity/trufflehog/assets/65353593/47e1d55f-f5aa-4ecf-bed2-dd58355d46e3)
But in this code, I'm unable to find how to validate "Postgres", that's why I suggested it.

**Comment by dustin-decker** [comment]
For now, I suggest trying to set the HTTP_PROXY and HTTPS_PROXY variables to point to burp. You will then be able to see what requests are made for reproduction.

**Comment by Dark-Aura** [comment]
Thank you for your reply.

I haven't seen the HTTP_PROXY flag in the help menu, but I tried setting it anyway based on your instructions. I've tried setting the HTTP_PROXY variable as instructed, but I'm still getting an error. Could you please provide the exact command to fix this, or guide me through the steps? 

For your reference here I'm attaching the screenshot

![image](https://github.com/trufflesecurity/trufflehog/assets/65353593/eec24d0b-7bf4-480a-b405-9b5d271f0ca5)
