### ISSUE TITLE
go install does not work

### ISSUE THREAD

**Issue by sssseossss** [trufflesecurity/trufflehog#283]
**Describe the bug**
Thanks for the cool tool! Much appreciated!
The command you have listed for go install is not working and outputs errror.

**To Reproduce**
trying the following in latest Kali WSL.

`└─$ go install github.com/trufflesecurity/trufflehog.git@latest                                                         go install: github.com/trufflesecurity/trufflehog.git@latest: invalid version control suffix in github.com/ path`
or:
`└─$ go install github.com/trufflesecurity/trufflehog@latest                                                             go install: github.com/trufflesecurity/trufflehog@latest: module github.com/trufflesecurity/trufflehog@latest found (v3.0.0-rc3+incompatible), but does not contain package github.com/trufflesecurity/trufflehog   `

**Expected behavior**
Installed.

**Comment by dustin-decker** [comment]
Thanks for the report, fixed by #285

```
git clone https://github.com/trufflesecurity/trufflehog.git

cd trufflehog; go install
```
