### ISSUE TITLE
"syntax error" while processing a file

### ISSUE THREAD

**Issue by rohitn** [trufflesecurity/trufflehog#2877]
### TruffleHog Version
`trufflehog --version`
trufflehog 3.76.3

### Trace Output
Invocation
`trufflehog git --no-update --no-verification --trace -j file:///data/REDACTED  > ~/trufflehog.json 2> ~/log.txt`

From log.txt

> 2024-05-23T02:09:30Z    error   trufflehog      error processing AR files       {"source_manager_worker_id": "awK83", "unit": "/data/REDACTED", "unit_kind": "dir", "commit": "1f3cb90", "path": "REDACTED/FpwLib.lib", "timeout": 30, "error": "error reading AR payload: strconv.Atoi: parsing \"\": invalid syntax"}

### Expected Behavior
No errors

### Actual Behavior
"invalid syntax" error

### Steps to Reproduce

 It is a private repository so I cannot provide steps to reproduce

## Environment
 * OS: Ubuntu
 * Version 22.04.4 LTS

**Comment by rgmz** [comment]
Source:

1. https://github.com/paultag/go-debian/blob/246d63d4a8289011dff5db890058a7d9403f785a/deb/ar.go#L107
2. https://github.com/paultag/go-debian/blob/246d63d4a8289011dff5db890058a7d9403f785a/deb/ar.go#L153
3. https://github.com/paultag/go-debian/blob/246d63d4a8289011dff5db890058a7d9403f785a/deb/ar.go#L89
4. https://github.com/trufflesecurity/trufflehog/blob/1441289d410e0918eddd9f749bdcd37cd14be944/pkg/handlers/ar.go#L74-L80

**Comment by rgmz** [comment]
I opened a pull request for this in the upstream library: https://github.com/paultag/go-debian/pull/130.

**Comment by rgmz** [comment]
> I opened a pull request for this in the upstream library: [paultag/go-debian#130](https://github.com/paultag/go-debian/pull/130).

@ahrav Is there an optimal field order for `string`, `*int64`? 
https://github.com/paultag/go-debian/blob/0efa67c1a811c738589ad900ef2ff8c6a4fed9c8/deb/ar.go#L131-L134

**Comment by ahrav** [comment]
> > I opened a pull request for this in the upstream library: [paultag/go-debian#130](https://github.com/paultag/go-debian/pull/130).
> 
> @ahrav Is there an optimal field order for `string`, `*int64`? https://github.com/paultag/go-debian/blob/0efa67c1a811c738589ad900ef2ff8c6a4fed9c8/deb/ar.go#L131-L134

Either order should have the same effect. Personally, I prefer the string first in this case (how you have it), but both should work fine.

Thanks for tracking this down. 🙇

**Comment by ahrav** [comment]
This reminds me, there was also an issue with the rpmutils package causing an IOOR panic. I temporarily band-aided with a `recover`, but I should submit a proper fix upstream. 😅

**Comment by rgmz** [comment]
No movement on the PR yet. It may end up being necessary to fork it to avoid this common and annoying error.
