### ISSUE TITLE
Check CODEOWNER files for contacts 

### ISSUE THREAD

**Issue by SadFaceSmith** [trufflesecurity/trufflehog#288]
**Is your feature request related to a problem? Please describe.**
Having to match up results with relevant contact info from CODEOWNER files is cumbersome. 
**Describe the solution you'd like**
It would be fantastic if trufflehog automatically provided contact info for results based on the listed contacts in CODEOWNER files.

**Describe alternatives you've considered**
Manually scripting with bash+sed+awk is painful and does not scale well. 

**Additional context**

**Comment by zricethezav** [comment]
Interesting feature request but we don't plan on adding this feature.
