### ISSUE TITLE
Crawl sites for js files and scan those for apikeys

### ISSUE THREAD

**Issue by wellenc-lex** [trufflesecurity/trufflehog#290]
It would be cool if we can pass something like
-url ‘urllistfile’ or httpx | Trufflehog 

so the tool would crawl domain for .js, .js.map files and search credentials in there

**Comment by dustin-decker** [comment]
You might enjoy https://github.com/trufflesecurity/Trufflehog-Chrome-Extension for now. It doesn't support verification or all of the detectors but we have found some keys with it.

**Comment by zricethezav** [comment]
While this feature could be useful, we don't plan on supporting a crawler in TruffleHog. As an alternative, you could use the chrome extension or curl files locally then run trufflehog on those files.
