### ISSUE TITLE
Allow terminal output and JSON file output simultaniously

### ISSUE THREAD

**Issue by ElvenSpellmaker** [trufflesecurity/trufflehog#297]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to output to a JSON file, and also to the terminal in the normal format.

**Describe the solution you'd like**
When running Trufflehog in a Pipeline we'd like the main output of Trufflehog to be written to the build log, but also a JSON file to save as an artefact.
E.g.
`trufflehog git file:///${CI_PROJECT_DIR} --json trufflehog-report.json --concurrency=4`

**Describe alternatives you've considered**
Currently we run the command twice, which isn't very efficient, once with `--json` and once without.

**Comment by zricethezav** [comment]
We don't plan on supporting json file output. You can use `--json` with `jq` as a solution.

**Comment by ElvenSpellmaker** [comment]
@zricethezav That doesn't solve the problem?

**Comment by zricethezav** [comment]
@ElvenSpellmaker We don't plan on supporting this feature, sorry

**Comment by zricethezav** [comment]
@ElvenSpellmaker 
```
trufflehog git file:///${CI_PROJECT_DIR} --json | jq -s . > out.json
```
Should do the trick

**Comment by ElvenSpellmaker** [comment]
Hey @zricethezav, thanks for the snippet, but sadly that only outputs the JSON to a file, not to the terminal also.
You can already output to a JSON without jq by doing, `trufflehog git file:///${CI_PROJECT_DIR} --json > out.json`.

JSON isn't very human readable and the pipeline build log kinda needs to be so, with the JSON output for other tools to ingest.

We'll just have to continue to run this twice, or wait for it to perhaps be supported one day, thanks though 🙂
