### ISSUE TITLE
Please update wasilibs/go-re2 to the latest release 

### ISSUE THREAD

**Issue by yurivict** [trufflesecurity/trufflehog#3006]
This fixes this build failure:
```
vendor/github.com/wasilibs/go-re2/internal/alloc/alloc.go:58:16: undefined: syscall.Mprotect
vendor/github.com/wasilibs/go-re2/internal/alloc/alloc.go:80:18: undefined: syscall.Mprotect
```

### TruffleHog Version
3.78.2

## Environment
 * OS: FreeBSD 14.1
 * Version 3.78.2

**Comment by ahrav** [comment]
Sorry about that @yurivict not sure why we didn't get a dependency update until just now.
