### ISSUE TITLE
List of Verifiers and Verifier endpoints for trufflehog

### ISSUE THREAD

**Issue by arjunharidasp** [trufflesecurity/trufflehog#3013]
## Description
We have seen the verifier option in the trufflehog command line that helps to verify the validity of the detected secrets

We would like to know whether the verification mechanism is implemented for all the detectors you are having

### Preferred Solution
If Trufflehog team can publish the list of detectors which also support the verifiers

publishing a list of available verifiers and validation endpoints will be very useful

**Comment by zricethezav** [comment]
We don't plan on supporting that. You can manually do that by writing a script looking at the files in the `pkg/detectors` package.
