### ISSUE TITLE
GCP and GCPApplicationDefaultCredentials Detector doesnt work on .db files

### ISSUE THREAD

**Issue by ankushgoel27** [trufflesecurity/trufflehog#3056]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version
dev - latest 

Issue:

Gcloud stores all credentials in files called credentials.db or access_tokens.db. These are database files and are stored in ~/.config/gcloud directory by default.
The GCP and GCPApplicationDefaultCredentials detectors work fine when the credentials are in a .json or .txt file and are properly formated but they fail to detect the same credentials when stored in a .db file

I guess the detectors need to properly open and read the .db file which they are unable to do and currently read them as a text file which contains a lot of gibberish along with valid credentials.

**Comment by dxa4481** [comment]
I believe this is a dup of #2095
