### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by sa7mon** [trufflesecurity/trufflehog#312]
**Is your feature request related to a problem? Please describe.**
Not able to scan an organization in GitHub Enterprise instance

**Describe the solution you'd like**
A `--github-url` or similar flag to specify the base URL of a GitHub instance so when you do `--org` it looks at the correct URL.

**Comment by bill-rich** [comment]
The use case you're describing is actually already supported! You should be able to use the `--endpoint` flag to point to a different URL.

For example:
`trufflehog github --endpoint https://api.my-internal-endpoint --token sometoken --org my-org`
