### ISSUE TITLE
Can't build due to lzip-go repo having vanished

### ISSUE THREAD

**Issue by h0bbl3s** [trufflesecurity/trufflehog#3227]
### TruffleHog Version
I've been having issues building TruffleHog for days, I've pulled the git master branch several times, as well as tried the last release source code.

### Trace Output

I cannot get trufflehog built to run it.

### Expected Behavior

Trufflehog should build and install

### Actual Behavior

No matter which build or version I tried to build the dependency lzip-go cannot download.

### Steps to Reproduce
 
either extract latest source release, or clone master git branch
cd into trufflehog dir
go install

## Environment
 * OS: Fedora
 * Version 40

## Additional Context

I checked after the first time this happened a few days ago, and the repository for https://github.com/sorairolake/lzip-go/ gives me a 404. Also on https://pkg.go.dev/github.com/sorairolake/lzip-go the package is listed as having a missing repo or being unavailable. 

I guess what I want to know is has anyone else run into this? Do we know anything about this or is there a workaround?

**Comment by rgmz** [comment]
This is bizarre. Either the user deleted their account or were suspended by GitHub statff.

**Comment by polarathene** [comment]
The repo was restored. I've heard of cases where GH automation mistakenly takes down repos/accounts, perhaps that happened?
