### ISSUE TITLE
trufflehog filesystem . results in error message "unrecognized arguments"

### ISSUE THREAD

**Issue by webpwnized** [trufflesecurity/trufflehog#3268]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

The trufflehog version command is not working as expected. 

```
$ trufflehog --version
usage: trufflehog [-h] [--json] [--regex] [--rules RULES] [--allow ALLOW] [--entropy DO_ENTROPY]
                  [--since_commit SINCE_COMMIT] [--max_depth MAX_DEPTH] [--branch BRANCH]
                  [-i INCLUDE_PATHS_FILE] [-x EXCLUDE_PATHS_FILE] [--repo_path REPO_PATH] [--cleanup]
                  git_url
trufflehog: error: the following arguments are required: git_url
```
### Trace Output

The documentation located at URL states to run the filesystem capability using the following

`trufflehog filesystem path/to/file1.txt path/to/file2.txt path/to/dir
`

When running the filesystem feature, the following occurs

$ **trufflehog filesystem .**
usage: trufflehog [-h] [--json] [--regex] [--rules RULES] [--allow ALLOW] [--entropy DO_ENTROPY]
                  [--since_commit SINCE_COMMIT] [--max_depth MAX_DEPTH] [--branch BRANCH]
                  [-i INCLUDE_PATHS_FILE] [-x EXCLUDE_PATHS_FILE] [--repo_path REPO_PATH] [--cleanup]
                  git_url
**trufflehog: error: unrecognized arguments: .**

### Expected Behavior

Trufflehog would scan the files located in the current directory

### Actual Behavior

An error message appeared: **trufflehog: error: unrecognized arguments: .**

### Steps to Reproduce

1. Install trufflehog on Ubuntu following the instructions in the documentation. The documentation is located at [https://github.com/trufflesecurity/trufflehog/blob/main/README.md#8-scan-individual-files-or-directories](https://github.com/trufflesecurity/trufflehog/blob/main/README.md#8-scan-individual-files-or-directories). As as example for illustration, run the following command

`curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
`

2. Run the command per the instructions in the documentation. The documentation is located at [https://github.com/trufflesecurity/trufflehog/blob/main/README.md#8-scan-individual-files-or-directories](https://github.com/trufflesecurity/trufflehog/blob/main/README.md#8-scan-individual-files-or-directories).

`trufflehog filesystem .
`
## Environment
 * OS: 
 * Distributor ID:	Ubuntu
 * Description:	Ubuntu 24.04.1 LTS
 * Release:	24.04
 * Codename:	noble
 * Ubuntu Linux ubuntu-cloud 6.8.0-41-generic #41-Ubuntu SMP 
 * x86_64 GNU/Linux

**Comment by rgmz** [comment]
> Install trufflehog on Ubuntu following the instructions in the documentation. The documentation is located at https://github.com/trufflesecurity/trufflehog/blob/main/README.md#8-scan-individual-files-or-directories. As as example for illustration, run the following command

Do you have any output from this script?

It appears that you somehow downloaded the deprecated v2 instead of the new v3.

**Comment by webpwnized** [comment]
I apologize. I do not have the output. It may be that I have an older version installed, and the script was not able to install the new version because the old version was already present.

**Comment by panospapako** [comment]
Good evening, I have the same problem with v3.82.1. 
I tried it on Windows with [trufflehog_3.82.1_windows_amd64.tar.gz](https://github.com/trufflesecurity/trufflehog/releases/download/v3.82.1/trufflehog_3.82.1_windows_amd64.tar.gz) and on WSL (Ubuntu) with [trufflehog_3.82.1_linux_amd64.tar.gz](https://github.com/trufflesecurity/trufflehog/releases/download/v3.82.1/trufflehog_3.82.1_linux_amd64.tar.gz).

This is the output from both OS:

```
trufflehog filesystem .
usage: trufflehog [-h] [--json] [--regex] [--rules RULES] [--allow ALLOW] [--entropy DO_ENTROPY]
                  [--since_commit SINCE_COMMIT] [--max_depth MAX_DEPTH] [--branch BRANCH] [-i INCLUDE_PATHS_FILE]
                  [-x EXCLUDE_PATHS_FILE] [--repo_path REPO_PATH] [--cleanup]
                  git_url
trufflehog: error: unrecognized arguments: .
```
