### ISSUE TITLE
Expose User-Agent customization via CLI or config

### ISSUE THREAD

**Issue by ktranSC** [trufflesecurity/trufflehog#3345]
## Description
Hi folks, just saw an update to enable custom User Agent suffix: https://github.com/trufflesecurity/trufflehog/pull/3297
Is there anyway to expose that customization via CLI argument?  Allowing custom User Agent would be helpful to triage verification attempts in audit logs.

**Comment by CameronLonsdale** [comment]
Keen for this!

**Comment by ahrav** [comment]
@dustin-decker is this something we can wire up relatively easily based on the work you did?

**Comment by ahrav** [comment]
> @ahrav I've made a PR for it here #3359 to add to CLI args.

Thanks again for the contribution. This should be out with the next release.

**Comment by ktranSC** [comment]
@ahrav thanks for the speedy approval 🙏
