### ISSUE TITLE
Expose Detector Description in JSON output

### ISSUE THREAD

**Issue by CameronLonsdale** [trufflesecurity/trufflehog#3380]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

## Description
Expose the new Description field via the JSON output.

### Preferred Solution
```
{
...
"DetectorName": "OpenAI",
"Description": "OpenAI provides various AI models and services. The API keys can be used to access and interact with these models and services.",
...
}
```

**Comment by kashifkhan0771** [comment]
This seems like a valuable feature.
### Proposed Approach:

I’m considering adding a Description field to the JSONPrinter struct [here](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/output/json.go#L27) and to the Result struct in detectors [here](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/detectors.go#L87). This would allow us to include descriptions for any detector results.

Do you think this approach makes sense? Alternatively, @mcastorina suggested that we could expose the entire detector object within the struct instead.

@zricethezav @abasit-folio3
