### ISSUE TITLE
Issues in pattern detection logic for AeroWorkFlow

### ISSUE THREAD

**Issue by sahil9001** [trufflesecurity/trufflehog#3432]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### Expected Behavior
The current API key pattern should match the pattern required.

### Actual Behavior
The` \b` at the end of the regex is looking for a word boundary. In this case, the 20-character sequence is immediately followed by a `/`, which is not a word character. The word boundary `\b` is expecting a transition from a word character to a non-word character or the end of the string, which doesn't occur here.

## Environment
 * OS: [e.g. iOS]
 * Version [e.g. 22]

### References

* #0000

**Comment by zricethezav** [comment]
> The \b at the end of the regex is looking for a word boundary. In this case, the 20-character sequence is immediately followed by a /, which is not a word character. The word boundary \b is expecting a transition from a word character to a non-word character or the end of the string, which doesn't occur here.

@sahil9001 Could you provide an example regex101 demonstrating this? I'm not following.

**Comment by sahil9001** [comment]
A valid pattern which doesn't match, 
![Uploading Screenshot 2024-10-17 at 1.02.13 AM.png…]()

**Comment by sahil9001** [comment]
Closing this, addressed here #3434
