### ISSUE TITLE
Issue with validation logic for `carboninterface`

### ISSUE THREAD

**Issue by sahil9001** [trufflesecurity/trufflehog#3485]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### Expected Behavior
API Key regex pattern should be matched to 22 characters, as that is the API pattern from carbon interface now.
<img width="1415" alt="Screenshot 2024-10-20 at 1 26 26 AM" src="https://github.com/user-attachments/assets/603f8371-0785-4223-8b13-de5123daf1df">

### Actual Behavior
Currently, tests fail because of incorrect API Key validation of 21 characters.

<img width="1421" alt="Screenshot 2024-10-20 at 1 26 12 AM" src="https://github.com/user-attachments/assets/5080fc7f-2ef9-4c54-98ae-89b7e40091e8">

## Environment
 * OS: [e.g. iOS]
 * Version [e.g. 22]

### References

* #0000

**Comment by abmussani** [comment]
@sahil9001 I could not find any way to revoke API key. The one you shared is giving Access Denied. is this redacted version ? Along with that I signed up new account and the key I got is 21 characters long. Are you sure that they have changed the pattern of Key?

**Comment by sahil9001** [comment]
@abmussani Well it's weird, I have 22 character API Key and it works like a charm!

And also, I had changed the character for security reasons, I am attaching the postman request here. 


<img width="1309" alt="Screenshot 2024-10-21 at 4 11 06 PM" src="https://github.com/user-attachments/assets/2cb2bc46-f897-4eac-8744-9a1bcb5179f2">

**Comment by sahil9001** [comment]
> Are you sure that they have changed the pattern of Key?


Yes, I guess that is why my API tests passed too 🤔

**Comment by sahil9001** [comment]
Closing issue as Hacktoberfest doesn't require opening issues
