### ISSUE TITLE
Support additional Doppler auth token formats

### ISSUE THREAD

**Issue by Piccirello** [trufflesecurity/trufflehog#349]
Trufflehog currently supports scanning for Doppler personal tokens. Doppler supports various other token types that we'd love to see included. All token formats are documented at the link below. Lmk if I can assist with this in some way.

https://docs.doppler.com/reference/auth-token-formats

**Comment by zricethezav** [comment]
closing as https://github.com/trufflesecurity/trufflehog/pull/2329 takes care of this
