### ISSUE TITLE
Binary false negatives because UTF-8 decoder removes non-printable characters

### ISSUE THREAD

**Issue by rgmz** [trufflesecurity/trufflehog#3585]
The UTF-8 decoder removes non-printable characters such as `\u000` (null). This results in binary files having a large number of false negatives.

**Without UTF-8 Decoder**
The text is separated and `\b` doesn't result in false negatives.
```
/private/tmp/com.apple.launchd.Jj7XaKWEYz/Listeners\ufffd\ufffd\ufffd\ufffd\ufffdSTORAGE_ACCESS_KEY_ID\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0003\ufffd\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\ufffd\ufffdAKIAJTQJLQSCJMNBT3OD\ufffd\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\ufffdAKIAJTQJLQSCJMNBT3OD\ufffd\ufffd\ufffd\ufffd\ufffd
```

**With UTF-8 Decoder**
The text is concatenated into a single large string and `\b` results in false negatives.
```
/private/tmp/com.apple.launchd.Jj7XaKWEYz/ListenersSTORAGE_ACCESS_KEY_IDAKIAJTQJLQSCJMNBT3ODAKIAJTQJLQSCJMNBT3OD
```

Edit: related to #3223.

**Comment by rgmz** [comment]
Another issue is that `github.com/wasilibs/go-re2` [explicitly stops reading input when it encounters an unexpected value](https://github.com/wasilibs/go-re2?tab=readme-ov-file#behavior-differences). Such results are only accurately detected using the stdlib `regexp` package.

> Invalid utf-8 strings are treated differently. The standard library silently replaces invalid utf-8 with the unicode replacement character. This library will stop consuming strings when encountering invalid utf-8.

**Comment by ahrav** [comment]
Working on a potential [fix](https://github.com/trufflesecurity/trufflehog/pull/3588)

**Comment by rgmz** [comment]
> Working on a potential [fix](https://github.com/trufflesecurity/trufflehog/pull/3588)

Works well for my reproducer.

**Comment by ahrav** [comment]
> > Working on a potential [fix](https://github.com/trufflesecurity/trufflehog/pull/3588)
> 
> Works well for my reproducer.

Thanks for giving it a test. 🙇
