### ISSUE TITLE
# trufflehog:ignore doesn't work in some cases

### ISSUE THREAD

**Issue by WillGibson** [trufflesecurity/trufflehog#3602]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

```
➜ trufflehog --version                                                              
trufflehog 3.83.6
```

### Trace Output

https://gist.github.com/WillGibson/536034c94cce64b30e21cfbfe5d04742

### Expected Behaviour

```
➜ trufflehog filesystem . --no-verification --fail
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2024-11-14T07:35:30Z    info-0  trufflehog      running source  {"source_manager_worker_id": "59XZa", "with_units": true}
2024-11-14T07:35:30Z    info-0  trufflehog      finished scanning       {"chunks": 1, "bytes": 188, "verified_secrets": 0, "unverified_secrets": 0, "scan_duration": "1.409666ms", "trufflehog_version": "3.83.6"}
➜ 
```

### Actual Behaviour

```
  ➜ trufflehog filesystem . --no-verification --fail                                  
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2024-11-14T07:33:43Z    info-0  trufflehog      running source  {"source_manager_worker_id": "P8h7w", "with_units": true}
Found unverified result 🐷🔑❓
Detector Type: Postgres
Decoder Type: PLAIN
Raw result: postgresql://master_user:master_password@hostname:1234
Sslmode: <unset>
File: example_false_positive.py
Line: 1

2024-11-14T07:33:43Z    info-0  trufflehog      finished scanning       {"chunks": 1, "bytes": 240, "verified_secrets": 0, "unverified_secrets": 1, "scan_duration": "2.711ms", "trufflehog_version": "3.83.6"}
Exit code: 183 ➜ 
```

### Steps to Reproduce

 1. Drop the following file into an empty directory...
```
# tests/example_false_positive.py

def test_something():
    connection_string = "who-cares"

    # Ignoring this does not work
    assert connection_string == "postgres://master_user:master_password@hostname:1234/main"  # trufflehog:ignore
```
 4. Run `trufflehog filesystem . --no-verification --fail`
 5. See the error in the output

## Environment

 * OS: MacOS
 * Version: 15.1

## Additional Context

Nothing to add.

### References

Nothing to add.

**Comment by ahrav** [comment]
The issue appears to arise from the `postgres` detector manually setting the `raw` value to `postgresql`, even when the actual connection string begins with `postgres` ([reference](https://github.com/trufflesecurity/trufflehog/blob/3d3fd713c4c837dd773424f58fc98e277dce891e/pkg/detectors/postgres/postgres.go#L103)). Consequently, when attempting to [separate](https://github.com/trufflesecurity/trufflehog/blob/3d3fd713c4c837dd773424f58fc98e277dce891e/pkg/engine/engine.go#L1237) the `raw` value from the chunk, `bytes.Cut` returns `found` as `false`.

**Comment by ahrav** [comment]
Thanks for creating the issue @WillGibson.

**Comment by WillGibson** [comment]
Thanks for picking up the bug fix so quickly @ahrav!

**Comment by WillGibson** [comment]
Can confirm it's fixed. Thanks @ahrav.
