### ISSUE TITLE
Are the 5 releases per night really necessary?

### ISSUE THREAD

**Issue by kbaikov** [trufflesecurity/trufflehog#362]
**Describe the bug**
Please stop doing so many releases per night. Each containing one change?
If someone is subscribed to watch your repor releases in github, this gets really anoying.

**Expected behavior**
One release per night containing multiple changes.

**Comment by bolshoytoster** [comment]
@dustin-decker

**Comment by dustin-decker** [comment]
Sorry for the flood. We had a major release recently and there were a number of bug fixes and features dropped in the first week. Expect a lower frequency of releases going forward. Please check out v3 when you get a chance!
