### ISSUE TITLE
How can use regex with filesystem?

### ISSUE THREAD

**Issue by secureITmania** [trufflesecurity/trufflehog#363]
I am trying to pass my custom regex with the filesystem but the "--regex" argument is not working with the "filesystem".

**Comment by bolshoytoster** [comment]
@secureITmania [it looks like `--regex` is deprecated:](https://github.com/trufflesecurity/trufflehog#usage)
https://github.com/trufflesecurity/trufflehog/blob/37fce75c4a407aac4c2bc17e5d78fe1a212de974/main.go#L55

And it looks like it only worked with git anyway.

I'm not sure why it was disabled, but I could see if I can implement it with filesystem if there's no reason not to.

Sidenote, if you're on linux you could just run `grep -r $REGEX $DIR` to search  a `$DIR`ectory `-r`ecursively.

**Comment by dustin-decker** [comment]
In v2  the regex flag did this:

```--regex               Enable high signal regex checks```

The equivalent in v3 are the 600+ detectors with verifiers which are enabled by default.
