### ISSUE TITLE
Algolia detector now considers invalidated admin API keys as verified secrets

### ISSUE THREAD

**Issue by SamyDjemai** [trufflesecurity/trufflehog#3648]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### TruffleHog Version

```
trufflehog 3.84.0
```
### Trace Output

The trace output is 247MB and contains sensitive data, ask me if you need more information.

### Expected Behavior

Invalidated Algolia Admin API keys shouldn't be considered a verified secret

### Actual Behavior

Invalidated Algolia Admin API keys are considered a verified secret

### Steps to Reproduce

 1. Install Trufflehog 3.84.0
 2. Put your Algolia admin API key in a text file
 3. Scan it using Trufflehog: the secret shows up as verified
 4. Go to the Algolia console and regenerate the admin API key, which invalidates the previous API key
 5. Scan your text file using Trufflehog again: the secret still shows up as verified

## Environment
 * OS: Ubuntu
 * Version: 22.04

### References

* #3613 seem to introduce the issue. We see this because the issue occurs since v3.84.0. It seems especially linked to the following lines that were introduced [here](https://github.com/trufflesecurity/trufflehog/pull/3613/files#diff-fa35cd76f44e83e649d437ec83c3e681821006143d43322de285ad847d07dce7R140-R142):
```go
        case http.StatusForbidden:
		// Key is valid but lacks permissions.
		return true, nil, nil
``` 

Trying to use the API with `curl` and the invalidated admin API key returns a HTTP 403 status code, which seems to trigger the secret validator.

**Comment by rgmz** [comment]
Apologies, that seems to have been a mistake when consolidating the two functions.

Out of curiosity, whats the response body that accompanies the 403?

**Comment by SamyDjemai** [comment]
> Apologies, that seems to have been a mistake when consolidating the two functions.
> 
> Out of curiosity, whats the response body that accompanies the 403?

Here's the response body:
```
{"message":"Invalid Application-ID or API key","status":403}
```
