### ISSUE TITLE
Any recommendations for effective website-git repository finder tool

### ISSUE THREAD

**Issue by honphilemon** [trufflesecurity/trufflehog#365]
Please any recommendations for effective website-git repository finder tool

**Comment by dustin-decker** [comment]
Are you talking about a tool that finds .git directories available on websites? I believe https://github.com/trufflesecurity/Trufflehog-Chrome-Extension does that but the we have not ported the new scanning engine to it yet, and it only checks websites as you browse.

**Comment by honphilemon** [comment]
You mean it checks website with .git directory. Cause that's exactly what I want.

**Comment by dustin-decker** [comment]
Yes, it does

**Comment by honphilemon** [comment]
Thanks for your kind recommendations.
