### ISSUE TITLE
JiraToken v1: strange email match

### ISSUE THREAD

**Issue by rgmz** [trufflesecurity/trufflehog#3698]
The JiraToken v1 detector seems to have faulty matching for the email.
https://github.com/trufflesecurity/trufflehog/blob/fe6773ea43e63700f29426c89e861aac85f0ba72/pkg/detectors/jiratoken/v1/jiratoken.go#L56-L60

For instance, this includes `+\n'"` in the email prefix.
```
Found unverified result 🐷🔑❓
Verification issue: lookup addons.cdn.mozilla: no such host
Detector Type: JiraToken
Decoder Type: PLAIN
Raw result: +
	'"commentanywhere@commentanywhere.org:b992a9c4-8f18-47e4-b908-:addons.cdn.mozilla
Rotation_guide: https://howtorotate.com/docs/tutorials/atlassian/
Version: 1
Commit: cc7dfb04892445d4eb593a252b5ca66be2fbbfac
File: src/amoDataCsv.js
Line: 3005
Link: https://github.com/mozilla/preparatory-survey-for-naar-study-addon/blob/cc7dfb04892445d4eb593a252b5ca66be2fbbfac/src/amoDataCsv.js#L3005
Repository: https://github.com/mozilla/preparatory-survey-for-naar-study-addon.git
Timestamp: 2019-06-20 08:26:17 +0000
```

---

Tangentially related to https://github.com/trufflesecurity/trufflehog/pull/2746#issuecomment-2079406298, I still don't know what this logic is trying to accomplish.

**Comment by kashifkhan0771** [comment]
I tried this endpoint `https://"+domain+"/rest/api/3/dashboard` with our JIRA domain without any authentication and it returned 200 😅

**Comment by rgmz** [comment]
Closing this in favour of #3818.
