### ISSUE TITLE
Web resource search for secrets 

### ISSUE THREAD

**Issue by sssseossss** [trufflesecurity/trufflehog#375]
**Is your feature request related to a problem? Please describe.**
Hi!, thanks for the awesome tool. I have a feature request:
could trufflehog have a feature to scan the remote resources for secrets, i.e. you provide a bunch of links and it just scans those web resources for secrets, e.g. http://example.com/secrets.js
ATM I'm downloading the contents and then searching as a filesystem, but the feature would make it more convenient.
Thanks!

**Comment by zricethezav** [comment]
We don't plan on supporting this feature natively in TruffleHog. However you can `curl` web resources into a directory then run trufflehog on that directory as a solution
