### ISSUE TITLE
Last matched custom regex incorrect

### ISSUE THREAD

**Issue by cfkirby** [trufflesecurity/trufflehog#3774]
### TruffleHog Version

trufflehog 3.86.1

### Trace Output

https://gist.github.com/cfkirby/9116ab886ed2dc1c743a7164d3084744

### Expected Behavior

The match on line 2 should have caught the entire string, i.e.:
```
secret2abcdefghijmagic-bin64-stringabcdefghij1abcdefghij2abcdefghij3abcdefghij4abcdefghij5abcdefghij6abcdefghij7abcdefghij8abcdefghij9abcdefghij10abcdefghij11abcdefghij12abcdefghij13abcdefghij14abcdefghij15abcdefghij16abcdefghij17abcdefghij18abcdefghij19abcdefghij20abcdefghij21abcdefghij22abcdefghij23abcdefghij24abcdefghij25abcdefghij26abcdefghij27abcdefghij28abcdefghij29abcdefghij1abcdefghij2abcdefghij3abcdefghij4abcdefghij5abcdefghij6abcdefghij7abcdefghij8abcdefghij9abcdefghij10abcdefghij11abcdefghij12abcdefghij13abcdefghij14abcdefghij15abcdefghij16abcdefghij17abcdefghij18
```

### Actual Behavior

The match on line 2 got cut off early:
```
secret2abcdefghijmagic-bin64-stringabcdefghij1abcdefghij2abcdefghij3abcdefghij4abcdefghij5abcdefghij6abcdefghij7abcdefghij8abcdefghij9abcdefghij10abcdefghij11abcdefghij12abcdefghij13abcdefghij14abcdefghij15abcdefghij16abcdefghij17abcdefghij18abcdefghij19abcdefghij20abcdefghij21abcdefghij22abcdefghij23abcdefghij24abcdefghij25abcdefghij26abcdefghij27abcdefghij28abcdefghij29abcdefghij1abcdefghij2abcdefghij3abcdefghij4abcdefghij5abcdefghij6abcdefghij7abcdefghij8abcdefghij9abcdefghij10abcdefghij11abcdefghij12abcdefghij13abcdefgh
```
The full string length is 581 characters, but the matched string was only 529. 

### Steps to Reproduce

1. Create the files shown in the gist and run the command demonstrated in the gist

## Environment
 * OS: MacOS
 * Sequoia 15.1.1

## Additional Context

This seems to only happen with the last match in the file and only if the string is rather large (approximately more than 520 characters, not sure the exact amount). Any prior tokens match correctly. It doesn't seem to be important that the last match is on the last line of the file either, there can be junk text on the last few lines but the last match will still have a problem.

My custom regex is more complicated than this, but I was able to reproduce the bug I was seeing with this over-simplified example. This is a pretty annoying bug because I know my custom regex is going to report many false negatives currently.

**Comment by rgmz** [comment]
Seems related to: https://github.com/trufflesecurity/trufflehog/pull/2812#issuecomment-2101784004

**Comment by kashifkhan0771** [comment]
Thanks, @rgmz, for pointing me in the right direction! To enable TruffleHog to scan the entire chunk, we need to set the `scan-entire-chunk` flag. After adding the flag, it successfully captured the full secret (see the attached screenshot for reference):

![Screenshot from 2024-12-19 11-13-44](https://github.com/user-attachments/assets/63a6477f-8d30-406c-845e-ae7eb68cfd3c)

It’s unclear how large a chunk needs to be for this flag to become necessary. Perhaps @ahrav can provide more insight into that.
