### ISSUE TITLE
Add detector name to JSON output

### ISSUE THREAD

**Issue by chr-b** [trufflesecurity/trufflehog#385]
**Is your feature request related to a problem? Please describe.**
When running trufflehog with `--json` output, a `DetectorType` field is available in the output. This field is an integer value, not a string identifier.

**Describe the solution you'd like**
Add an additional field to the JSON output. E.g. `DetectorName` that provides the name of the secrets detector (e.g. `AWS` for the AWS access key detector).

**Describe alternatives you've considered**
I am not sure how to perform a dynamic mapping from detector type (the integer ID) to the detector name.

**Additional context**
I have only tested this with the Github command.

**Comment by mvastola** [comment]
I was literally about to post something similar. Alternatively/additionally, is there a way to obtain a list showing the ID to name mappings? (Especially for processing existing results.)

**Comment by mvastola** [comment]
@kstilwell that helps. Not sure why it wasn't coming up in search. Thanks!

**Comment by dustin-decker** [comment]
We'd like to change this to be the string value of the enum. Right now it's just directly marshaling the protobuf type which marshals the enums as an integer in the JSON.

**Comment by richa-p** [comment]
+1 to this request, it will be a lot easier to relate to the finding.

**Comment by mattnedrich** [comment]
+1 to this as well

**Comment by dustin-decker** [comment]
Fixed in #538, released in v3.4.5
