### ISSUE TITLE
add verified

### ISSUE THREAD

**Issue by marcelo321** [trufflesecurity/trufflehog#393]
There is a flag `--only-verified` which is used to only output verified results. Would it be possible that when using that flag, it output also how was the result verified?

e.g if it is a curl command, you would get:

```
Verify: curl example.com/whatever?apikey=APIKEY
```

**Comment by dustin-decker** [comment]
Hey Marcelo, I don't think we will add this. It would be a very large effort for the amount of credentials that we cover. 
The source code is available for you to look at to construct a curl request.

**Comment by dustin-decker** [comment]
Actually, after a brief moment of thinking, it's possible do this programatically by converting go's http.Request to a curl command, and it looks like libraries already exist to do so: https://github.com/moul/http2curl

This would certainly help with disclosing findings.

**Comment by shreyas-sriram** [comment]
## Possible solution

I was looking into this and one possible solution is to modify `Verified bool` https://github.com/trufflesecurity/trufflehog/blob/6de778d5108415fba3a582ef26e3ce35fb00d527/pkg/detectors/detectors.go#L29 to a struct. That struct will have two fields; one to know if it is verified and the other is the curl request.

Something like this.

```
type Verified struct {
    IsVerified bool
    RequestPOC *CurlCommand
}
```

The values for this will have to be updated whenever verification is successful. For example, here. https://github.com/trufflesecurity/trufflehog/blob/6de778d5108415fba3a582ef26e3ce35fb00d527/pkg/detectors/digitaloceantoken/digitaloceantoken.go#L59

This will be modified to something like this.

```
s1.IsVerified = true
s1.RequestPOC = http2curl.GetCurlCommand(req)
```

## Notes

This solution sounds tedious to me. Is there a better way to add this functionality?

**Comment by dustin-decker** [comment]
I think we might be able to do this with a custom roundtripper in the http.Client that we use for verification. It could use http2curl to print the output when the option is set. This would work for client libraries too as long as we can set the custom http.Client.

**Comment by shreyas-sriram** [comment]
Good idea, but how do we filter and print only the ***successfully verified*** requests? From my understanding, it is not good practice to have logic in the custom roundtripper.

Otherwise, it is going to be too noisy by printing all verification requests.

**Comment by 0x736E** [comment]
While I'm not convinced of the value of this feature for 'standard' secret types such as AWS, GCP, etc. given that the method(s) for verification are unlikely to change much over time, and are mostly self evident, I don't really see the value here. 

That said, the relatively new addition of the "verification server" feature makes this enhancement *much* more valuable and I dare say necessary. Given that it is possible that a secret may be verified by non-standard means (via a custom verification server), there is a lot of value in knowing the method(s) by which a "custom" (RegEx) secret was verified.

**Comment by shreyas-sriram** [comment]
Revisiting this as part of hacktober.

I noticed the `Result` struct has `ExtraData`, which can be used to store the curl validation request (coming out of http2curl).

https://github.com/trufflesecurity/trufflehog/blob/6de778d5108415fba3a582ef26e3ce35fb00d527/pkg/detectors/detectors.go#L35

Should be a fairly simple task; would require modifying all detectors to add this in the `ExtraData` field. What do you think? @dustin-decker

**Comment by marcelo321** [comment]
As a side comment, where should I look how a apikey is verified? I mean, in what file? I found a verified "airbrake" apikey, but following the docs I get auth error when testing the apikey.

And I can't find how was the apikey "verified".

Would appreciate any help :)

**Comment by clonsdale-canva** [comment]
This would be great since often you want to re-verify to confirm that the token has been successfully revoked. It's tricky to work out how without re-running trufflehog again. It would be amazing to generate a curl command where possible to verify that the secret no longer works

**Comment by shreyas-sriram** [comment]
+1 to @clonsdale-canva

**Comment by rgmz** [comment]
Perhaps general verification steps could be listed alongside remediation advice on https://howtorotate.com/?

**Comment by shreyas-sriram** [comment]
Would suggest keeping it along with the code for parity.

**Comment by rgmz** [comment]
While that is a concern, I'm not sure how you'd feasibly implement this without making the output significantly more verbose.

Plus, it's still possible for the code and instructions to get out if sync even if they're stored together. It's not _as_ likely, but it's still possible.

**Comment by zricethezav** [comment]
We don't plan on supporting this feature as for this to be useful we would have to expose the secret. Additionally, not all detectors rely on simple auth flows. Some have more complex auth flows that can't be captured in a simple curl command
