### ISSUE TITLE
Allow for checking local branches as well as remotes

### ISSUE THREAD

**Issue by bbriggs** [trufflesecurity/trufflehog#40]
Tool currently only checks remote branches. Would be great to check local branches as well before something gets pushed off that shouldn't be.

**Comment by cjbarker** [comment]
@bbriggs and @dxa4481, I need this feature and don't mind adding it in the next couple weeks.

**Comment by cjbarker** [comment]
Already supports checking local branches, but added validation logic and usage with following pull request:

https://github.com/dxa4481/truffleHog/pull/47

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It can scan local repositories by using the `git file://.` option.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
