### ISSUE TITLE
--since-commit does not include changes from current commit

### ISSUE THREAD

**Issue by krzychurra** [trufflesecurity/trufflehog#413]
**Describe the bug**
`--since-commit` flag does not include changes from current commit

**To Reproduce**
1. Create a commit with secret that should be detected (to simplify lets say that commit hash is 9b73705 - latest commit present on branch)
2. Run trufflehog with flag `--since-commit="9b73705"`
3. No secrets found
4. Run trufflehog again, but this time point to previous latest commit (e.g. 864f8dd)
5. Secret found from 9b73705 commit

**Expected behavior**
Trufflehog should include changes from pointed in flag commit. It's a real problem for me when I need to scan changes on very first commit on a new branch (there is no previous commits so trufflehog does not find anything suspicious)

**Comment by dustin-decker** [comment]
The fix will make it into the next release after v3.3.1

**Comment by krzychurra** [comment]
@dustin-decker @bill-rich Thank you! Now it works like a charm!

**Comment by dustin-decker** [comment]
Glad to hear it. Thanks for the bug report.
