### ISSUE TITLE
Github Action Lacks Documentation 

### ISSUE THREAD

**Issue by johnwaghorn** [trufflesecurity/trufflehog#434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description	
The Official GitHub action for Trufflehog lacks documentation.
## Problem to be Addressed
The Official Github action for Trufflehog lacks documentation, no details of arguments that can be used or how it should be used. 
## Description of the Preferred Solution
Documentation for the GitHub action which details each possible argument and an example of a workflow yaml config for the action would be nice. This could exist in the readme.md for example.

**Comment by dustin-decker** [comment]
Fixed in #439. Big speed improvement coming soon from #493  as well.
