### ISSUE TITLE
Wrong details in Trufflehog Output

### ISSUE THREAD

**Issue by SecTheBit** [trufflesecurity/trufflehog#435]
I created a set of api keys for testing in my github repository : https://github.com/SecTheBit/Test_Keys.
Running trufflehog on this repo give a good result but in one section , it have given a result regarding bulbul api (as shown below). In this output , it is mentioned about line, **Line:27** , which means that api keys are on line 27 of that particular file, but the  keys file is ended with 23 lines. Why and How it is showing Line : 27. Although, it is showing the correct API key.

```
Found verified result 🐷🔑
Detector Type: Bulbul
Raw result: fdcq6ajxg4q6to8mjprckzis26ptlw7l
Commit: 458a68ff90d7033775a11ec291edc503ce2bde3e
Email: 46895441+SecTheBit@users.noreply.github.com
File: keys
Timestamp: 2022-04-20 11:05:35 +0530 IST
Line: 27
Link: https://github.com/SecTheBit/Test_Keys/blob/458a68ff90d7033775a11ec291edc503ce2bde3e/keys
Repository: https://github.com/SecTheBit/Test_Keys.git
```

**Comment by SecTheBit** [comment]
Hi @bill-rich ,

Any update on this?

**Comment by bill-rich** [comment]
Hi @SecTheBit,

I've tracked down the problem and am testing a fix. I should have a PR open for it in the next day or two.

Thank you for including all the info necessary to repro the issue! That helped a lot in figuring out what was going on.
