### ISSUE TITLE
Not scanning FileSystem

### ISSUE THREAD

**Issue by polajenko** [trufflesecurity/trufflehog#483]
### TruffleHog Version

3.3.3

### Expected Behavior

Should have found a secret. I placed a github personal access token into a file on my file system.

### Actual Behavior

Command finished and did not detect the api key.

### Steps to Reproduce

1. Goto command line and run: docker run -it --rm trufflesecurity/trufflehog:latest --verification filesystem --directory=C:\s\github --trace --no-update

## Environment
 * OS: Windows 10
 * Enterprise

**Comment by shreyas-sriram** [comment]
Mount the directory into container - `-v "$PWD:/pwd"`

Instructions are given on the README.

```
docker run -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --org=trufflesecurity
```

**Comment by dustin-decker** [comment]
Thanks @shreyas-sriram , I think you nailed the issue. I'm going to close this issue now, please reopen if it's still not resolved.
