### ISSUE TITLE
Filesystem not finding key secrets

### ISSUE THREAD

**Issue by pranaykute06** [trufflesecurity/trufflehog#486]
### Community Note

I was trying to scan my dictionary with trufflehog 
in my appsettings i put the API Secrets key still it is not able to find it.

Command i have used is :  trufflehog filesystem --directory='E:\MyFolder'

 only scaning binaries
not any other files (eg. .cs, .json ..... etc)

### TruffleHog Version
trufflehog-3.4.1

![image](https://user-images.githubusercontent.com/82197220/165741969-8b30018b-8166-46e8-9c03-efb994512fe8.png)

**Comment by dustin-decker** [comment]
We need more information. What type of api token are you trying to find? What did you put in the file? Please show us the redacted form of it.

**Comment by jessequinn** [comment]
I can attest to this. I have basic auth credentials in a JS file 

```
//TEST : some@email.com       (u#49J@kjS0uT1l9e3)
//TEST : some@email.com       (Password*123)
```

and `trufflehog filesystem --directory=$(echo $PWD) --fail --concurrency=8 --only-verified` returns nothing. In addition, using gitleaks I was able to find credentials in the form of `clientId: 'dsfsdfdsfdsf',` in JS. Is truffle filesystem skipping over Javascript?

**Comment by pranaykute06** [comment]
API token like a client secrete key in **appsettings.json** 
e.g. =>   "ClientSecret": "IZtxkHrgHnvN3ObIe4fffox+FBviIv2kl+wewz8beVjKyi2r5847gffrrrYyNhmhO/5ycyt3NpE8d7ee44UYwaMHFrk9KuF8qhdw=="

I have also try putting code in my **.cs file (class file)**
string password = "myPass@123#kl"

Still trufflehog is not capturing it, when I try to run the trufflehog scan on the dictionary which contains above file.
trufflehog filesystem --directory="E:\AssetWiseReliability"

It is scanning only binary files. and gives me non varified results

**Comment by dustin-decker** [comment]
These look like 'generic' secrets, which TruffleHog does not currently support. We have nearly 700 specific detectors (and growing) implemented in  [`pkg/detectors`](pkg/detectors). Generic secret support may arrive as an optional feature in the future.

**Comment by jessequinn** [comment]
honestly that was a bad response. if you dont cover some basic 'generic' secrets then i would think the trufflehog is a misleading product. I look into create a detector for generics.
