### ISSUE TITLE
Add --exclude-paths flag to filesystem module

### ISSUE THREAD

**Issue by JosiahOne** [trufflesecurity/trufflehog#536]
### Description

Like https://github.com/trufflesecurity/trufflehog/issues/420 but for the filesystem module.

## Problem to be Addressed
We frequently use the `filesystem` module to scan large amounts of code. There are many directories we'd like to exclude for a variety of reasons (but the most common being test data that has intentional creds) and we were hoping we could creating a file to ignore these directories just like when using the `git` module.

Unfortunately, it seems the `--exclude-paths` flag is unavailable for filesystem scanning.

## Description of the Preferred Solution
Provide `--exclude-paths` using exactly the same interface as the `git` module.

**Comment by hassanejaz** [comment]
Is this prioritised.. would love for this to be added ASAP.
