### ISSUE TITLE
Scanning Github repo's based on User-assigned or GitHub assigned labels

### ISSUE THREAD

**Issue by saurabhlime** [trufflesecurity/trufflehog#537]
Description
Currently there is a feature of scanning a repository or an organization. The problem here is usually only 10% to 20% of the repo's in the organization are actually in the scope of assessment for a variety of reasons. It would be great to scan repo's based on the labels assigned to repository. These labels can be user-defined e.g SOX-in-scope, Mobile App, Web App, IAC or Github-assigned e.g Private, Public, Archive etc.

Problem to be Addressed
A product/application may use multiple repositories linked to that product. To scan all the repositories associated a label tag will help to scan secrets.

Description of the Preferred Solution
What information may be required and what would be the preferred way to provide it? 
**docker run --platform linux/arm64 -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --label <>**

* #0000

**Comment by zricethezav** [comment]
We don't plan on supporting this feature. 

You use existing option to produce the behavior you desire though by manually creating a list and using `--include-repos` and `--exclude-repos`

```
      --include-repos=INCLUDE-REPOS ...
                                 Repositories to include in an org scan. This can also be a glob pattern. You can repeat this flag. Must use
                                 Github repo full name. Example: "trufflesecurity/trufflehog", "trufflesecurity/t*"
      --exclude-repos=EXCLUDE-REPOS ...
                                 Repositories to exclude in an org scan. This can also be a glob pattern. You can repeat this flag. Must use
                                 Github repo full name. Example: "trufflesecurity/driftwood", "trufflesecurity/d*"
```
