### ISSUE TITLE
Cannot run trufflehog in pre-receive hook

### ISSUE THREAD

**Issue by odorT** [trufflesecurity/trufflehog#565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
trufflehog 3.5.0

### Trace Output
https://gist.github.com/odorT/9d9bb7cfc0e1e2ec03d14ce0f18f53d6

### Expected Behavior
returned secret info in git repo

### Actual Behavior
error in trufflehog

## Environment
 * OS: Centos
 * Version 7

## Additional Context
I created server side git pre-receive hook in gilab enterprise host machine custom_hooks directory. This hook works without any issue. But when I tried to use trufflehog command to check if the code contains any secrets, trufflehog throwed error that I pasted above in gist.
### References

* #0000

**Comment by dustin-decker** [comment]
There was probably a permission error while attempting to move the binary during the update process. You can probably fix this by changing the ownership of the folder where the trufflehog binary resides to the user that invokes it.

Could you provide your hook configuration please?

**Comment by KzDog** [comment]
I have the same problem in my Windows 10:

![image](https://user-images.githubusercontent.com/48339783/169932604-68273286-419e-4a80-a7b1-7a9c93d78317.png)

**Comment by bill-rich** [comment]
@KzDog If you are not able to give the user write permissions on the trufflehog binary and folder, you can use the `--no-update` option to skip automatically updating.

**Comment by odorT** [comment]
I could utilize trufflehog with --no-update flag. thanks for the answer
