### ISSUE TITLE
Sarif 2.1.0 output support for CI security

### ISSUE THREAD

**Issue by MNThomson** [trufflesecurity/trufflehog#578]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adding a `Sarif` output format that the Github Security tab can read.

## Problem to be Addressed

Running TruffleHog in Github Actions is awesome! Unfortunately TruffleHog then only outputs to the runner's log which is easy to miss and requires some digging (as well as showing these leaked credentials to any GH user)!

## Description of the Preferred Solution

Github supports [Sarif](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning) uploads for the Security tab. TruffleHog could also output a `SARIF 2.1.0 JSON schema` that can then be uploaded on completion of the job. This would facilitate an easier way to check outputs as well as bring attention to leaked credentials as soon as they arise.

## Additional Context

This most certainly is a large undertaking, but I feel that it would be an invaluable asset to add to TruffleHog's CI capabilities

### References

- [Github Sarif Support](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning)
- [Github CodeQL Sarif docs](https://codeql.github.com/docs/codeql-cli/sarif-output/)
- [sast-scan integration doc](https://github.com/ShiftLeftSecurity/sast-scan/blob/8243fb8c59e8db1dab00aa424978302d970fdc0b/docs/integration.md)
- [Gitleaks Golang Sarif implementation](https://github.com/zricethezav/gitleaks/pull/421/files)

**Comment by zricethezav** [comment]
@MNThomson @dustin-decker I've attempted to find a way to utilize Github's codeql/sarif artifact upload feature but found it pretty useless for secret scanning because secrets are vulnerabilities that exist in a git history. If you upload a sarif report after finding some secrets, then remove those secrets and run the job (TruffleHog or gitleaks) again, the vulnerability report will see that change removing the secrets from the code (but still in the git history) as resolved. 

If there was a way to disable automatic vulnerability resolution this feature would be useful, but I haven't found a way to do that unfortunately.

**Comment by Chumper** [comment]
Sarif output would be useful even if we do not upload it to GitHub directly. as Sarif is a common format for issues other systems that work with Sarif data can then make use of the trufflehog findings.

**Comment by nvuillam** [comment]
[MegaLinter](https://megalinter.io/beta/descriptors/repository_trufflehog/) would love trufflehog to have SARIF too :)

**Comment by zricethezav** [comment]
We don't plan on supporting SARIF

**Comment by nvuillam** [comment]
That's sad , seiing how many people of the community are waiting for it 😐

**Comment by ak-incode** [comment]
If the project supported SARIF, I could just write a bot to reopen security advisories until, e.g., credits contain someone from security signing off that creds were rotated [0].

I don't see why a project providing the mechanism of secret scanning feels the need to intrude into every team's policy of remediation.

[0] - https://docs.github.com/en/rest/security-advisories/repository-advisories?apiVersion=2022-11-28#update-a-repository-security-advisory
