### ISSUE TITLE
Feature Request: only show trigger lines

### ISSUE THREAD

**Issue by t3h2mas** [trufflesecurity/trufflehog#58]
It would be nice to have an option to only display trigger strings instead of the entire commit

**Comment by dend** [comment]
This would also significantly reduce the size of output files (if piped into) since those carry over a lot of unnecessary information.

**Comment by tjohnston01** [comment]
This would be really great. Maybe even have flags like `grep` for `-A`, `-B` etc?

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It includes this information by default under the `raw` field.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
