### ISSUE TITLE
Use existing docker image or binary for github actions

### ISSUE THREAD

**Issue by mcastorina** [trufflesecurity/trufflehog#580]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current github action is building trufflehog every time before scanning. It would be great to use an existing docker image or binary.

**Comment by dustin-decker** [comment]
This was fixed in #534 but the readme referenced an old version of the action.

I opened #582 to fix that.
