### ISSUE TITLE
unrecognized arguments:

### ISSUE THREAD

**Issue by sasholy** [trufflesecurity/trufflehog#583]
can't run it

trufflehog git https://github.com/trufflesecurity/trufflehog.git
usage: trufflehog [-h] [--json] [--regex] [--rules RULES] [--allow ALLOW]
                  [--entropy DO_ENTROPY] [--since_commit SINCE_COMMIT]
                  [--max_depth MAX_DEPTH] [--branch BRANCH] [-i INCLUDE_PATHS_FILE]
                  [-x EXCLUDE_PATHS_FILE] [--repo_path REPO_PATH] [--cleanup]
                  git_url
trufflehog: error: unrecognized arguments: https://github.com/trufflesecurity/trufflehog.git

thx

**Comment by dustin-decker** [comment]
You're still running trufflehog v2. Please see one of our several installation options available for v3: https://github.com/trufflesecurity/trufflehog#installation
