### ISSUE TITLE
Trufflehog as golang lib

### ISSUE THREAD

**Issue by richa-p** [trufflesecurity/trufflehog#590]
Hello,

I would like to try using trufflehog as a lib dependency in my golang project. Is it available as a golang lib?

I am using binary from a docker container but the JSON output isn't in the well formed json format. It's not an array of all the findings. Is there any workaround to get a well formatted JSON output?

**Comment by dustin-decker** [comment]
The JSON output is one JSON object per line. This is known as [NDJSON](http://ndjson.org/). Output as a single array would require withholding all of the output until the end instead of streaming it.

TruffleHog is not intended to be used as a library.

**Comment by dustin-decker** [comment]
You would need to unmarshal each line of json output to an object.

**Comment by richa-p** [comment]
I was able to successfully parse the response and store it for further reporting from a golang program.
