### ISSUE TITLE
Option to use custom regex with and without the already available detectors

### ISSUE THREAD

**Issue by LuD1161** [trufflesecurity/trufflehog#596]
### Description

Currently trufflehog has it's share of over 600 detectors. Which is an exhaustive set in itself.
Here, I am talking about scenarios where a developer/organisation would want to use this and add their custom regexes. 
Such as patterns of internal api keys or code bases etc.

## Problem to be Addressed
Currently there's no option to add custom regexes, as far as I could check.

## Description of the Preferred Solution
It would be good if we could pass in a file with regex pattern on each line.

**Comment by LuD1161** [comment]
I would love to work on this, if someone's not working on this already 😅

**Comment by sjgupta19** [comment]
any update on this? I am trying something like this - 

- name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ env.BRANCH }}
          head: HEAD
          args: "--only-verified --entropy=false --regex --rules=regexes.json"

**Comment by ahrav** [comment]
Hi @LuD1161 i'm going to close this issue as you should now be able to provide a custom regex along with verification as of [V3.20.0](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.20.0)

Some additional information can be found [here](https://docs.trufflesecurity.com/docs/configuration/detectors/#custom-regex)
