### ISSUE TITLE
Becoming FIPS compliant

### ISSUE THREAD

**Issue by smrdawg** [trufflesecurity/trufflehog#607]
I tried to use Trufflehog on a gitlab system that was FIPS compliant.  I got an error that pointed me to line 351 of TruffleHog.py.  This uses MD5, which has been broken.  I downloaded and changed this to use sha256, and rebuilt my container, and it worked on my FIPS compliant system.  I suggest either simply changing this to be sha256, which would make it compliant by default, or creating a -FIPS flag that would swap out the weaker md5 hash for the stronger sha256 hash.

**Comment by dustin-decker** [comment]
This sounds like trufflehog v2 or prior, which was written in python. The current repo's default branch and supported version is v3, written in go. It has many improvements. Please give that a shot when you get a chance.
