### ISSUE TITLE
No binaries in v3.6.5 ?

### ISSUE THREAD

**Issue by leucos** [trufflesecurity/trufflehog#626]
### Description

It seems that for v3.6.5 release, no binaries are provided. Is this normal ?

## Description of the Preferred Solution

It would be nice to have binaries available in assets like in the previous releases.

## Additional Context

This prevents installing trufflehog with [binenv](https://github.com/devops-works/binenv).

**Comment by dustin-decker** [comment]
Sorry about that, it was a broken release so the binaries did not get built.
