### ISSUE TITLE
Missing Line Number when scanning filesystem

### ISSUE THREAD

**Issue by bakwc** [trufflesecurity/trufflehog#636]
### Description

When scanning filesystem there is no "Line" output.

### TruffleHog Version
Version from `main` branch on 27 jun 2022

### Expected Behavior

> Found unverified result 🐷🔑❓
> Detector Type: URI
> Raw result: https://user:password@test:2379
> File: tests/test_etcd.py
> Line: 278

### Actual Behavior

> Found unverified result 🐷🔑❓
> Detector Type: URI
> Raw result: https://user:password@test:2379
> File: tests/test_etcd.py
> 

### Steps to Reproduce

1) Clone any repo with secrets
2) scan it with `filesystem` module

**Comment by dustin-decker** [comment]
Fixed by #1297
