### ISSUE TITLE
Unable to scan git repo with trufflehog

### ISSUE THREAD

**Issue by venkatn087** [trufflesecurity/trufflehog#655]
Hi Team,

I have 2 queries here.
Query 1: I have installed trufflehog in RHEL7  with go lang as per below  steps but when i check for trufflehog version saying "trufflehog is not found".
       git version 2.18.0
       go version go1.18.3 linux/amd64
       mkdir test
       cd test
       git init
      git clone https://github.com/trufflesecurity/trufflehog.git
      cd trufflehog
      go install
      from the same directory,trufflehog git –help 
         Error –trufflehog command not found.
Could you please let mow what other steps do i need to follow if i want to install truffehog with Go lang.

Query no 2:
I have installed trufflehog with source as mentioned below.
    git version 2.18.0
    go version go1.18.3 linux/amd64
    sudo wget https://github.com/trufflesecurity/trufflehog/releases/download/v3.6.7/trufflehog_3.6.7_linux_amd64.tar.gz
    tar -xvf trufflehog_3.6.7_linux_amd64.tar.gz
    sudo mv trufflehog /usr/bin/
    which trufflehog
[brsubbareddy123@apache ~]$ trufflehog git --help
usage: TruffleHog git [<flags>] <uri>

Now when i scan the gitrepo with below command getting the error.
<img width="959" alt="trufflehog1" src="https://user-images.githubusercontent.com/52975559/178574521-3bbeebbd-d9f3-4b7f-8d0d-f4c0a789ff32.PNG">

[brsubbareddy123@trufflehog ~]$ trufflehog git https://github.com/facebook/flipper.git
FATA[0000] error occured with trufflehog updater 🐷       error="cannot move binary (exit status 1)"
[brsubbareddy123@trufflehog ~]$ trufflehog git --regex --entropy=False https://github.com/facebook/flipper.git
trufflehog: error: unexpected https://github.com/facebook/flipper.git, try --help
[brsubbareddy123@trufflehog ~]$

**Comment by dustin-decker** [comment]
The updater encountered a permission issue while trying to replace the binary. You can run with `--no-update` to get around that.

**Comment by DarkSkull91** [comment]
I'm trying to run trufflehog using the latest build for Windows and I get these errors:
![image](https://github.com/trufflesecurity/trufflehog/assets/16278411/d78bfdd6-ee04-4ff6-baea-5d75bd1c8fd3)

Do you have some workaround?

**Comment by rgmz** [comment]
> I'm trying to run trufflehog using the latest build for Windows and I get these errors: ![image](https://user-images.githubusercontent.com/16278411/281285048-d78bfdd6-ee04-4ff6-baea-5d75bd1c8fd3.png)
> 
> Do you have some workaround?

This has nothing to do with this issue. Please make your own issue.
