### ISSUE TITLE
Unauthenticated enterprise github org scan always uses api.github.com

### ISSUE THREAD

**Issue by ArunWesleyGH** [trufflesecurity/trufflehog#657]
Hi There

i am trying to run scan on Linux environment using cmd -
 trufflehog github --org testorg --endpoint myenterprise.github.com

it is searching for the github org in api.github.com instead of the endpoint i mentioned.

Please help to fix.

@mcastorina

**Comment by mcastorina** [comment]
Thanks for reporting. I think the bug is here in the [unauthenticated scan](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/sources/github/github.go#L146).

**Comment by nyanshak** [comment]
The link wasn't a permalink and doesn't seem to show the bug.

In `enumerateWithToken` function ([permalink](https://github.com/trufflesecurity/trufflehog/blob/21258f416008f1e389a1e38b1af08ec5651b9d54/pkg/sources/github/github.go#L301-L309)) - an enterprise client is created if the endpoint doesn't match `https://api.github.com`.

`enumerateUnauthenticated` doesn't replicate this behavior ([permalink](https://github.com/trufflesecurity/trufflehog/blob/21258f416008f1e389a1e38b1af08ec5651b9d54/pkg/sources/github/github.go#L263)), instead always creating a standard github client.

I'm not terribly familiar with Github enterprise and don't have an instance to test against, though it may be possible to try changing `enumerateUnauthenticated` to create different clients based on the endpoint passed in via config.

**Comment by zricethezav** [comment]
This should be supported with the `--endpoint` option. See https://github.com/trufflesecurity/trufflehog/blob/b3040b1227b6d46392e7633570a38464c13402bc/main.go#L78

Reopen if it doesn't work

**Comment by rgmz** [comment]
I believe this was fixed in #1454.
