### ISSUE TITLE
Why these security credentials are not caught by trufflehog?

### ISSUE THREAD

**Issue by agrawalsmart7** [trufflesecurity/trufflehog#678]
Hi Wanted to check why these credentials did not caught by trufflehog?

There is one file present on my github repo. I was hoping trufflehog to find these creds but it didn't. Is the tool only finds popular keys like AWS Secret Keys? 

<?php

$username = "Utkarsh_testing"
$password = "Testing_Purpose_88_**"
  
  $newvar = $_GET["testing"];
echo $newvar;

?>

**Comment by ahrav** [comment]
Hi @agrawalsmart7,

Would you mind elaborating a little more on what credentials you were hoping to find? If it's a public repo could you link it here? This is the current list of detectors that are used by the software when finding credentials. https://github.com/trufflesecurity/trufflehog/blob/main/proto/detectors.proto

For each of the listed detectors, there should be a corresponding Go file that includes the regexes used when trying to match credentials. For example, AWS credential detection uses this file https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/aws/aws.go

Additionally, to reduce the number of false positives you will see the code in the detectors' specific keywords. Those are used before the regex comparison.

Let us know if your repo contains credentials in the current list of detectors and is still not being detected.
