### ISSUE TITLE
GitHub Action version 3.7.1 is failing

### ISSUE THREAD

**Issue by okiedork** [trufflesecurity/trufflehog#690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

GitHub Action 3.7.1 - `trufflesecurity/trufflehog@047e2b4607487da3c05564ec9b198cf22a048310`

### Trace Output

gist: https://gist.github.com/okiedork/d4d31956b2f115c85ad597290207762e

### Expected Behavior

The action should have succeeded.

### Actual Behavior

The action failed with message: `trufflehog: error: unexpected , try --help`

### Steps to Reproduce

1. Update the trufflehog action to version 3.7.1
2. Run the action

## Additional Context

Probably caused because the recently added `extra-args` option is being passed to the cli as `""`, if no extra-args are set.

Example reproducing the same error message using trufflehog cli:

```shell
./trufflehog git file://./ --since-commit develop --branch HEAD --fail ""
trufflehog: error: unexpected , try --help
```

### References

#670

**Comment by dustin-decker** [comment]
Can you try v3.7.3 please? This did get broken for 3.7.0 and 3.7.1 I believe. Sorry about that.

**Comment by okiedork** [comment]
I've tested v3.7.3 and it is working fine now. Thanks.
