### ISSUE TITLE
Missing necessary step for adding a new detector

### ISSUE THREAD

**Issue by jonandersenverkada** [trufflesecurity/trufflehog#692]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
trufflehog dev

### Trace Output

N/A

### Expected Behavior

Following the steps in Adding_Detectors_external.md allows you to build and run your new detector.

### Actual Behavior

There is a missing step, required for the new detector to build.  I didn't create a PR for this because I don't know if make protos should do this or if it should be a manual documented step.

### Steps to Reproduce

Follow the steps in Adding_Detectors_external.md

The new detector will not be built.

The missing step is to add "github.com/trufflesecurity/trufflehog/v3/pkg/detectors/mydetector" and "mydetector.Scanner{}," to pkg/engine/defaults.go.  Without this import the new detector isn't even built.

## Environment
 * OS: Mac OS 
 * Version 11.6 (Big Sur)

**Comment by dustin-decker** [comment]
This is a manual step. Feel free to make a PR for it.

**Comment by dxa4481** [comment]
Closing this for now

**Comment by pulkitanz** [comment]
This hasn't been implemented yet! Best to keep it open.
