### ISSUE TITLE
Okta, MadKudu, Metrilo and GCP False verified results

### ISSUE THREAD

**Issue by MalwareJuice** [trufflesecurity/trufflehog#694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello team :)

### TruffleHog Version
3.7.2

### Output
Gist contains many false verified results for Okta, MadKudu, Metrilo and GCP
https://gist.github.com/MalwareJuice/8166453c705c4640962723363a59b835

### Steps to Reproduce
MadKudu and Metrila results from here:
trufflehog github --only-verified --repo https://github.com/duckduckgo/tracker-radar
Okta:
trufflehog github --only-verified --repo https://github.com/duckduckgo/duckduckgo-privacy-extension
GCP:
trufflehog github --only-verified --repo https://github.com/kubernetes/kubernetes
GCP:
trufflehog github --only-verified --repo https://github.com/kubernetes/autoscaler

## Environment
 Ubuntu 20.04.4 LTS

* #0000

**Comment by dxa4481** [comment]
Hi @MalwareJuice 

I haven't had a chance to go through all of the results, but I was able to confirm some of these results are not false positives. In particular, the GCP key on this line is a real live GCP key. You can view it by base64 decoding the blob: https://github.com/kubernetes/kubernetes/blob/74bc8a3211620397419f0e4ea996e862b070f9bb/test/e2e/common/runtime.go#L241

**Comment by MalwareJuice** [comment]
can you delete the issue please as it may expose some credentials
