### ISSUE TITLE
Trufflehog stuck iwhile running scan on empty git repo

### ISSUE THREAD

**Issue by surajraghuvanshi** [trufflesecurity/trufflehog#695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

suraj:~$ trufflehog --version
trufflehog dev
its version 3 

### Expected Behavior

it should finish the scan if the repo is empty

### Actual Behavior

stuck on empty directory while running the scan

### Steps to Reproduce
trufflehog gitlab --token= gitlab_token --repo gitlab_repo_url

## Environment
 * OS: ubuntu linux
 * Version [e.g. 22]: 20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### References

* #0000

**Comment by zricethezav** [comment]
Closing, this is no longer an issue
