### ISSUE TITLE
SSH URIs No Longer Supported

### ISSUE THREAD

**Issue by VanTekken** [trufflesecurity/trufflehog#720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
3.7.3 (latest)

### Expected Behavior
Scan remote repo for secrets e.g. ssh://github.com/trufflesecurity/trufflehog.

### Actual Behavior
Fails and errors with 'expecting a HTTPS URI'. This is new behavior and previous versions of trufflehog supported scanning of remote repos with ssh URIs.

### Steps to Reproduce
Try to scan a git repo (with SSH keys enabled) using the ssh:// URI:
`trufflehog git ssh://mygit/repo`

**Comment by VanTekken** [comment]
Noticed that this feature hasn't been present since the Python implementation of Trufflehog. Considering Trufflehog has been rewritten in Go since then, this could be re-labeled as a feature request.

**Comment by ahrav** [comment]
@VanTekken I believe as a potential temporary solution you might consider updating your `~/.gitconfig` w/
```
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
```

That being said I do believe we should natively support ssh URIs. We will hopefully support it in one of the next few releases.

**Comment by VanTekken** [comment]
The issue seems to be with [net/url.Parse](https://pkg.go.dev/net/url#Parse) not supporting Git URLs. Usually failing because git URLs include a colon, making the Parse function expect a port number. There could be other reasons why parsing fails, but this appears to be the main reason in my case. Example URL: ssh://github.com:/VanTekken/trufflehog.

[git-urls](https://pkg.go.dev/github.com/whilp/git-urls) may be a solution. If I find a working method I'll issue a pull request.

**Comment by VanTekken** [comment]
https://github.com/VanTekken/trufflehog
