### ISSUE TITLE
Trufflehog hangs indefinitely after scanning a Jupyter notebook

### ISSUE THREAD

**Issue by dinvlad** [trufflesecurity/trufflehog#728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

`trufflehog dev` (freshly installed from Git)

### Trace Output

https://gist.github.com/dinvlad/7d2f505c56bffb9e743c2ce8f4b2a746

### Expected Behavior

After scan is complete, Trufflehog should report any results found and exit.

### Actual Behavior

The trace says scan is complete, but then it just hangs indefinitely without results or exit 0.

### Steps to Reproduce

```
trufflehog git https://github.com/dinvlad/pyro-cov.git \
    --branch bkotzen-CEPI --max-depth 2 \
    --since-commit 9cd031577750f88648a0cee5f8d6ed781f717c6b --trace
```

## Environment
 * OS: Ubuntu
 * Version: 22.04 LTS

## Additional Context

When I added some debug points to Trufflehog's code, it seems to hang on this line:
https://github.com/trufflesecurity/trufflehog/blob/619ab2027a417cda90d0fc0adf01502fa103df8a/main.go#L276

Perhaps there's some unclosed channel logic that leads to a deadlock?

**Comment by bill-rich** [comment]
Hi @dinvlad,

I ran the command that is giving you trouble but was not able to reproduce the issue. Do you get the same result when running from a different system? What about if you use the [latest tagged version or binary](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.7.3)?

**Comment by dinvlad** [comment]
OK, it seems to complete successfully now. I've used the latest version from Git when I tested it 2 days ago, so something must've fixed it since then. Thanks!

**Comment by andrew-womeldorf** [comment]
I found this issue having the same problem. The repository I was scanning was only TSV files and a Jupyter notebook.
I had been running v3.13.0, but upgrading to v3.16.0 resolved it.
