### ISSUE TITLE
Allow secrets (tokens and access keys) to be passed as env vars

### ISSUE THREAD

**Issue by fenak** [trufflesecurity/trufflehog#735]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow secrets to be passed to `trufflehog` as environment variables.

I got a PR opened for this, see #736 

## Problem to be Addressed

When scanning private repos on a Github organization, repos on Gitlab or S3 buckets, the secrets need to be passed via cli arguments, which might expose those secrets in logs and files like `.bash_history`.

## Description of the Preferred Solution

It should be possible to pass those secrets as env vars. Using AWS as an example, when running the `trufflehog` container in a cloud environment like AWS ECS, the secrets can be injected from AWS Secrets Manager as environment variables, like described here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html#secrets-envvar

## Additional Context

edit: added reference to opened PR

### References

* #736

**Comment by dustin-decker** [comment]
Added in #736

**Comment by dustin-decker** [comment]
This was released in v3.10!

https://github.com/trufflesecurity/trufflehog/releases/tag/v3.10.0
