### ISSUE TITLE
Please add --max-depth parameter to gitlab function

### ISSUE THREAD

**Issue by Robsta86** [trufflesecurity/trufflehog#781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the --max-depth parameter to the gitlab scan function.

## Problem to be Addressed

We like this tool and we would like to do an initial scan on our repositories to see if there are any secrets in the most recent states of the code.

## Description of the Preferred Solution

Please add the --max-depth option to the gitlab function so that it's possible to scan our gitlab instance with a max depth of 1.

* #0000

**Comment by zricethezav** [comment]
Closing as we have no plans on adding this feature
