### ISSUE TITLE
how about  add aliyun cloud oss bucket scan ?

### ISSUE THREAD

**Issue by Conanjun** [trufflesecurity/trufflehog#798]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### References

* #0000

**Comment by zricethezav** [comment]
closing due to incomplete description
