### ISSUE TITLE
Feature Request: Ability to specify a list of files (with wildcard match) to ignore

### ISSUE THREAD

**Issue by gbrayut** [trufflesecurity/trufflehog#8]
Many of our projects have a few files that always contain high entropy strings like SHA1 hashes or Base64 encoded values.  It would be nice to provide a list of files to be be ignored, sort of like a .gitignore file.

**Comment by michaeltlombardi** [comment]
We have this same need with regard to SSIS packages, for example.

**Comment by ryanohoro** [comment]
I haven't found a way to retrieve diff file names. If anyone knows how I'll add a PR for this feature.

**Comment by gbrayut** [comment]
@ryanohoro Should be part of the commit->tree->blob object (See http://gitpython.readthedocs.io/en/stable/tutorial.html#the-tree-object ). Looks like there is a blob.name and blob.path

**Comment by ryanohoro** [comment]
Ah ok, it's not in the commit blob that truffleHog iterates over, it's a separate tree object that's part of the commit. I have to cross-reference the objects. There's multiple "blob" attributes in different classes.

**Comment by ryanohoro** [comment]
Uses blob.a_path instead of tree.blob[n].name.

Let me know if this PR meets your needs.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

There is an option for this `--exclude_paths` in v3.

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3
