### ISSUE TITLE
Trufflehog only lists one token per detection if multiple tokens are present

### ISSUE THREAD

**Issue by ankushgoel27** [trufflesecurity/trufflehog#844]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
Trufflehog dev

### Expected Behavior
For example, if multiple heroku tokens are present(all different), it should list all tokens and not just one
### Current Behaviour
Currently, it only list one token per detection and not all the similar type of tokens present.

# this is not about listing same token multiple times but detecting all tokens of a particular detector. ( Github tokens works as expected)

I believe its related to the end of the detector file where "return detector.CleanResults(results), nil" is present. I changed it to just return like how ghp works and it works fine.

### Steps to Reproduce

1. get multiple tokens for a service. Example - heroku API token. 
2. add those tokens to a file and run trufflehog
3. it only lists one token out of the file.
4. Now replace the "return detectors.CleanResults(results),nil" with just "return" and recompile the trufflehog binary
5. run the trufflehog binary again and it will not detect all tokens present in the file for heroku service

## Environment
OS - kali Linux

### References

* #0000

**Comment by ahrav** [comment]
https://github.com/trufflesecurity/trufflehog/releases/tag/v3.16.2 Should resolve this issue.
