### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by AQAqoma** [trufflesecurity/trufflehog#862]
Hi,

during my testing, i had a file with multiple valid old format tokens and new format tokens. But trufflehog was detecting only 1 of each. it should detect all tokens present in the file.

_Originally posted by @ankushgoel27 in https://github.com/trufflesecurity/trufflehog/issues/841#issuecomment-1275637727_

**Comment by dustin-decker** [comment]
This should be fixed by #856 if we merge it

**Comment by ankushgoel27** [comment]
Tested this PR on my linux machine.

not sure if this is related to AWS detector but ran trufflehog on a directory containing 20 valid AWS credentials in a single file.

trufflehog filesystem --directory=/opt/test  # returns 3 valid credentials and rest as unverified
trufflehog filesystem --directory=/opt/test --only-verified # returns those same 3 valid credentials.
