### ISSUE TITLE
[BUG] Slack Webhook Detector Validation

### ISSUE THREAD

**Issue by marshalltech81** [trufflesecurity/trufflehog#880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
[v3.16.1](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.16.1)

### Trace Output
n/A

### Expected Behavior
Slack Webhooks should be validated

### Actual Behavior
Slack Webhooks are not validated

### Steps to Reproduce

1. Run Trufflehog against a repository that contains a valid Slack Webhook and it will not be validated

## Environment
n/A

## Additional Context
It appears as if the validator is looking for the presence of `missing_text` in the response back.  Slack returns a `400` with `no_text`.  Please see attached screenshot.

### References

* #0000

**Comment by marshalltech81** [comment]
<img width="880" alt="Screen Shot 2022-10-29 at 11 05 09 PM" src="https://user-images.githubusercontent.com/68938002/198860781-d069aec1-14cf-4004-8023-b5b57d59a2f1.png">

**Comment by ahrav** [comment]
Thanks again @marshalltech81 for raising this issue. it is greatly appreciated.
