### ISSUE TITLE
Fatal Error - "concurrent map read and write" when scanning GitHub organization.

### ISSUE THREAD

**Issue by wapplegate** [trufflesecurity/trufflehog#890]
When I run the following command:

`trufflehog github --endpoint https://github.org.com --org MyOrg --token token -j --only-verified`

(https://github.org.com is an on prem version of GitHub enterprise with around 30 repos in the org.)

In some cases, but not all, I'll get the following error:

"fatal error: concurrent map read and write"

![image](https://user-images.githubusercontent.com/974296/199163990-b1fa46b3-022a-4064-9190-1edb9d816fc6.png)

This seems to be a concurrency issue with a map object here:

https://github.com/trufflesecurity/trufflehog/blob/2884864cd3191608afa2fd3b571f9c80bd8ed2a1/pkg/sources/github/github.go#L180

I see this issue mostly when running the trufflehog command in a Docker container created from a custom image. The image uses golang:bullseye as a base. I've installed trufflehog in the Docker image with the following commands:

```
git clone https://github.com/trufflesecurity/trufflehog.git
cd trufflehog; go install
```

I do not seem to run into issues when running this command on Windows however.

**Comment by ahrav** [comment]
Thanks @wapplegate for pointing this out. We really appreciate it. 😄

**Comment by wapplegate** [comment]
No problem, thanks for fixing it so quickly!
