### ISSUE TITLE
sqlserver: wrong keywords

### ISSUE THREAD

**Issue by mac2000** [trufflesecurity/trufflehog#897]
because of wrong keyword, sqlserver detector misses majority of files

instead of single `"sqlserver"` string it should be something like: `"Data Source", "Server", "User ID", "User", "UID", "Password"` which are parts of connection string

**Comment by mnieto** [comment]
The sqlserver keyword is still needed. for example, a jdbc connection string looks like:
jdbc:**sqlserver**://;servername=server_name;authentication=SqlPassword;user=username;password=pass@word1

**Comment by mac2000** [comment]
@mnieto there is an dedicated jdbc detector which [does catch this](https://github.com/trufflesecurity/trufflehog/blob/main/pkg/detectors/jdbc/sqlserver.go#L24), this detector is more for connections strings outside of jdbc

**Comment by zricethezav** [comment]
https://github.com/trufflesecurity/trufflehog/blob/834163acf5343c103e5d1b8bd88a952f23b85bc8/pkg/detectors/sqlserver/sqlserver.go#L28 keywords have been updated
