### ISSUE TITLE
Detect and ignore sops-encrypted secrets

### ISSUE THREAD

**Issue by ckuethe** [trufflesecurity/trufflehog#907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

`trufflehog 3.16.3` (current at the time this bug was filed)

### Trace Output

https://gist.github.com/ckuethe/bfcb6cfa30608a1c4fcb2c929d83e0e0#file-trufflehog-trace

### Expected Behavior

I would like to see trufflehog detect SOPS-encrypted secrets and ignore them.

### Actual Behavior

A line in a SOPS-encrypted file was detected as an Etsy API key. I have thousands of other examples of secret mis-detection (NY Times, Qase, EightxEight, Happi, ...), but I won't bore you with them all.

### Steps to Reproduce

 1. Create an empty git repo
 1. Create a JSON file that one might use to store secret key-value pairs
 1. Encrypt it with SOPS (https://github.com/mozilla/sops) 
 1. Commit the encrypted secret file to repo
 1. Scan repo with `trufflehog  -j --trace git file://.`
 1. Add more secrets, change some secrets, and rerun trufflehog if you don't get any detections

## Environment
 * OS: Ubuntu
 * Version 22.04.1 LTS

## Additional Context

Not every SOPS file exhibits this issue; I'm scanning a large code base (many individual repositories, many years of history, many commits, and many files). I created a trivial input file and encrypted it with SOPS, and it doesn't trigger any particular detector. It certainly triggers with my live secrets though.

I've seen a few partial detections of an API keys for "SomeService", which appear in my SOPS files as `SOMESERVICE_APIKEY: ENC[AES256_GCM,data:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==,iv:YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY=,tag:ZZZZZZZZZZZZZZZZZZZZZZ==,type:str]` (actual values replaced by X, Y, Z). The detectors pick up on the "SOMESERVICE" prefix, and see the appropriate number and type of non-blank characters later on in the line, and call it as a plaintext secret. But they're not.

### References

* https://github.com/mozilla/sops#usage
* #22 would solve this use case for me, if I could ignore lines matching "`ENC\[[A-Z0-9_]+,.+?\]$`"

**Comment by dxa4481** [comment]
Hey there, we rely heavily on verification, since this showed up "verified: false" I'd recommend running `--only-verified` in the future.
