### ISSUE TITLE
Scanning secrets in S3 does not work properly

### ISSUE THREAD

**Issue by mori1209** [trufflesecurity/trufflehog#908]
### TruffleHog Version
trufflehog dev (last-3.16.4)

### Trace Output
https://gist.github.com/mori1209/15831c3d5df4aba4dada4758b5761159

### Expected Behavior
S3 bucket scan that will pass successfully 

### Actual Behavior
The tool failed to perform the scan

### Steps to Reproduce
 1. Run 'trufflehog s3 --bucket=***'
 2. See error

## Environment
 * OS: Kali Linux
 * Version: 2022.3

## Additional Context
I think two options should be added to the scan-
1. Normal scan (probably what's happening now)
2. Scanning with the --no-sign-request flag (S3 CLI command)
In addition, need to give an option for a user to enter his AWS profile (aws configure profile).

**Comment by jperez3** [comment]
I'm experiencing a similar situation/error using trufflehog `3.16.4`, although I'm on an M1 mac

**Comment by bill-rich** [comment]
@mori1209 It doesn't look like the bucket you're scanning is public. If that is the case, you'll need to include some credentials when using trufflehog. You can do that using the `--key` and `--secret` flags.
```
      --key=KEY                  S3 key used to authenticate. Can be provided with environment variable AWS_ACCESS_KEY_ID.
      --secret=SECRET            S3 secret used to authenticate. Can be provided with environment variable AWS_SECRET_ACCESS_KEY.
```

**Comment by jperez3** [comment]
@bill-rich sorry for the delay, I'm still not able to get this to work. Can you please post an example of this working? 

I've tried:
`trufflehog s3 --bucket=bucket-name-goes-here --key=$AWS_ACCESS_KEY_ID --secret=$AWS_SECRET_ACCESS_KEY`

`trufflehog s3 --bucket=bucket-name-goes-here --key --secret` (to see if it would pick up the environment variables) 

`trufflehog s3 --bucket=bucket-name-goes-here --key=$(echo AWS_ACCESS_KEY_ID) --secret=$(echo AWS_SECRET_ACCESS_KEY)`

`av trufflehog s3 --bucket=bucket-name-goes-here --cloud-environment --key=${AWS_ACCESS_KEY_ID} --secret=${AWS_SECRET_ACCESS_KEY}` (with cloud environment flag)

**Comment by pingwin** [comment]
@bill-rich I'm experiencing similar issues as @jperez3.

In a cloud environment, like executing from kubernetes, it's not ideal to provide hard-coded access key's when an assigned role is sufficient. In addition Trufflehog fails to read my default aws credentials as well, forcing users to extract their secrets and record them into my shell history when executing locally.

If there is some piece of documentation that I have missed, I apologize and ask for some direction to that documentation.

**Comment by nerijus** [comment]
@mori1209 or @bill-rich , could you please reopen this issue? It does not work as described in comment https://github.com/trufflesecurity/trufflehog/issues/908#issuecomment-1329671475
