### ISSUE TITLE
Run truffleHog on directories recusively and not just in git repos

### ISSUE THREAD

**Issue by michaelgrifalconi** [trufflesecurity/trufflehog#92]
I would assume it's easy to setup a dummy git repo and scan it, but would be nice to use the tool to scan any file or directory even outside git.

One example is to scan database dumps of project trackers (jira)

**Comment by dxa4481** [comment]
I've got a script here that scans archives, tar.gz's, will this work for you?

https://github.com/dxa4481/santaHog/blob/master/santaHog/scan_archives.py

**Comment by avanier** [comment]
I'll add making a PR for this on my to-do list.

**Comment by Miserlou** [comment]
+1 for this - I'm not sure why git is necessary, I'd like to use this on some dump files!

**Comment by BBerastegui** [comment]
There is already a pull request on this: https://github.com/dxa4481/truffleHog/pull/37

**Comment by cryptid11** [comment]
@Miserlou is obviously not, this is microsoft philosophy here, mixing two or more utilities in one. 
i really dont get why this dont get attention, i cant even make sense of the script to scan archives, is that a completely different thing?!

i pray for this to get solved, good luck
and thanks @dxa4481 anyway, hope you can understand pipe idea sooner of later XD

**Comment by mykter** [comment]
https://github.com/feeltheajf/truffleHog3 implemented this feature.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It includes a new filesystem scanner to do this!

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this issue.
