### ISSUE TITLE
URI detector not verifying basic auth credential

### ISSUE THREAD

**Issue by cruddasj** [trufflesecurity/trufflehog#942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
3.18.0

### Trace Output
https://gist.github.com/cruddasj/43f7bd388cbb5720a7a5cc547728e3f8

### Expected Behavior

When credentials are detected in HTTP/S URIs a verifier runs to test the credentials. Based on the description in https://github.com/trufflesecurity/trufflehog/issues/894 I am of the understanding these should be checked via the likes of a curl command?

### Actual Behavior

When a basic auth username/password combination is supplied in a URI, it is not verified.

### Steps to Reproduce

1. Add a file to an empty directory
2. Add the contents https://user:pass@authenticationtest.com/HTTPAuth/ (username/password for basic auth in URL)
3. Run trufflehog scan using command `docker run -it -v $(pwd):/opt trufflesecurity/trufflehog:3.18.0 filesystem --directory=/opt --only-verified --trace`
4. No results are returned

In the above if you remove the --only-verified flag, an unverified result is found. 

## Environment
 * OS: Ubuntu (Docker version 20.10.19)
 * Version: 18.04.6

### References

https://github.com/trufflesecurity/trufflehog/issues/894

**Comment by dxa4481** [comment]
Hey there. We rely on status code to do basic auth verification, and it looks like the example you provided doesn't respond with standard 2XX/4XX status codes, it just always redirects to another page that always throws a 200.

**Comment by cruddasj** [comment]
@dxa4481 - many thanks for the above (much appreciated)!
