### ISSUE TITLE
help output is very different from tutorial output? please help

### ISSUE THREAD

**Issue by AnubisTwine** [trufflesecurity/trufflehog#943]
### Community Note
![Screenshot from 2022-11-23 12-50-49](https://user-images.githubusercontent.com/78452945/203551637-6d808227-3aa7-4b5b-bf8a-18a6b03619da.png)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Environment
 * OS: [e.g. iOS]
 * Version [e.g. 22]

### References

* #0000

**Comment by dxa4481** [comment]
Hi there, you're looking at the help menu, please use one of the commands in the README, and let us know if you have any issues with those.
