### ISSUE TITLE
[Windows] prog exited with 1 

### ISSUE THREAD

**Issue by gchukfeh** [trufflesecurity/trufflehog#948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
3.18.0

### Expected Behavior

Expected behaviour is for Trufflehog on Windows to run successfully, the same way it does on Mac 

### Actual Behavior

Trufflehog on Windows exits with the error "prog exited with 1" See below:
c:\scripts>
c:\scripts>trufflehog github --repo=https://github.com/xxxxxxxxxxxxx --only-verified --token=xxxxxxxxxxxx --debug
time="2022-11-30T11:33:34-05:00" level=debug msg="running version 3.18.0"
2022/11/30 11:33:34 [updater parent] run
2022/11/30 11:33:34 [updater parent] checking for updates...
2022/11/30 11:33:35 [updater parent] failed to get latest version: already up to date
2022/11/30 11:33:35 [updater parent] starting c:\scripts\trufflehog.exe
time="2022-11-30T11:33:35-05:00" level=debug msg="running version 3.18.0"
2022/11/30 11:33:35 [updater child#1] run
2022/11/30 11:33:35 [updater child#1] start program
trufflehog 3.18.0
time="2022-11-30T11:33:35-05:00" level=debug msg="running with up to 1 workers"
time="2022-11-30T11:33:35-05:00" level=debug msg="loaded 2 decoders"
time="2022-11-30T11:33:35-05:00" level=debug msg="loaded 731 detectors total, 731 with verification enabled. 0 with verification disabled"
time="2022-11-30T11:33:35-05:00" level=info msg="starting pprof and fgprof server on :18066 /debug/pprof and /debug/fgprof"
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

time="2022-11-30T11:33:35-05:00" level=debug msg="Found 1 total repos to scan"
time="2022-11-30T11:33:35-05:00" level=debug msg="attempting to clone repo 1/1" name="trufflehog - github" repo="https://github.com/xxxxxxxxxxx” source=SOURCE_TYPE_GITHUB
2022/11/30 11:33:36 [updater parent] checking for updates...
2022/11/30 11:33:54 [updater parent] prog exited with 1

### Steps to Reproduce

 Run trufflehog on Windows

## Environment
 * OS: [Windows]
 * Version [3.18.0]

### References
https://trufflehog-community.slack.com/archives/CK3UYAQF2/p1669827602487819

<img width="1582" alt="Screenshot 2022-11-30 at 11 37 39 AM" src="https://user-images.githubusercontent.com/5022643/204934523-7904fd94-d709-4ec4-a0ee-e78c4a8d846f.png">

**Comment by zricethezav** [comment]
Closing this issue as there has been significant changes since `3.18.0`. Feel free to reopen if this issue still persists
