### ISSUE TITLE
Add scanning for user repos

### ISSUE THREAD

**Issue by uvulpos** [trufflesecurity/trufflehog#949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As you already implemented the organization flag, as a private user, I want to check for my personal repos as well. The cherry on top would be even scanning private repositories, but this would be optional I guess 🙂  

## Problem to be Addressed

As you already implemented the organization flag, as a private user, I want to check for my personal repos as well. The cherry on top would be even scanning private repositories, but this would be optional I guess 🙂  

## Description of the Preferred Solution
An application-flag to define a user or to use a access token / ssh key

**Comment by coffeepenbit** [comment]
You can specify `github --org "<username>"`. Though, this doesn't satisfy your private repo request.

**Comment by CameronLonsdale** [comment]
Does that command still work? Debug trace on latest shows 404 on `https://api.github.com/orgs/cameronlonsdale/repos?per_page=100` for my account for example. The URL seems to need to be `https://api.github.com/users/cameronlonsdale/repos?per_page=100` with /users instead.

**Comment by zricethezav** [comment]
> You can specify github --org "<username>". Though, this doesn't satisfy your private repo request.

Just tested this and it does not work. Opening this issue up for contributions. Should be _relatively_ easy to implement

**Comment by sherlocksecurity** [comment]
Any updates on this? Or any workaround to solve this?
