### ISSUE TITLE
Unable to find username and password in github commit

### ISSUE THREAD

**Issue by mori1209** [trufflesecurity/trufflehog#964]
### TruffleHog Version
trufflehog dev v3.18.0 

### Trace Output
The output I get is empty

### Expected Behavior

That will find for me the username and password found in one of the github commits

Nothing found

 Run the next command on Github repository that include commit with username:password
trufflehog git https://github.com/.../.../ 

### References
The tool fails to find a "username" and "password" that appear in the github commit

![image](https://user-images.githubusercontent.com/63657758/206206476-71252061-08a2-4dbf-802a-d311f43eedd3.png)

**Comment by zricethezav** [comment]
The example provided shouldn't be flagged as a secret as there isn't enough context to determine what the secret provider is
