### ISSUE TITLE
go install - missing dot in first path element

### ISSUE THREAD

**Issue by rip752** [trufflesecurity/trufflehog#988]
build github.com/trufflesecurity/trufflehog/v3: cannot load embed: malformed module path "embed": missing dot in first path element
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Steps to Reproduce

 Distributor ID:	Elementary
Description:	elementary OS 6.1 Jólnir
Release:	6.1
Codename:	jolnir

### References

* #0000

**Comment by JoeUser47** [comment]
I had this error when running go install using Ubuntu's apt golang-go install, which loaded go version 1.13. Removing that version and installing go binary 1.20 from https://go.dev/dl/ resolved for me.

**Comment by zricethezav** [comment]
closing this issue as there are no steps to reproduce

**Comment by octaviovg** [comment]
> I had this error when running go install using Ubuntu's apt golang-go install, which loaded go version 1.13. Removing that version and installing go binary 1.20 from https://go.dev/dl/ resolved for me.

this helped me to install correctly trufflehog. I use version 1.21.4
