### ISSUE TITLE
Add max-depth limit to GitHub subcommand

### ISSUE THREAD

**Issue by dwilliamsstc** [trufflesecurity/trufflehog#989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ability to limit the depth of the commit history being scanned for GitHub users We need the ability to set a --max-depth= limit to GitHub sub command.  

## Problem to be Addressed

It is very noisy for large GitHub enterprises to detect new issues due to the inability to ignore historical commit history that one has already remediated.  Results have to be saved into a spreadsheet or database and then diff'd to see what has changed.  

## Description of the Preferred Solution
 

The ability to set a --max-depth= limit to GitHub sub command. 
This would be very beneficial when attempting to scan a GitHub enterprise repositories as a group.  

### References

* #0000

**Comment by CameronLonsdale** [comment]
Yes please, would be great to specify --depth=1 which is passed to the git clone command. For the more continuous scans which don't need to go through the entire commit history, just the current files.

**Comment by hoernrob** [comment]
would love to have this as well
